In [2]:
import pandas as pd
import nflreadpy as nfl
import polars as pl

In [3]:
weekly = nfl.load_player_stats([2025])
weekly

shape: (19_421, 145)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ player_id ┆ player_na ┆ player_di ┆ position ┆ … ┆ pt_return ┆ pt_net_ya ┆ fantasy_p ┆ fantasy_p │
│ ---       ┆ me        ┆ splay_nam ┆ ---      ┆   ┆ _tds      ┆ rds       ┆ oints     ┆ oints_ppr │
│ str       ┆ ---       ┆ e         ┆ str      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│           ┆ str       ┆ ---       ┆          ┆   ┆ i32       ┆ i32       ┆ f64       ┆ f64       │
│           ┆           ┆ str       ┆          ┆   ┆           ┆           ┆           ┆           │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 00-002345 ┆ A.Rodgers ┆ Aaron     ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 25.66     ┆ 25.66     │
│ 9         ┆           ┆ Rodgers   ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-002385 ┆ M.Prater  ┆ Matt      ┆ K        ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 3         ┆           ┆ Prater    ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-002556 ┆ N.Folk    ┆ Nick Folk ┆ K        ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 5         ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-002615 ┆ J.Flacco  ┆ Joe       ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 12.2      ┆ 12.2      │
│ 8         ┆           ┆ Flacco    ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-002619 ┆ C.Campbel ┆ Calais    ┆ DE       ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 0         ┆ l         ┆ Campbell  ┆          ┆   ┆           ┆           ┆           ┆           │
│ …         ┆ …         ┆ …         ┆ …        ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 00-004069 ┆ W.Campbel ┆ Will      ┆ OT       ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 9         ┆ l         ┆ Campbell  ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-004071 ┆ C.Woodson ┆ Craig     ┆ SAF      ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 6         ┆           ┆ Woodson   ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-004073 ┆ N.Emmanwo ┆ Nick      ┆ SAF      ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 3         ┆ ri        ┆ Emmanwori ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-004073 ┆ T.Henders ┆ TreVeyon  ┆ RB       ┆ … ┆ 0         ┆ 0         ┆ 4.5       ┆ 7.5       │
│ 4         ┆ on        ┆ Henderson ┆          ┆   ┆           ┆           ┆           ┆           │
│ null      ┆ null      ┆ null      ┆ null     ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [4]:
print(type(weekly))
print(weekly.shape)
print(weekly.columns)

<class 'polars.dataframe.frame.DataFrame'>
(19421, 145)
['player_id', 'player_name', 'player_display_name', 'position', 'position_group', 'headshot_url', 'season', 'week', 'season_type', 'game_id', 'team', 'opponent_team', 'completions', 'attempts', 'passing_yards', 'passing_tds', 'passing_interceptions', 'sacks_suffered', 'sack_yards_lost', 'sack_fumbles', 'sack_fumbles_lost', 'passing_air_yards', 'passing_yards_after_catch', 'passing_first_downs', 'passing_epa', 'passing_cpoe', 'passing_2pt_conversions', 'pacr', 'passing_10', 'passing_16', 'passing_20', 'passing_40', 'carries', 'rushing_yards', 'rushing_tds', 'rushing_fumbles', 'rushing_fumbles_lost', 'rushing_first_downs', 'rushing_epa', 'rushing_2pt_conversions', 'rushing_10', 'rushing_12', 'rushing_20', 'rushing_40', 'receptions', 'targets', 'receiving_yards', 'receiving_tds', 'receiving_fumbles', 'receiving_fumbles_lost', 'receiving_air_yards', 'receiving_yards_after_catch', 'receiving_first_downs', 'receiving_epa', 'receiving_2pt_conversions', 'receiving_10', 'receiving_16', 'receiving_20', 'receiving_40', 'racr', 'target_share', 'air_yards_share', 'wopr', 'special_teams_tds', 'def_tackles_solo', 'def_tackles_with_assist', 'def_tackle_assists', 'def_tackles_for_loss', 'def_tackles_for_loss_yards', 'def_fumbles_forced', 'def_sacks', 'def_sack_yards', 'def_qb_hits', 'def_interceptions', 'def_interception_yards', 'def_pass_defended', 'def_tds', 'def_fumbles', 'def_safeties', 'misc_yards', 'fumble_recovery_own', 'fumble_recovery_yards_own', 'fumble_recovery_opp', 'fumble_recovery_yards_opp', 'fumble_recovery_tds', 'penalties', 'penalty_yards', 'fumbles_forced_by_opp', 'fumbles_not_forced', 'fumbles_out_of_bounds', 'fumbles_total', 'fumbles_lost_total', 'punt_returns', 'punt_return_yards', 'kickoff_returns', 'kickoff_return_yards', 'fg_made', 'fg_att', 'fg_missed', 'fg_blocked', 'fg_long', 'fg_pct', 'fg_made_0_19', 'fg_made_20_29', 'fg_made_30_39', 'fg_made_40_49', 'fg_made_50_59', 'fg_made_60_', 'fg_missed_0_19', 'fg_missed_20_29', 'fg_missed_30_39', 'fg_missed_40_49', 'fg_missed_50_59', 'fg_missed_60_', 'fg_made_list', 'fg_missed_list', 'fg_blocked_list', 'fg_made_distance', 'fg_missed_distance', 'fg_blocked_distance', 'pat_made', 'pat_att', 'pat_missed', 'pat_blocked', 'pat_pct', 'gwfg_made', 'gwfg_att', 'gwfg_missed', 'gwfg_blocked', 'gwfg_distance', 'pt_att', 'pt_blocked', 'pt_long', 'pt_yards', 'pt_inside_20', 'pt_out_of_bounds', 'pt_downed', 'pt_touchback', 'pt_fair_caught', 'pt_returned', 'pt_return_yards', 'pt_return_tds', 'pt_net_yards', 'fantasy_points', 'fantasy_points_ppr']

In [5]:
receivers = weekly.filter(weekly['position'] == 'WR')
receivers

shape: (2_623, 145)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ player_id ┆ player_na ┆ player_di ┆ position ┆ … ┆ pt_return ┆ pt_net_ya ┆ fantasy_p ┆ fantasy_p │
│ ---       ┆ me        ┆ splay_nam ┆ ---      ┆   ┆ _tds      ┆ rds       ┆ oints     ┆ oints_ppr │
│ str       ┆ ---       ┆ e         ┆ str      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│           ┆ str       ┆ ---       ┆          ┆   ┆ i32       ┆ i32       ┆ f64       ┆ f64       │
│           ┆           ┆ str       ┆          ┆   ┆           ┆           ┆           ┆           │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 00-003003 ┆ A.Thielen ┆ Adam      ┆ WR       ┆ … ┆ 0         ┆ 0         ┆ 2.0       ┆ 2.0       │
│ 5         ┆           ┆ Thielen   ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-003027 ┆ K.Allen   ┆ Keenan    ┆ WR       ┆ … ┆ 0         ┆ 0         ┆ 12.8      ┆ 19.8      │
│ 9         ┆           ┆ Allen     ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-003056 ┆ D.Hopkins ┆ DeAndre   ┆ WR       ┆ … ┆ 0         ┆ 0         ┆ 9.5       ┆ 11.5      │
│ 4         ┆           ┆ Hopkins   ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-003123 ┆ B.Cooks   ┆ Brandin   ┆ WR       ┆ … ┆ 0         ┆ 0         ┆ 2.6       ┆ 5.6       │
│ 6         ┆           ┆ Cooks     ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-003138 ┆ D.Adams   ┆ Davante   ┆ WR       ┆ … ┆ 0         ┆ 0         ┆ 5.1       ┆ 9.1       │
│ 1         ┆           ┆ Adams     ┆          ┆   ┆           ┆           ┆           ┆           │
│ …         ┆ …         ┆ …         ┆ …        ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 00-003854 ┆ J.Smith-N ┆ Jaxon Smi ┆ WR       ┆ … ┆ 0         ┆ 0         ┆ 2.7       ┆ 6.7       │
│ 3         ┆ jigba     ┆ th-Njigba ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-003860 ┆ K.Boutte  ┆ Kayshon   ┆ WR       ┆ … ┆ 0         ┆ 0         ┆ 2.1       ┆ 3.1       │
│ 8         ┆           ┆ Boutte    ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-003862 ┆ D.Douglas ┆ DeMario   ┆ WR       ┆ … ┆ 0         ┆ 0         ┆ 4.5       ┆ 9.5       │
│ 1         ┆           ┆ Douglas   ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-003875 ┆ J.Bobo    ┆ Jake Bobo ┆ WR       ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 2         ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-004013 ┆ K.William ┆ Kyle      ┆ WR       ┆ … ┆ 0         ┆ 0         ┆ 0.7       ┆ 1.7       │
│ 1         ┆ s         ┆ Williams  ┆          ┆   ┆           ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [24]:
receiving_stats = receivers.select([
    "player_display_name",
    "season",
    "week",
    "team",
    "opponent_team",
    "receptions",
    "targets",
    "receiving_yards",
    "receiving_tds",
    "receiving_fumbles_lost",
    "receiving_2pt_conversions",
    "special_teams_tds",
    "rushing_yards",
    "rushing_tds",
    "rushing_fumbles_lost",
    "rushing_2pt_conversions",
    "fantasy_points_ppr",
])

receiving_stats

shape: (2_623, 17)
┌──────────────┬────────┬──────┬──────┬───┬─────────────┬──────────────┬─────────────┬─────────────┐
│ player_displ ┆ season ┆ week ┆ team ┆ … ┆ rushing_tds ┆ rushing_fumb ┆ rushing_2pt ┆ fantasy_poi │
│ ay_name      ┆ ---    ┆ ---  ┆ ---  ┆   ┆ ---         ┆ les_lost     ┆ _conversion ┆ nts_ppr     │
│ ---          ┆ i32    ┆ i32  ┆ str  ┆   ┆ i32         ┆ ---          ┆ s           ┆ ---         │
│ str          ┆        ┆      ┆      ┆   ┆             ┆ i32          ┆ ---         ┆ f64         │
│              ┆        ┆      ┆      ┆   ┆             ┆              ┆ i32         ┆             │
╞══════════════╪════════╪══════╪══════╪═══╪═════════════╪══════════════╪═════════════╪═════════════╡
│ Adam Thielen ┆ 2025   ┆ 1    ┆ MIN  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 2.0         │
│ Keenan Allen ┆ 2025   ┆ 1    ┆ LAC  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 19.8        │
│ DeAndre      ┆ 2025   ┆ 1    ┆ BAL  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 11.5        │
│ Hopkins      ┆        ┆      ┆      ┆   ┆             ┆              ┆             ┆             │
│ Brandin      ┆ 2025   ┆ 1    ┆ NO   ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 5.6         │
│ Cooks        ┆        ┆      ┆      ┆   ┆             ┆              ┆             ┆             │
│ Davante      ┆ 2025   ┆ 1    ┆ LA   ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 9.1         │
│ Adams        ┆        ┆      ┆      ┆   ┆             ┆              ┆             ┆             │
│ Mike Evans   ┆ 2025   ┆ 1    ┆ TB   ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 10.1        │
│ Stefon Diggs ┆ 2025   ┆ 1    ┆ NE   ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 11.7        │
│ DeAndre      ┆ 2025   ┆ 1    ┆ CLE  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 0.0         │
│ Carter       ┆        ┆      ┆      ┆   ┆             ┆              ┆             ┆             │
│ Tyler        ┆ 2025   ┆ 1    ┆ TEN  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 0.0         │
│ Lockett      ┆        ┆      ┆      ┆   ┆             ┆              ┆             ┆             │
│ Sterling     ┆ 2025   ┆ 1    ┆ TB   ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 6.9         │
│ Shepard      ┆        ┆      ┆      ┆   ┆             ┆              ┆             ┆             │
│ Chris Moore  ┆ 2025   ┆ 1    ┆ WAS  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 4.4         │
│ Kalif        ┆ 2025   ┆ 1    ┆ DET  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 3.6         │
│ Raymond      ┆        ┆      ┆      ┆   ┆             ┆              ┆             ┆             │
│ Tyreek Hill  ┆ 2025   ┆ 1    ┆ MIA  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 8.0         │
│ Mack Hollins ┆ 2025   ┆ 1    ┆ NE   ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 1.3         │
│ Jamal Agnew  ┆ 2025   ┆ 1    ┆ ATL  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 0.0         │
│ David Moore  ┆ 2025   ┆ 1    ┆ CAR  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 0.0         │
│ Noah Brown   ┆ 2025   ┆ 1    ┆ WAS  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 4.7         │
│ JuJu Smith-S ┆ 2025   ┆ 1    ┆ KC   ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 10.5        │
│ chuster      ┆        ┆      ┆      ┆   ┆             ┆              ┆             ┆             │
│ Zay Jones    ┆ 2025   ┆ 1    ┆ ARI  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 1.4         │
│ Cooper Kupp  ┆ 2025   ┆ 1    ┆ SEA  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 3.5         │
│ Josh         ┆ 2025   ┆ 1    ┆ NYJ  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 3.8         │
│ Reynolds     ┆        ┆      ┆      ┆   ┆             ┆              ┆             ┆             │
│ Courtland    ┆ 2025   ┆ 1    ┆ DEN  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 18.1        │
│ Sutton       ┆        ┆      ┆      ┆   ┆             ┆              ┆             ┆             │
│ Justin       ┆ 2025   ┆ 1    ┆ HOU  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 4.7         │
│ Watson       ┆        ┆      ┆      ┆   ┆             ┆              ┆             ┆             │
│ Ray-Ray      ┆ 2025   ┆ 1    ┆ ATL  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 8.1         │
│ McCloud      ┆        ┆      ┆      ┆   ┆             ┆              ┆             ┆             │
│ Trent        ┆ 2025   ┆ 1    ┆ DEN  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 1.3         │
│ Sherfield    ┆        ┆      ┆      ┆   ┆             ┆              ┆             ┆             │
│ …            ┆ …      ┆ …    ┆ …    ┆ … ┆ …           ┆ …            ┆ …           ┆ …           │
│ Courtland    ┆ 2025   ┆ 21   ┆ DEN  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 10.7        │
│ Sutton       ┆        ┆      ┆      ┆   ┆             ┆              ┆             ┆             │
│ Lil'Jordan   ┆ 2025   ┆ 21   ┆ DEN  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 1.5         │
│ Humphrey     ┆        ┆      ┆      ┆   ┆             ┆              ┆             ┆             │
│ Elijah Moore ┆ 2025   ┆ 21   ┆ DEN  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 1.4         │
│ Dareke Young ┆ 2025   ┆ 21   ┆ SEA  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 0.0         │
│ Rashid       ┆ 2025   ┆ 21   ┆ SEA  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 6.1         │
│ Shaheed      ┆        ┆      ┆      ┆   ┆             ┆              ┆             ┆             │
│ Xavier Smith ┆ 2025   ┆ 21   ┆ LA   ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 0.0         │
│ Jaxon        ┆ 2025   ┆ 21   ┆ SEA  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 31.3        │
│ Smith-Njigba ┆        ┆      ┆      ┆   ┆             ┆              ┆             ┆             │
│ Kayshon      ┆ 2025   ┆ 21   ┆ NE   ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 1.6         │
│ Boutte       ┆        ┆      ┆      ┆   ┆             ┆              ┆             ┆             │
│ DeMario      ┆ 2025   ┆ 21   ┆ NE   ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 0.0         │
│ Douglas      ┆        ┆      ┆      ┆   ┆             ┆              ┆             ┆             │
│ Jake Bobo    ┆ 2025   ┆ 21   ┆ SEA  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 8.7         │
│ Marvin Mims  ┆ 2025   ┆ 21   ┆ DEN  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 10.2        │
│ Jr.          ┆        ┆      ┆      ┆   ┆             ┆              ┆             ┆             │
│ Puka Nacua   ┆ 2025   ┆ 21   ┆ LA   ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 31.9        │
│ Jordan       ┆ 2025   ┆ 21   ┆ LA   ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 0.0         │
│ Whittington  ┆        ┆      ┆      ┆   ┆             ┆              ┆             ┆             │
│ Pat Bryant   ┆ 2025   ┆ 21   ┆ DEN  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 1.3         │
│ Konata       ┆ 2025   ┆ 21   ┆ LA   ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 0.0         │
│ Mumpfield    ┆        ┆      ┆      ┆   ┆             ┆              ┆             ┆             │
│ Stefon Diggs ┆ 2025   ┆ 22   ┆ NE   ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 6.7         │
│ Mack Hollins ┆ 2025   ┆ 22   ┆ NE   ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 17.8        │
│ Cooper Kupp  ┆ 2025   ┆ 22   ┆ SEA  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 12.1        │
│ Dareke Young ┆ 2025   ┆ 22   ┆ SEA  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 0.0         │
│ Rashid       ┆ 2025   ┆ 22   ┆ SEA  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 4.2         │
│ Shaheed      ┆        ┆      ┆      ┆   ┆             ┆              ┆             ┆             │
│ Jaxon        ┆ 2025   ┆ 22   ┆ SEA  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 6.7         │
│ Smith-Njigba ┆        ┆      ┆      ┆   ┆             ┆              ┆             ┆             │
│ Kayshon      ┆ 2025   ┆ 22   ┆ NE   ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 3.1         │
│ Boutte       ┆        ┆      ┆      ┆   ┆             ┆              ┆             ┆             │
│ DeMario      ┆ 2025   ┆ 22   ┆ NE   ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 9.5         │
│ Douglas      ┆        ┆      ┆      ┆   ┆             ┆              ┆             ┆             │
│ Jake Bobo    ┆ 2025   ┆ 22   ┆ SEA  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 0.0         │
│ Kyle         ┆ 2025   ┆ 22   ┆ NE   ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 1.7         │
│ Williams     ┆        ┆      ┆      ┆   ┆             ┆              ┆             ┆             │
└──────────────┴────────┴──────┴──────┴───┴─────────────┴──────────────┴─────────────┴─────────────┘

In [25]:
lamb = receiving_stats.filter((pl.col('player_display_name') == 'CeeDee Lamb'))
lamb

shape: (13, 17)
┌──────────────┬────────┬──────┬──────┬───┬─────────────┬──────────────┬─────────────┬─────────────┐
│ player_displ ┆ season ┆ week ┆ team ┆ … ┆ rushing_tds ┆ rushing_fumb ┆ rushing_2pt ┆ fantasy_poi │
│ ay_name      ┆ ---    ┆ ---  ┆ ---  ┆   ┆ ---         ┆ les_lost     ┆ _conversion ┆ nts_ppr     │
│ ---          ┆ i32    ┆ i32  ┆ str  ┆   ┆ i32         ┆ ---          ┆ s           ┆ ---         │
│ str          ┆        ┆      ┆      ┆   ┆             ┆ i32          ┆ ---         ┆ f64         │
│              ┆        ┆      ┆      ┆   ┆             ┆              ┆ i32         ┆             │
╞══════════════╪════════╪══════╪══════╪═══╪═════════════╪══════════════╪═════════════╪═════════════╡
│ CeeDee Lamb  ┆ 2025   ┆ 1    ┆ DAL  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 18.0        │
│ CeeDee Lamb  ┆ 2025   ┆ 2    ┆ DAL  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 20.2        │
│ CeeDee Lamb  ┆ 2025   ┆ 7    ┆ DAL  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 22.0        │
│ CeeDee Lamb  ┆ 2025   ┆ 8    ┆ DAL  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 14.6        │
│ CeeDee Lamb  ┆ 2025   ┆ 9    ┆ DAL  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 15.5        │
│ CeeDee Lamb  ┆ 2025   ┆ 11   ┆ DAL  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 17.6        │
│ CeeDee Lamb  ┆ 2025   ┆ 12   ┆ DAL  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 11.5        │
│ CeeDee Lamb  ┆ 2025   ┆ 13   ┆ DAL  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 24.2        │
│ CeeDee Lamb  ┆ 2025   ┆ 14   ┆ DAL  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 18.1        │
│ CeeDee Lamb  ┆ 2025   ┆ 15   ┆ DAL  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 17.1        │
│ CeeDee Lamb  ┆ 2025   ┆ 16   ┆ DAL  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 11.1        │
│ CeeDee Lamb  ┆ 2025   ┆ 17   ┆ DAL  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 9.6         │
│ CeeDee Lamb  ┆ 2025   ┆ 18   ┆ DAL  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 1.4         │
└──────────────┴────────┴──────┴──────┴───┴─────────────┴──────────────┴─────────────┴─────────────┘

In [26]:
lamb.sort("targets", descending=True)

shape: (13, 17)
┌──────────────┬────────┬──────┬──────┬───┬─────────────┬──────────────┬─────────────┬─────────────┐
│ player_displ ┆ season ┆ week ┆ team ┆ … ┆ rushing_tds ┆ rushing_fumb ┆ rushing_2pt ┆ fantasy_poi │
│ ay_name      ┆ ---    ┆ ---  ┆ ---  ┆   ┆ ---         ┆ les_lost     ┆ _conversion ┆ nts_ppr     │
│ ---          ┆ i32    ┆ i32  ┆ str  ┆   ┆ i32         ┆ ---          ┆ s           ┆ ---         │
│ str          ┆        ┆      ┆      ┆   ┆             ┆ i32          ┆ ---         ┆ f64         │
│              ┆        ┆      ┆      ┆   ┆             ┆              ┆ i32         ┆             │
╞══════════════╪════════╪══════╪══════╪═══╪═════════════╪══════════════╪═════════════╪═════════════╡
│ CeeDee Lamb  ┆ 2025   ┆ 1    ┆ DAL  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 18.0        │
│ CeeDee Lamb  ┆ 2025   ┆ 9    ┆ DAL  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 15.5        │
│ CeeDee Lamb  ┆ 2025   ┆ 2    ┆ DAL  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 20.2        │
│ CeeDee Lamb  ┆ 2025   ┆ 12   ┆ DAL  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 11.5        │
│ CeeDee Lamb  ┆ 2025   ┆ 8    ┆ DAL  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 14.6        │
│ CeeDee Lamb  ┆ 2025   ┆ 15   ┆ DAL  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 17.1        │
│ CeeDee Lamb  ┆ 2025   ┆ 17   ┆ DAL  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 9.6         │
│ CeeDee Lamb  ┆ 2025   ┆ 13   ┆ DAL  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 24.2        │
│ CeeDee Lamb  ┆ 2025   ┆ 7    ┆ DAL  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 22.0        │
│ CeeDee Lamb  ┆ 2025   ┆ 14   ┆ DAL  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 18.1        │
│ CeeDee Lamb  ┆ 2025   ┆ 11   ┆ DAL  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 17.6        │
│ CeeDee Lamb  ┆ 2025   ┆ 16   ┆ DAL  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 11.1        │
│ CeeDee Lamb  ┆ 2025   ┆ 18   ┆ DAL  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 1.4         │
└──────────────┴────────┴──────┴──────┴───┴─────────────┴──────────────┴─────────────┴─────────────┘

In [27]:
lamb.sort("fantasy_points_ppr", descending=True)

shape: (13, 17)
┌──────────────┬────────┬──────┬──────┬───┬─────────────┬──────────────┬─────────────┬─────────────┐
│ player_displ ┆ season ┆ week ┆ team ┆ … ┆ rushing_tds ┆ rushing_fumb ┆ rushing_2pt ┆ fantasy_poi │
│ ay_name      ┆ ---    ┆ ---  ┆ ---  ┆   ┆ ---         ┆ les_lost     ┆ _conversion ┆ nts_ppr     │
│ ---          ┆ i32    ┆ i32  ┆ str  ┆   ┆ i32         ┆ ---          ┆ s           ┆ ---         │
│ str          ┆        ┆      ┆      ┆   ┆             ┆ i32          ┆ ---         ┆ f64         │
│              ┆        ┆      ┆      ┆   ┆             ┆              ┆ i32         ┆             │
╞══════════════╪════════╪══════╪══════╪═══╪═════════════╪══════════════╪═════════════╪═════════════╡
│ CeeDee Lamb  ┆ 2025   ┆ 13   ┆ DAL  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 24.2        │
│ CeeDee Lamb  ┆ 2025   ┆ 7    ┆ DAL  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 22.0        │
│ CeeDee Lamb  ┆ 2025   ┆ 2    ┆ DAL  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 20.2        │
│ CeeDee Lamb  ┆ 2025   ┆ 14   ┆ DAL  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 18.1        │
│ CeeDee Lamb  ┆ 2025   ┆ 1    ┆ DAL  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 18.0        │
│ CeeDee Lamb  ┆ 2025   ┆ 11   ┆ DAL  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 17.6        │
│ CeeDee Lamb  ┆ 2025   ┆ 15   ┆ DAL  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 17.1        │
│ CeeDee Lamb  ┆ 2025   ┆ 9    ┆ DAL  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 15.5        │
│ CeeDee Lamb  ┆ 2025   ┆ 8    ┆ DAL  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 14.6        │
│ CeeDee Lamb  ┆ 2025   ┆ 12   ┆ DAL  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 11.5        │
│ CeeDee Lamb  ┆ 2025   ┆ 16   ┆ DAL  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 11.1        │
│ CeeDee Lamb  ┆ 2025   ┆ 17   ┆ DAL  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 9.6         │
│ CeeDee Lamb  ┆ 2025   ┆ 18   ┆ DAL  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 1.4         │
└──────────────┴────────┴──────┴──────┴───┴─────────────┴──────────────┴─────────────┴─────────────┘

In [28]:
lamb_week_1 = lamb.filter((pl.col('week') == 1))
lamb_week_1

shape: (1, 17)
┌──────────────┬────────┬──────┬──────┬───┬─────────────┬──────────────┬─────────────┬─────────────┐
│ player_displ ┆ season ┆ week ┆ team ┆ … ┆ rushing_tds ┆ rushing_fumb ┆ rushing_2pt ┆ fantasy_poi │
│ ay_name      ┆ ---    ┆ ---  ┆ ---  ┆   ┆ ---         ┆ les_lost     ┆ _conversion ┆ nts_ppr     │
│ ---          ┆ i32    ┆ i32  ┆ str  ┆   ┆ i32         ┆ ---          ┆ s           ┆ ---         │
│ str          ┆        ┆      ┆      ┆   ┆             ┆ i32          ┆ ---         ┆ f64         │
│              ┆        ┆      ┆      ┆   ┆             ┆              ┆ i32         ┆             │
╞══════════════╪════════╪══════╪══════╪═══╪═════════════╪══════════════╪═════════════╪═════════════╡
│ CeeDee Lamb  ┆ 2025   ┆ 1    ┆ DAL  ┆ … ┆ 0           ┆ 0            ┆ 0           ┆ 18.0        │
└──────────────┴────────┴──────┴──────┴───┴─────────────┴──────────────┴─────────────┴─────────────┘

In [29]:
receiving_stats_ppr = receiving_stats.with_columns(
    (
        pl.col("receptions")
        + (pl.col("receiving_yards") * 0.1)
        + (pl.col("receiving_tds") * 6)
        + (pl.col('rushing_yards') * 0.1)
        + (pl.col('rushing_tds') * 6)
        - (pl.col("receiving_fumbles_lost") * 2)
        - (pl.col("rushing_fumbles_lost") * 2)
    ).alias("calculated_ppr")
)

receiving_stats_ppr

shape: (2_623, 18)
┌──────────────┬────────┬──────┬──────┬───┬──────────────┬─────────────┬─────────────┬─────────────┐
│ player_displ ┆ season ┆ week ┆ team ┆ … ┆ rushing_fumb ┆ rushing_2pt ┆ fantasy_poi ┆ calculated_ │
│ ay_name      ┆ ---    ┆ ---  ┆ ---  ┆   ┆ les_lost     ┆ _conversion ┆ nts_ppr     ┆ ppr         │
│ ---          ┆ i32    ┆ i32  ┆ str  ┆   ┆ ---          ┆ s           ┆ ---         ┆ ---         │
│ str          ┆        ┆      ┆      ┆   ┆ i32          ┆ ---         ┆ f64         ┆ f64         │
│              ┆        ┆      ┆      ┆   ┆              ┆ i32         ┆             ┆             │
╞══════════════╪════════╪══════╪══════╪═══╪══════════════╪═════════════╪═════════════╪═════════════╡
│ Adam Thielen ┆ 2025   ┆ 1    ┆ MIN  ┆ … ┆ 0            ┆ 0           ┆ 2.0         ┆ 0.0         │
│ Keenan Allen ┆ 2025   ┆ 1    ┆ LAC  ┆ … ┆ 0            ┆ 0           ┆ 19.8        ┆ 19.8        │
│ DeAndre      ┆ 2025   ┆ 1    ┆ BAL  ┆ … ┆ 0            ┆ 0           ┆ 11.5        ┆ 11.5        │
│ Hopkins      ┆        ┆      ┆      ┆   ┆              ┆             ┆             ┆             │
│ Brandin      ┆ 2025   ┆ 1    ┆ NO   ┆ … ┆ 0            ┆ 0           ┆ 5.6         ┆ 5.6         │
│ Cooks        ┆        ┆      ┆      ┆   ┆              ┆             ┆             ┆             │
│ Davante      ┆ 2025   ┆ 1    ┆ LA   ┆ … ┆ 0            ┆ 0           ┆ 9.1         ┆ 9.1         │
│ Adams        ┆        ┆      ┆      ┆   ┆              ┆             ┆             ┆             │
│ Mike Evans   ┆ 2025   ┆ 1    ┆ TB   ┆ … ┆ 0            ┆ 0           ┆ 10.1        ┆ 10.1        │
│ Stefon Diggs ┆ 2025   ┆ 1    ┆ NE   ┆ … ┆ 0            ┆ 0           ┆ 11.7        ┆ 11.7        │
│ DeAndre      ┆ 2025   ┆ 1    ┆ CLE  ┆ … ┆ 0            ┆ 0           ┆ 0.0         ┆ 0.0         │
│ Carter       ┆        ┆      ┆      ┆   ┆              ┆             ┆             ┆             │
│ Tyler        ┆ 2025   ┆ 1    ┆ TEN  ┆ … ┆ 0            ┆ 0           ┆ 0.0         ┆ 0.0         │
│ Lockett      ┆        ┆      ┆      ┆   ┆              ┆             ┆             ┆             │
│ Sterling     ┆ 2025   ┆ 1    ┆ TB   ┆ … ┆ 0            ┆ 0           ┆ 6.9         ┆ 6.9         │
│ Shepard      ┆        ┆      ┆      ┆   ┆              ┆             ┆             ┆             │
│ Chris Moore  ┆ 2025   ┆ 1    ┆ WAS  ┆ … ┆ 0            ┆ 0           ┆ 4.4         ┆ 4.4         │
│ Kalif        ┆ 2025   ┆ 1    ┆ DET  ┆ … ┆ 0            ┆ 0           ┆ 3.6         ┆ 3.6         │
│ Raymond      ┆        ┆      ┆      ┆   ┆              ┆             ┆             ┆             │
│ Tyreek Hill  ┆ 2025   ┆ 1    ┆ MIA  ┆ … ┆ 0            ┆ 0           ┆ 8.0         ┆ 8.0         │
│ Mack Hollins ┆ 2025   ┆ 1    ┆ NE   ┆ … ┆ 0            ┆ 0           ┆ 1.3         ┆ 1.3         │
│ Jamal Agnew  ┆ 2025   ┆ 1    ┆ ATL  ┆ … ┆ 0            ┆ 0           ┆ 0.0         ┆ 0.0         │
│ David Moore  ┆ 2025   ┆ 1    ┆ CAR  ┆ … ┆ 0            ┆ 0           ┆ 0.0         ┆ 0.0         │
│ Noah Brown   ┆ 2025   ┆ 1    ┆ WAS  ┆ … ┆ 0            ┆ 0           ┆ 4.7         ┆ 4.7         │
│ JuJu Smith-S ┆ 2025   ┆ 1    ┆ KC   ┆ … ┆ 0            ┆ 0           ┆ 10.5        ┆ 10.5        │
│ chuster      ┆        ┆      ┆      ┆   ┆              ┆             ┆             ┆             │
│ Zay Jones    ┆ 2025   ┆ 1    ┆ ARI  ┆ … ┆ 0            ┆ 0           ┆ 1.4         ┆ 1.4         │
│ Cooper Kupp  ┆ 2025   ┆ 1    ┆ SEA  ┆ … ┆ 0            ┆ 0           ┆ 3.5         ┆ 3.5         │
│ Josh         ┆ 2025   ┆ 1    ┆ NYJ  ┆ … ┆ 0            ┆ 0           ┆ 3.8         ┆ 3.8         │
│ Reynolds     ┆        ┆      ┆      ┆   ┆              ┆             ┆             ┆             │
│ Courtland    ┆ 2025   ┆ 1    ┆ DEN  ┆ … ┆ 0            ┆ 0           ┆ 18.1        ┆ 18.1        │
│ Sutton       ┆        ┆      ┆      ┆   ┆              ┆             ┆             ┆             │
│ Justin       ┆ 2025   ┆ 1    ┆ HOU  ┆ … ┆ 0            ┆ 0           ┆ 4.7         ┆ 4.7         │
│ Watson       ┆        ┆      ┆      ┆   ┆              ┆             ┆             ┆             │
│ Ray-Ray      ┆ 2025   ┆ 1    ┆ ATL  ┆ … ┆ 0            ┆ 0           ┆ 8.1         ┆ 8.1         │
│ McCloud      ┆        ┆      ┆      ┆   ┆              ┆             ┆             ┆             │
│ Trent        ┆ 2025   ┆ 1    ┆ DEN  ┆ … ┆ 0            ┆ 0           ┆ 1.3         ┆ 1.3         │
│ Sherfield    ┆        ┆      ┆      ┆   ┆              ┆             ┆             ┆             │
│ …            ┆ …      ┆ …    ┆ …    ┆ … ┆ …            ┆ …           ┆ …           ┆ …           │
│ Courtland    ┆ 2025   ┆ 21   ┆ DEN  ┆ … ┆ 0            ┆ 0           ┆ 10.7        ┆ 10.7        │
│ Sutton       ┆        ┆      ┆      ┆   ┆              ┆             ┆             ┆             │
│ Lil'Jordan   ┆ 2025   ┆ 21   ┆ DEN  ┆ … ┆ 0            ┆ 0           ┆ 1.5         ┆ 1.5         │
│ Humphrey     ┆        ┆      ┆      ┆   ┆              ┆             ┆             ┆             │
│ Elijah Moore ┆ 2025   ┆ 21   ┆ DEN  ┆ … ┆ 0            ┆ 0           ┆ 1.4         ┆ 1.4         │
│ Dareke Young ┆ 2025   ┆ 21   ┆ SEA  ┆ … ┆ 0            ┆ 0           ┆ 0.0         ┆ 0.0         │
│ Rashid       ┆ 2025   ┆ 21   ┆ SEA  ┆ … ┆ 0            ┆ 0           ┆ 6.1         ┆ 6.1         │
│ Shaheed      ┆        ┆      ┆      ┆   ┆              ┆             ┆             ┆             │
│ Xavier Smith ┆ 2025   ┆ 21   ┆ LA   ┆ … ┆ 0            ┆ 0           ┆ 0.0         ┆ 0.0         │
│ Jaxon        ┆ 2025   ┆ 21   ┆ SEA  ┆ … ┆ 0            ┆ 0           ┆ 31.3        ┆ 31.3        │
│ Smith-Njigba ┆        ┆      ┆      ┆   ┆              ┆             ┆             ┆             │
│ Kayshon      ┆ 2025   ┆ 21   ┆ NE   ┆ … ┆ 0            ┆ 0           ┆ 1.6         ┆ 1.6         │
│ Boutte       ┆        ┆      ┆      ┆   ┆              ┆             ┆             ┆             │
│ DeMario      ┆ 2025   ┆ 21   ┆ NE   ┆ … ┆ 0            ┆ 0           ┆ 0.0         ┆ 0.0         │
│ Douglas      ┆        ┆      ┆      ┆   ┆              ┆             ┆             ┆             │
│ Jake Bobo    ┆ 2025   ┆ 21   ┆ SEA  ┆ … ┆ 0            ┆ 0           ┆ 8.7         ┆ 8.7         │
│ Marvin Mims  ┆ 2025   ┆ 21   ┆ DEN  ┆ … ┆ 0            ┆ 0           ┆ 10.2        ┆ 10.2        │
│ Jr.          ┆        ┆      ┆      ┆   ┆              ┆             ┆             ┆             │
│ Puka Nacua   ┆ 2025   ┆ 21   ┆ LA   ┆ … ┆ 0            ┆ 0           ┆ 31.9        ┆ 31.9        │
│ Jordan       ┆ 2025   ┆ 21   ┆ LA   ┆ … ┆ 0            ┆ 0           ┆ 0.0         ┆ 0.0         │
│ Whittington  ┆        ┆      ┆      ┆   ┆              ┆             ┆             ┆             │
│ Pat Bryant   ┆ 2025   ┆ 21   ┆ DEN  ┆ … ┆ 0            ┆ 0           ┆ 1.3         ┆ 1.3         │
│ Konata       ┆ 2025   ┆ 21   ┆ LA   ┆ … ┆ 0            ┆ 0           ┆ 0.0         ┆ 0.0         │
│ Mumpfield    ┆        ┆      ┆      ┆   ┆              ┆             ┆             ┆             │
│ Stefon Diggs ┆ 2025   ┆ 22   ┆ NE   ┆ … ┆ 0            ┆ 0           ┆ 6.7         ┆ 6.7         │
│ Mack Hollins ┆ 2025   ┆ 22   ┆ NE   ┆ … ┆ 0            ┆ 0           ┆ 17.8        ┆ 17.8        │
│ Cooper Kupp  ┆ 2025   ┆ 22   ┆ SEA  ┆ … ┆ 0            ┆ 0           ┆ 12.1        ┆ 12.1        │
│ Dareke Young ┆ 2025   ┆ 22   ┆ SEA  ┆ … ┆ 0            ┆ 0           ┆ 0.0         ┆ 0.0         │
│ Rashid       ┆ 2025   ┆ 22   ┆ SEA  ┆ … ┆ 0            ┆ 0           ┆ 4.2         ┆ 4.2         │
│ Shaheed      ┆        ┆      ┆      ┆   ┆              ┆             ┆             ┆             │
│ Jaxon        ┆ 2025   ┆ 22   ┆ SEA  ┆ … ┆ 0            ┆ 0           ┆ 6.7         ┆ 6.7         │
│ Smith-Njigba ┆        ┆      ┆      ┆   ┆              ┆             ┆             ┆             │
│ Kayshon      ┆ 2025   ┆ 22   ┆ NE   ┆ … ┆ 0            ┆ 0           ┆ 3.1         ┆ 3.1         │
│ Boutte       ┆        ┆      ┆      ┆   ┆              ┆             ┆             ┆             │
│ DeMario      ┆ 2025   ┆ 22   ┆ NE   ┆ … ┆ 0            ┆ 0           ┆ 9.5         ┆ 9.5         │
│ Douglas      ┆        ┆      ┆      ┆   ┆              ┆             ┆             ┆             │
│ Jake Bobo    ┆ 2025   ┆ 22   ┆ SEA  ┆ … ┆ 0            ┆ 0           ┆ 0.0         ┆ 0.0         │
│ Kyle         ┆ 2025   ┆ 22   ┆ NE   ┆ … ┆ 0            ┆ 0           ┆ 1.7         ┆ 1.7         │
│ Williams     ┆        ┆      ┆      ┆   ┆              ┆             ┆             ┆             │
└──────────────┴────────┴──────┴──────┴───┴──────────────┴─────────────┴─────────────┴─────────────┘

In [30]:
lamb_ppr = receiving_stats_ppr.filter((pl.col('player_display_name') == 'CeeDee Lamb'))
lamb_ppr.select([
    'player_display_name',
    'week',
    'receptions',
    'receiving_yards',
    'receiving_tds',
    'receiving_fumbles_lost',
    'fantasy_points_ppr',
    'calculated_ppr'
])
# lamb_ppr.sort('week')
# lamb_ppr

shape: (13, 8)
┌─────────────┬──────┬────────────┬────────────┬────────────┬────────────┬────────────┬────────────┐
│ player_disp ┆ week ┆ receptions ┆ receiving_ ┆ receiving_ ┆ receiving_ ┆ fantasy_po ┆ calculated │
│ lay_name    ┆ ---  ┆ ---        ┆ yards      ┆ tds        ┆ fumbles_lo ┆ ints_ppr   ┆ _ppr       │
│ ---         ┆ i32  ┆ i32        ┆ ---        ┆ ---        ┆ st         ┆ ---        ┆ ---        │
│ str         ┆      ┆            ┆ i32        ┆ i32        ┆ ---        ┆ f64        ┆ f64        │
│             ┆      ┆            ┆            ┆            ┆ i32        ┆            ┆            │
╞═════════════╪══════╪════════════╪════════════╪════════════╪════════════╪════════════╪════════════╡
│ CeeDee Lamb ┆ 1    ┆ 7          ┆ 110        ┆ 0          ┆ 0          ┆ 18.0       ┆ 18.0       │
│ CeeDee Lamb ┆ 2    ┆ 9          ┆ 112        ┆ 0          ┆ 0          ┆ 20.2       ┆ 20.2       │
│ CeeDee Lamb ┆ 7    ┆ 5          ┆ 110        ┆ 1          ┆ 0          ┆ 22.0       ┆ 22.0       │
│ CeeDee Lamb ┆ 8    ┆ 7          ┆ 74         ┆ 0          ┆ 0          ┆ 14.6       ┆ 14.6       │
│ CeeDee Lamb ┆ 9    ┆ 7          ┆ 85         ┆ 0          ┆ 0          ┆ 15.5       ┆ 15.5       │
│ CeeDee Lamb ┆ 11   ┆ 5          ┆ 66         ┆ 1          ┆ 0          ┆ 17.6       ┆ 17.6       │
│ CeeDee Lamb ┆ 12   ┆ 4          ┆ 75         ┆ 0          ┆ 0          ┆ 11.5       ┆ 11.5       │
│ CeeDee Lamb ┆ 13   ┆ 7          ┆ 112        ┆ 1          ┆ 0          ┆ 24.2       ┆ 24.2       │
│ CeeDee Lamb ┆ 14   ┆ 6          ┆ 121        ┆ 0          ┆ 0          ┆ 18.1       ┆ 18.1       │
│ CeeDee Lamb ┆ 15   ┆ 6          ┆ 111        ┆ 0          ┆ 0          ┆ 17.1       ┆ 17.1       │
│ CeeDee Lamb ┆ 16   ┆ 6          ┆ 51         ┆ 0          ┆ 0          ┆ 11.1       ┆ 11.1       │
│ CeeDee Lamb ┆ 17   ┆ 5          ┆ 46         ┆ 0          ┆ 0          ┆ 9.6        ┆ 9.6        │
│ CeeDee Lamb ┆ 18   ┆ 1          ┆ 4          ┆ 0          ┆ 0          ┆ 1.4        ┆ 1.4        │
└─────────────┴──────┴────────────┴────────────┴────────────┴────────────┴────────────┴────────────┘

In [31]:
jsn_ppr = receiving_stats_ppr.filter(pl.col('player_display_name') == 'Jaxon Smith-Njigba')
jsn_summary = jsn_ppr.select([
    'player_display_name',
    'week',
    'receptions',
    'receiving_yards',
    'receiving_tds',
    'receiving_fumbles_lost',
    'rushing_yards',
    'rushing_tds',
    'rushing_fumbles_lost',
    'fantasy_points_ppr',
    'calculated_ppr'
])
pl.Config.set_tbl_rows(50)
jsn_summary

shape: (20, 11)
┌────────────┬──────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ player_dis ┆ week ┆ receptions ┆ receiving_ ┆ … ┆ rushing_td ┆ rushing_f ┆ fantasy_p ┆ calculate │
│ play_name  ┆ ---  ┆ ---        ┆ yards      ┆   ┆ s          ┆ umbles_lo ┆ oints_ppr ┆ d_ppr     │
│ ---        ┆ i32  ┆ i32        ┆ ---        ┆   ┆ ---        ┆ st        ┆ ---       ┆ ---       │
│ str        ┆      ┆            ┆ i32        ┆   ┆ i32        ┆ ---       ┆ f64       ┆ f64       │
│            ┆      ┆            ┆            ┆   ┆            ┆ i32       ┆           ┆           │
╞════════════╪══════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ Jaxon Smit ┆ 1    ┆ 9          ┆ 124        ┆ … ┆ 0          ┆ 0         ┆ 19.4      ┆ 19.4      │
│ h-Njigba   ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Jaxon Smit ┆ 2    ┆ 8          ┆ 103        ┆ … ┆ 0          ┆ 0         ┆ 18.3      ┆ 18.3      │
│ h-Njigba   ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Jaxon Smit ┆ 3    ┆ 5          ┆ 96         ┆ … ┆ 0          ┆ 0         ┆ 20.6      ┆ 20.6      │
│ h-Njigba   ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Jaxon Smit ┆ 4    ┆ 4          ┆ 79         ┆ … ┆ 0          ┆ 0         ┆ 13.0      ┆ 13.0      │
│ h-Njigba   ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Jaxon Smit ┆ 5    ┆ 8          ┆ 132        ┆ … ┆ 0          ┆ 0         ┆ 27.2      ┆ 27.2      │
│ h-Njigba   ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Jaxon Smit ┆ 6    ┆ 8          ┆ 162        ┆ … ┆ 0          ┆ 0         ┆ 30.2      ┆ 30.2      │
│ h-Njigba   ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Jaxon Smit ┆ 7    ┆ 8          ┆ 123        ┆ … ┆ 0          ┆ 0         ┆ 26.3      ┆ 26.3      │
│ h-Njigba   ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Jaxon Smit ┆ 9    ┆ 8          ┆ 129        ┆ … ┆ 0          ┆ 0         ┆ 22.0      ┆ 22.0      │
│ h-Njigba   ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Jaxon Smit ┆ 10   ┆ 5          ┆ 93         ┆ … ┆ 0          ┆ 0         ┆ 20.3      ┆ 20.3      │
│ h-Njigba   ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Jaxon Smit ┆ 11   ┆ 9          ┆ 105        ┆ … ┆ 0          ┆ 0         ┆ 20.6      ┆ 20.6      │
│ h-Njigba   ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Jaxon Smit ┆ 12   ┆ 8          ┆ 167        ┆ … ┆ 0          ┆ 0         ┆ 37.1      ┆ 37.1      │
│ h-Njigba   ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Jaxon Smit ┆ 13   ┆ 2          ┆ 23         ┆ … ┆ 0          ┆ 0         ┆ 4.3       ┆ 4.3       │
│ h-Njigba   ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Jaxon Smit ┆ 14   ┆ 7          ┆ 92         ┆ … ┆ 0          ┆ 0         ┆ 28.1      ┆ 28.1      │
│ h-Njigba   ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Jaxon Smit ┆ 15   ┆ 7          ┆ 113        ┆ … ┆ 0          ┆ 0         ┆ 18.3      ┆ 18.3      │
│ h-Njigba   ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Jaxon Smit ┆ 16   ┆ 8          ┆ 96         ┆ … ┆ 0          ┆ 0         ┆ 23.6      ┆ 23.6      │
│ h-Njigba   ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Jaxon Smit ┆ 17   ┆ 9          ┆ 72         ┆ … ┆ 0          ┆ 0         ┆ 16.2      ┆ 16.2      │
│ h-Njigba   ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Jaxon Smit ┆ 18   ┆ 6          ┆ 84         ┆ … ┆ 0          ┆ 0         ┆ 14.4      ┆ 14.4      │
│ h-Njigba   ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Jaxon Smit ┆ 20   ┆ 3          ┆ 19         ┆ … ┆ 0          ┆ 0         ┆ 10.9      ┆ 10.9      │
│ h-Njigba   ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Jaxon Smit ┆ 21   ┆ 10         ┆ 153        ┆ … ┆ 0          ┆ 0         ┆ 31.3      ┆ 31.3      │
│ h-Njigba   ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Jaxon Smit ┆ 22   ┆ 4          ┆ 27         ┆ … ┆ 0          ┆ 0         ┆ 6.7       ┆ 6.7       │
│ h-Njigba   ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
└────────────┴──────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [32]:
puka = receiving_stats_ppr.filter(pl.col('player_display_name') == 'Puka Nacua')
puka_summary = puka.select([
    'player_display_name',
    'week',
    'receptions',
    'receiving_yards',
    'receiving_tds',
    'receiving_fumbles_lost',
    'rushing_yards',
    'rushing_tds',
    'rushing_fumbles_lost',
    'fantasy_points_ppr',
    'calculated_ppr'
])
pl.Config.set_tbl_rows(50)
puka_summary

shape: (19, 11)
┌────────────┬──────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ player_dis ┆ week ┆ receptions ┆ receiving_ ┆ … ┆ rushing_td ┆ rushing_f ┆ fantasy_p ┆ calculate │
│ play_name  ┆ ---  ┆ ---        ┆ yards      ┆   ┆ s          ┆ umbles_lo ┆ oints_ppr ┆ d_ppr     │
│ ---        ┆ i32  ┆ i32        ┆ ---        ┆   ┆ ---        ┆ st        ┆ ---       ┆ ---       │
│ str        ┆      ┆            ┆ i32        ┆   ┆ i32        ┆ ---       ┆ f64       ┆ f64       │
│            ┆      ┆            ┆            ┆   ┆            ┆ i32       ┆           ┆           │
╞════════════╪══════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ Puka Nacua ┆ 1    ┆ 10         ┆ 130        ┆ … ┆ 0          ┆ 0         ┆ 23.1      ┆ 23.1      │
│ Puka Nacua ┆ 2    ┆ 8          ┆ 91         ┆ … ┆ 1          ┆ 0         ┆ 27.6      ┆ 27.6      │
│ Puka Nacua ┆ 3    ┆ 11         ┆ 112        ┆ … ┆ 0          ┆ 0         ┆ 22.8      ┆ 22.8      │
│ Puka Nacua ┆ 4    ┆ 13         ┆ 170        ┆ … ┆ 0          ┆ 0         ┆ 36.0      ┆ 36.0      │
│ Puka Nacua ┆ 5    ┆ 10         ┆ 85         ┆ … ┆ 0          ┆ 0         ┆ 24.5      ┆ 24.5      │
│ Puka Nacua ┆ 6    ┆ 2          ┆ 28         ┆ … ┆ 0          ┆ 0         ┆ 4.8       ┆ 4.8       │
│ Puka Nacua ┆ 9    ┆ 7          ┆ 95         ┆ … ┆ 0          ┆ 0         ┆ 22.8      ┆ 22.8      │
│ Puka Nacua ┆ 10   ┆ 5          ┆ 64         ┆ … ┆ 0          ┆ 0         ┆ 17.4      ┆ 17.4      │
│ Puka Nacua ┆ 11   ┆ 7          ┆ 75         ┆ … ┆ 0          ┆ 0         ┆ 14.3      ┆ 14.3      │
│ Puka Nacua ┆ 12   ┆ 7          ┆ 97         ┆ … ┆ 0          ┆ 0         ┆ 16.7      ┆ 16.7      │
│ Puka Nacua ┆ 13   ┆ 6          ┆ 72         ┆ … ┆ 0          ┆ 0         ┆ 13.2      ┆ 13.2      │
│ Puka Nacua ┆ 14   ┆ 7          ┆ 167        ┆ … ┆ 0          ┆ 0         ┆ 35.7      ┆ 35.7      │
│ Puka Nacua ┆ 15   ┆ 9          ┆ 181        ┆ … ┆ 0          ┆ 0         ┆ 27.9      ┆ 27.9      │
│ Puka Nacua ┆ 16   ┆ 12         ┆ 225        ┆ … ┆ 0          ┆ 0         ┆ 46.5      ┆ 46.5      │
│ Puka Nacua ┆ 17   ┆ 5          ┆ 47         ┆ … ┆ 0          ┆ 0         ┆ 15.7      ┆ 15.7      │
│ Puka Nacua ┆ 18   ┆ 10         ┆ 76         ┆ … ┆ 0          ┆ 0         ┆ 26.0      ┆ 26.0      │
│ Puka Nacua ┆ 19   ┆ 10         ┆ 111        ┆ … ┆ 1          ┆ 0         ┆ 34.5      ┆ 34.5      │
│ Puka Nacua ┆ 20   ┆ 5          ┆ 56         ┆ … ┆ 0          ┆ 0         ┆ 11.2      ┆ 11.2      │
│ Puka Nacua ┆ 21   ┆ 9          ┆ 165        ┆ … ┆ 0          ┆ 0         ┆ 31.9      ┆ 31.9      │
└────────────┴──────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [33]:
receiving_stats_ppr = receiving_stats_ppr.with_columns(
    (pl.col("calculated_ppr") - pl.col("fantasy_points_ppr")).alias("ppr_difference")
)
receiving_stats_ppr.select([
    'player_display_name',
    'week',
    'fantasy_points_ppr',
    'calculated_ppr',
    'ppr_difference'
]).sort('ppr_difference')

shape: (2_623, 5)
┌─────────────────────┬──────┬────────────────────┬────────────────┬────────────────┐
│ player_display_name ┆ week ┆ fantasy_points_ppr ┆ calculated_ppr ┆ ppr_difference │
│ ---                 ┆ ---  ┆ ---                ┆ ---            ┆ ---            │
│ str                 ┆ i32  ┆ f64                ┆ f64            ┆ f64            │
╞═════════════════════╪══════╪════════════════════╪════════════════╪════════════════╡
│ Kalif Raymond       ┆ 4    ┆ 9.3                ┆ 3.3            ┆ -6.0           │
│ Malik Washington    ┆ 2    ┆ 9.5                ┆ 3.5            ┆ -6.0           │
│ Jaylin Lane         ┆ 3    ┆ 6.8                ┆ 0.8            ┆ -6.0           │
│ Tory Horton         ┆ 3    ┆ 18.2               ┆ 12.2           ┆ -6.0           │
│ Parker Washington   ┆ 4    ┆ 5.9                ┆ -0.1           ┆ -6.0           │
│ Charlie Jones       ┆ 9    ┆ 6.0                ┆ 0.0            ┆ -6.0           │
│ Chimere Dike        ┆ 9    ┆ 7.5                ┆ 1.5            ┆ -6.0           │
│ Isaiah Williams     ┆ 10   ┆ 7.4                ┆ 1.4            ┆ -6.0           │
│ Rashid Shaheed      ┆ 14   ┆ 16.7               ┆ 10.7           ┆ -6.0           │
│ Marvin Mims Jr.     ┆ 14   ┆ 7.7                ┆ 1.7            ┆ -6.0           │
│ Isaiah Williams     ┆ 14   ┆ 10.4               ┆ 4.4            ┆ -6.0           │
│ Jaylin Lane         ┆ 15   ┆ 6.0                ┆ 0.0            ┆ -6.0           │
│ Rashid Shaheed      ┆ 16   ┆ 9.1                ┆ 3.1            ┆ -6.0           │
│ Rashid Shaheed      ┆ 20   ┆ 8.7                ┆ 2.7            ┆ -6.0           │
│ Parker Washington   ┆ 10   ┆ 17.9               ┆ 11.9           ┆ -6.0           │
│ Chimere Dike        ┆ 12   ┆ 21.4               ┆ 15.4           ┆ -6.0           │
│ Gunner Olszewski    ┆ 12   ┆ 5.32               ┆ 0.0            ┆ -5.32          │
│ Jauan Jennings      ┆ 19   ┆ 10.66              ┆ 5.5            ┆ -5.16          │
│ DJ Moore            ┆ 9    ┆ 22.98              ┆ 18.9           ┆ -4.08          │
│ Courtland Sutton    ┆ 7    ┆ 16.7               ┆ 14.7           ┆ -2.0           │
│ Troy Franklin       ┆ 9    ┆ 8.3                ┆ 6.3            ┆ -2.0           │
│ Adam Thielen        ┆ 1    ┆ 2.0                ┆ 0.0            ┆ -2.0           │
│ Luke McCaffrey      ┆ 2    ┆ 4.9                ┆ 2.9            ┆ -2.0           │
│ Jalen Tolbert       ┆ 3    ┆ 7.4                ┆ 5.4            ┆ -2.0           │
│ Jauan Jennings      ┆ 4    ┆ 6.4                ┆ 4.4            ┆ -2.0           │
│ …                   ┆ …    ┆ …                  ┆ …              ┆ …              │
│ Jameson Williams    ┆ 1    ┆ 6.6                ┆ 6.6            ┆ 8.8818e-16     │
│ Olamide Zaccheaus   ┆ 2    ┆ 4.1                ┆ 4.1            ┆ 8.8818e-16     │
│ Olamide Zaccheaus   ┆ 3    ┆ 6.6                ┆ 6.6            ┆ 8.8818e-16     │
│ Ryan Flournoy       ┆ 4    ┆ 4.6                ┆ 4.6            ┆ 8.8818e-16     │
│ Malik Washington    ┆ 9    ┆ 7.1                ┆ 7.1            ┆ 8.8818e-16     │
│ Xavier Worthy       ┆ 9    ┆ 6.0                ┆ 6.0            ┆ 8.8818e-16     │
│ Tre Tucker          ┆ 10   ┆ 5.5                ┆ 5.5            ┆ 8.8818e-16     │
│ KaVontae Turpin     ┆ 12   ┆ 4.2                ┆ 4.2            ┆ 8.8818e-16     │
│ Luther Burden III   ┆ 13   ┆ 7.6                ┆ 7.6            ┆ 8.8818e-16     │
│ Quentin Johnston    ┆ 2    ┆ 15.9               ┆ 15.9           ┆ 1.7764e-15     │
│ Ricky Pearsall      ┆ 2    ┆ 9.2                ┆ 9.2            ┆ 1.7764e-15     │
│ Deebo Samuel Sr.    ┆ 9    ┆ 9.4                ┆ 9.4            ┆ 1.7764e-15     │
│ Xavier Worthy       ┆ 13   ┆ 11.4               ┆ 11.4           ┆ 1.7764e-15     │
│ Ja'Marr Chase       ┆ 14   ┆ 10.2               ┆ 10.2           ┆ 1.7764e-15     │
│ Jayden Reed         ┆ 19   ┆ 15.7               ┆ 15.7           ┆ 1.7764e-15     │
│ Puka Nacua          ┆ 20   ┆ 11.2               ┆ 11.2           ┆ 1.7764e-15     │
│ Puka Nacua          ┆ 3    ┆ 22.8               ┆ 22.8           ┆ 3.5527e-15     │
│ Chimere Dike        ┆ 8    ┆ 16.4               ┆ 16.4           ┆ 3.5527e-15     │
│ Rashee Rice         ┆ 13   ┆ 29.4               ┆ 29.4           ┆ 3.5527e-15     │
│ Adonai Mitchell     ┆ 15   ┆ 17.4               ┆ 17.4           ┆ 3.5527e-15     │
│ DJ Moore            ┆ 16   ┆ 21.9               ┆ 21.9           ┆ 3.5527e-15     │
│ Justin Jefferson    ┆ 18   ┆ 18.4               ┆ 18.4           ┆ 3.5527e-15     │
│ Parker Washington   ┆ 19   ┆ 23.9               ┆ 23.9           ┆ 3.5527e-15     │
│ Chris Olave         ┆ 4    ┆ 9.0                ┆ 11.0           ┆ 2.0            │
│ Cooper Kupp         ┆ 7    ┆ 2.2                ┆ 4.2            ┆ 2.0            │
└─────────────────────┴──────┴────────────────────┴────────────────┴────────────────┘

In [35]:
ppr_differences = receiving_stats_ppr.filter(
    pl.col("ppr_difference") != 0
)

ppr_differences.select([
    'player_display_name',
    'week',
    'receptions',
    'receiving_yards',
    'receiving_tds',
    'receiving_fumbles_lost',
    'receiving_2pt_conversions',
    'rushing_yards',
    'rushing_tds',
    'rushing_fumbles_lost',
    'rushing_2pt_conversions',
    'special_teams_tds',
    'fantasy_points_ppr',
    'calculated_ppr',
    'ppr_difference'
]).sort('ppr_difference')

shape: (125, 15)
┌────────────┬──────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ player_dis ┆ week ┆ receptions ┆ receiving_ ┆ … ┆ special_te ┆ fantasy_p ┆ calculate ┆ ppr_diffe │
│ play_name  ┆ ---  ┆ ---        ┆ yards      ┆   ┆ ams_tds    ┆ oints_ppr ┆ d_ppr     ┆ rence     │
│ ---        ┆ i32  ┆ i32        ┆ ---        ┆   ┆ ---        ┆ ---       ┆ ---       ┆ ---       │
│ str        ┆      ┆            ┆ i32        ┆   ┆ i32        ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪══════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ Kalif      ┆ 4    ┆ 2          ┆ 13         ┆ … ┆ 1          ┆ 9.3       ┆ 3.3       ┆ -6.0      │
│ Raymond    ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Malik      ┆ 2    ┆ 1          ┆ 2          ┆ … ┆ 1          ┆ 9.5       ┆ 3.5       ┆ -6.0      │
│ Washington ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Jaylin     ┆ 3    ┆ 1          ┆ -2         ┆ … ┆ 1          ┆ 6.8       ┆ 0.8       ┆ -6.0      │
│ Lane       ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Tory       ┆ 3    ┆ 3          ┆ 32         ┆ … ┆ 1          ┆ 18.2      ┆ 12.2      ┆ -6.0      │
│ Horton     ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Parker     ┆ 4    ┆ 0          ┆ 0          ┆ … ┆ 1          ┆ 5.9       ┆ -0.1      ┆ -6.0      │
│ Washington ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Charlie    ┆ 9    ┆ 0          ┆ 0          ┆ … ┆ 1          ┆ 6.0       ┆ 0.0       ┆ -6.0      │
│ Jones      ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Chimere    ┆ 9    ┆ 1          ┆ 5          ┆ … ┆ 1          ┆ 7.5       ┆ 1.5       ┆ -6.0      │
│ Dike       ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Isaiah     ┆ 10   ┆ 1          ┆ 4          ┆ … ┆ 1          ┆ 7.4       ┆ 1.4       ┆ -6.0      │
│ Williams   ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Rashid     ┆ 14   ┆ 4          ┆ 67         ┆ … ┆ 1          ┆ 16.7      ┆ 10.7      ┆ -6.0      │
│ Shaheed    ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Marvin     ┆ 14   ┆ 1          ┆ 5          ┆ … ┆ 1          ┆ 7.7       ┆ 1.7       ┆ -6.0      │
│ Mims Jr.   ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Isaiah     ┆ 14   ┆ 2          ┆ 24         ┆ … ┆ 1          ┆ 10.4      ┆ 4.4       ┆ -6.0      │
│ Williams   ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Jaylin     ┆ 15   ┆ 0          ┆ 0          ┆ … ┆ 1          ┆ 6.0       ┆ 0.0       ┆ -6.0      │
│ Lane       ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Rashid     ┆ 16   ┆ 0          ┆ 0          ┆ … ┆ 1          ┆ 9.1       ┆ 3.1       ┆ -6.0      │
│ Shaheed    ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Rashid     ┆ 20   ┆ 0          ┆ 0          ┆ … ┆ 1          ┆ 8.7       ┆ 2.7       ┆ -6.0      │
│ Shaheed    ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Parker     ┆ 10   ┆ 3          ┆ 33         ┆ … ┆ 1          ┆ 17.9      ┆ 11.9      ┆ -6.0      │
│ Washington ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Chimere    ┆ 12   ┆ 5          ┆ 44         ┆ … ┆ 1          ┆ 21.4      ┆ 15.4      ┆ -6.0      │
│ Dike       ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Gunner     ┆ 12   ┆ 0          ┆ 0          ┆ … ┆ 0          ┆ 5.32      ┆ 0.0       ┆ -5.32     │
│ Olszewski  ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Jauan      ┆ 19   ┆ 1          ┆ 45         ┆ … ┆ 0          ┆ 10.66     ┆ 5.5       ┆ -5.16     │
│ Jennings   ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ DJ Moore   ┆ 9    ┆ 4          ┆ 72         ┆ … ┆ 0          ┆ 22.98     ┆ 18.9      ┆ -4.08     │
│ Courtland  ┆ 7    ┆ 6          ┆ 87         ┆ … ┆ 0          ┆ 16.7      ┆ 14.7      ┆ -2.0      │
│ Sutton     ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Troy       ┆ 9    ┆ 4          ┆ 27         ┆ … ┆ 0          ┆ 8.3       ┆ 6.3       ┆ -2.0      │
│ Franklin   ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Adam       ┆ 1    ┆ 0          ┆ 0          ┆ … ┆ 0          ┆ 2.0       ┆ 0.0       ┆ -2.0      │
│ Thielen    ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Luke       ┆ 2    ┆ 1          ┆ 19         ┆ … ┆ 0          ┆ 4.9       ┆ 2.9       ┆ -2.0      │
│ McCaffrey  ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Jalen      ┆ 3    ┆ 3          ┆ 24         ┆ … ┆ 0          ┆ 7.4       ┆ 5.4       ┆ -2.0      │
│ Tolbert    ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Jauan      ┆ 4    ┆ 2          ┆ 24         ┆ … ┆ 0          ┆ 6.4       ┆ 4.4       ┆ -2.0      │
│ Jennings   ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ …          ┆ …    ┆ …          ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ Jameson    ┆ 1    ┆ 4          ┆ 23         ┆ … ┆ 0          ┆ 6.6       ┆ 6.6       ┆ 8.8818e-1 │
│ Williams   ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆ 6         │
│ Olamide    ┆ 2    ┆ 2          ┆ 12         ┆ … ┆ 0          ┆ 4.1       ┆ 4.1       ┆ 8.8818e-1 │
│ Zaccheaus  ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆ 6         │
│ Olamide    ┆ 3    ┆ 3          ┆ 24         ┆ … ┆ 0          ┆ 6.6       ┆ 6.6       ┆ 8.8818e-1 │
│ Zaccheaus  ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆ 6         │
│ Ryan       ┆ 4    ┆ 2          ┆ 14         ┆ … ┆ 0          ┆ 4.6       ┆ 4.6       ┆ 8.8818e-1 │
│ Flournoy   ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆ 6         │
│ Malik      ┆ 9    ┆ 3          ┆ 48         ┆ … ┆ 0          ┆ 7.1       ┆ 7.1       ┆ 8.8818e-1 │
│ Washington ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆ 6         │
│ Xavier     ┆ 9    ┆ 3          ┆ 23         ┆ … ┆ 0          ┆ 6.0       ┆ 6.0       ┆ 8.8818e-1 │
│ Worthy     ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆ 6         │
│ Tre Tucker ┆ 10   ┆ 2          ┆ 28         ┆ … ┆ 0          ┆ 5.5       ┆ 5.5       ┆ 8.8818e-1 │
│            ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆ 6         │
│ KaVontae   ┆ 12   ┆ 1          ┆ 48         ┆ … ┆ 0          ┆ 4.2       ┆ 4.2       ┆ 8.8818e-1 │
│ Turpin     ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆ 6         │
│ Luther     ┆ 13   ┆ 4          ┆ 33         ┆ … ┆ 0          ┆ 7.6       ┆ 7.6       ┆ 8.8818e-1 │
│ Burden III ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆ 6         │
│ Quentin    ┆ 2    ┆ 3          ┆ 71         ┆ … ┆ 0          ┆ 15.9      ┆ 15.9      ┆ 1.7764e-1 │
│ Johnston   ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆ 5         │
│ Ricky      ┆ 2    ┆ 4          ┆ 56         ┆ … ┆ 0          ┆ 9.2       ┆ 9.2       ┆ 1.7764e-1 │
│ Pearsall   ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆ 5         │
│ Deebo      ┆ 9    ┆ 5          ┆ 41         ┆ … ┆ 0          ┆ 9.4       ┆ 9.4       ┆ 1.7764e-1 │
│ Samuel Sr. ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆ 5         │
│ Xavier     ┆ 13   ┆ 4          ┆ 61         ┆ … ┆ 0          ┆ 11.4      ┆ 11.4      ┆ 1.7764e-1 │
│ Worthy     ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆ 5         │
│ Ja'Marr    ┆ 14   ┆ 5          ┆ 44         ┆ … ┆ 0          ┆ 10.2      ┆ 10.2      ┆ 1.7764e-1 │
│ Chase      ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆ 5         │
│ Jayden     ┆ 19   ┆ 4          ┆ 43         ┆ … ┆ 0          ┆ 15.7      ┆ 15.7      ┆ 1.7764e-1 │
│ Reed       ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆ 5         │
│ Puka Nacua ┆ 20   ┆ 5          ┆ 56         ┆ … ┆ 0          ┆ 11.2      ┆ 11.2      ┆ 1.7764e-1 │
│            ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆ 5         │
│ Puka Nacua ┆ 3    ┆ 11         ┆ 112        ┆ … ┆ 0          ┆ 22.8      ┆ 22.8      ┆ 3.5527e-1 │
│            ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆ 5         │
│ Chimere    ┆ 8    ┆ 7          ┆ 93         ┆ … ┆ 0          ┆ 16.4      ┆ 16.4      ┆ 3.5527e-1 │
│ Dike       ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆ 5         │
│ Rashee     ┆ 13   ┆ 8          ┆ 92         ┆ … ┆ 0          ┆ 29.4      ┆ 29.4      ┆ 3.5527e-1 │
│ Rice       ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆ 5         │
│ Adonai     ┆ 15   ┆ 6          ┆ 58         ┆ … ┆ 0          ┆ 17.4      ┆ 17.4      ┆ 3.5527e-1 │
│ Mitchell   ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆ 5         │
│ DJ Moore   ┆ 16   ┆ 5          ┆ 97         ┆ … ┆ 0          ┆ 21.9      ┆ 21.9      ┆ 3.5527e-1 │
│            ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆ 5         │
│ Justin     ┆ 18   ┆ 8          ┆ 101        ┆ … ┆ 0          ┆ 18.4      ┆ 18.4      ┆ 3.5527e-1 │
│ Jefferson  ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆ 5         │
│ Parker     ┆ 19   ┆ 7          ┆ 107        ┆ … ┆ 0          ┆ 23.9      ┆ 23.9      ┆ 3.5527e-1 │
│ Washington ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆ 5         │
│ Chris      ┆ 4    ┆ 3          ┆ 20         ┆ … ┆ 0          ┆ 9.0       ┆ 11.0      ┆ 2.0       │
│ Olave      ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ Cooper     ┆ 7    ┆ 1          ┆ 32         ┆ … ┆ 0          ┆ 2.2       ┆ 4.2       ┆ 2.0       │
│ Kupp       ┆      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
└────────────┴──────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [ ]:
player_averages = receiving_stats_ppr.group_by('player_display_name').agg([
    pl.col("calculated_ppr").mean().round(2).alias("avg_calculated_ppr"),
    pl.col("receptions").mean().round(2).alias("avg_receptions"),
    pl.col("receiving_yards").mean().round(2).alias("avg_receiving_yards"),
]).sort("avg_calculated_ppr", descending=True)

player_averages

shape: (240, 4)
┌──────────────────────┬────────────────────┬────────────────┬─────────────────────┐
│ player_display_name  ┆ avg_calculated_ppr ┆ avg_receptions ┆ avg_receiving_yards │
│ ---                  ┆ ---                ┆ ---            ┆ ---                 │
│ str                  ┆ f64                ┆ f64            ┆ f64                 │
╞══════════════════════╪════════════════════╪════════════════╪═════════════════════╡
│ Puka Nacua           ┆ 23.82              ┆ 8.05           ┆ 107.74              │
│ Jaxon Smith-Njigba   ┆ 20.44              ┆ 6.8            ┆ 99.6                │
│ Ja'Marr Chase        ┆ 19.6               ┆ 7.81           ┆ 88.25               │
│ Amon-Ra St. Brown    ┆ 19.06              ┆ 6.88           ┆ 82.41               │
│ Rashee Rice          ┆ 18.51              ┆ 6.62           ┆ 71.38               │
│ George Pickens       ┆ 17.05              ┆ 5.47           ┆ 84.06               │
│ Chris Olave          ┆ 16.88              ┆ 6.25           ┆ 72.69               │
│ Drake London         ┆ 16.66              ┆ 5.67           ┆ 76.58               │
│ CeeDee Lamb          ┆ 15.45              ┆ 5.77           ┆ 82.85               │
│ Davante Adams        ┆ 15.2               ┆ 4.18           ┆ 57.29               │
│ Nico Collins         ┆ 14.33              ┆ 4.62           ┆ 71.12               │
│ Zay Flowers          ┆ 14.31              ┆ 5.06           ┆ 71.24               │
│ Malik Nabers         ┆ 14.28              ┆ 4.5            ┆ 67.75               │
│ Garrett Wilson       ┆ 14.21              ┆ 5.14           ┆ 56.43               │
│ A.J. Brown           ┆ 14.11              ┆ 5.06           ┆ 64.25               │
│ Tee Higgins          ┆ 13.97              ┆ 3.93           ┆ 56.4                │
│ Wan'Dale Robinson    ┆ 13.62              ┆ 5.75           ┆ 63.38               │
│ Tyreek Hill          ┆ 13.38              ┆ 5.25           ┆ 66.25               │
│ Christian Watson     ┆ 13.18              ┆ 3.45           ┆ 58.82               │
│ Michael Wilson       ┆ 12.98              ┆ 4.59           ┆ 59.18               │
│ Jameson Williams     ┆ 12.94              ┆ 3.82           ┆ 65.71               │
│ Quentin Johnston     ┆ 12.59              ┆ 3.86           ┆ 53.93               │
│ Tetairoa McMillan    ┆ 12.58              ┆ 4.17           ┆ 60.83               │
│ Courtland Sutton     ┆ 12.51              ┆ 4.26           ┆ 57.21               │
│ Alec Pierce          ┆ 12.22              ┆ 3.13           ┆ 66.87               │
│ …                    ┆ …                  ┆ …              ┆ …                   │
│ Anthony Gould        ┆ 0.24               ┆ 0.18           ┆ 0.55                │
│ Devin Duvernay       ┆ 0.24               ┆ 0.11           ┆ 1.37                │
│ Ke'Shawn Williams    ┆ 0.23               ┆ 0.09           ┆ 0.45                │
│ Malik Cunningham     ┆ 0.1                ┆ 0.0            ┆ 0.0                 │
│ Laquon Treadwell     ┆ 0.0                ┆ 0.0            ┆ 0.0                 │
│ LaJohntay Wester     ┆ 0.0                ┆ 0.0            ┆ 0.0                 │
│ Charlie Jones        ┆ 0.0                ┆ 0.0            ┆ 0.0                 │
│ DeAndre Carter       ┆ 0.0                ┆ 0.0            ┆ 0.0                 │
│ River Cracraft       ┆ 0.0                ┆ 0.0            ┆ 0.0                 │
│ Dominic Lovett       ┆ 0.0                ┆ 0.0            ┆ 0.0                 │
│ Jason Brownlee       ┆ 0.0                ┆ 0.0            ┆ 0.0                 │
│ Jeshaun Jones        ┆ 0.0                ┆ 0.0            ┆ 0.0                 │
│ Dalen Cambre         ┆ 0.0                ┆ 0.0            ┆ 0.0                 │
│ Kaden Davis          ┆ 0.0                ┆ 0.0            ┆ 0.0                 │
│ Dalevon Campbell     ┆ 0.0                ┆ 0.0            ┆ 0.0                 │
│ Myles Price          ┆ 0.0                ┆ 0.0            ┆ 0.0                 │
│ DJ Turner            ┆ 0.0                ┆ 0.0            ┆ 0.0                 │
│ Malik Turner         ┆ 0.0                ┆ 0.0            ┆ 0.0                 │
│ Jamal Agnew          ┆ 0.0                ┆ 0.0            ┆ 0.0                 │
│ Simi Fehoko          ┆ 0.0                ┆ 0.0            ┆ 0.0                 │
│ Coleman Owen         ┆ 0.0                ┆ 0.0            ┆ 0.0                 │
│ Parris Campbell      ┆ 0.0                ┆ 0.0            ┆ 0.0                 │
│ Jalen Moreno-Cropper ┆ 0.0                ┆ 0.0            ┆ 0.0                 │
│ Chris Blair          ┆ 0.0                ┆ 0.0            ┆ 0.0                 │
│ Steven Sims          ┆ 0.0                ┆ 0.0            ┆ 0.0                 │
└──────────────────────┴────────────────────┴────────────────┴─────────────────────┘

In [43]:
lamb_rolling = (
    lamb_ppr
    .sort("week")
    .with_columns(
        pl.col("calculated_ppr")
        .rolling_mean(window_size=3)
        .round(2)
        .alias("rolling_3_ppr"),

        pl.col("receptions")
        .rolling_mean(window_size=3)
        .round(2)
        .alias("rolling_3_receptions"),

        pl.col("receiving_yards")
        .rolling_mean(window_size=3)
        .round(2)
        .alias("rolling_3_receiving_yards")
    )
)

lamb_rolling.select([
    'player_display_name',
    'week',
    'calculated_ppr',
    'rolling_3_ppr',
    'receptions',
    'rolling_3_receptions',
    'receiving_yards',
    'rolling_3_receiving_yards'
])

shape: (13, 8)
┌─────────────┬──────┬────────────┬────────────┬────────────┬────────────┬────────────┬────────────┐
│ player_disp ┆ week ┆ calculated ┆ rolling_3_ ┆ receptions ┆ rolling_3_ ┆ receiving_ ┆ rolling_3_ │
│ lay_name    ┆ ---  ┆ _ppr       ┆ ppr        ┆ ---        ┆ receptions ┆ yards      ┆ receiving_ │
│ ---         ┆ i32  ┆ ---        ┆ ---        ┆ i32        ┆ ---        ┆ ---        ┆ yards      │
│ str         ┆      ┆ f64        ┆ f64        ┆            ┆ f64        ┆ i32        ┆ ---        │
│             ┆      ┆            ┆            ┆            ┆            ┆            ┆ f64        │
╞═════════════╪══════╪════════════╪════════════╪════════════╪════════════╪════════════╪════════════╡
│ CeeDee Lamb ┆ 1    ┆ 18.0       ┆ null       ┆ 7          ┆ null       ┆ 110        ┆ null       │
│ CeeDee Lamb ┆ 2    ┆ 20.2       ┆ null       ┆ 9          ┆ null       ┆ 112        ┆ null       │
│ CeeDee Lamb ┆ 7    ┆ 22.0       ┆ 20.07      ┆ 5          ┆ 7.0        ┆ 110        ┆ 110.67     │
│ CeeDee Lamb ┆ 8    ┆ 14.6       ┆ 18.93      ┆ 7          ┆ 7.0        ┆ 74         ┆ 98.67      │
│ CeeDee Lamb ┆ 9    ┆ 15.5       ┆ 17.37      ┆ 7          ┆ 6.33       ┆ 85         ┆ 89.67      │
│ CeeDee Lamb ┆ 11   ┆ 17.6       ┆ 15.9       ┆ 5          ┆ 6.33       ┆ 66         ┆ 75.0       │
│ CeeDee Lamb ┆ 12   ┆ 11.5       ┆ 14.87      ┆ 4          ┆ 5.33       ┆ 75         ┆ 75.33      │
│ CeeDee Lamb ┆ 13   ┆ 24.2       ┆ 17.77      ┆ 7          ┆ 5.33       ┆ 112        ┆ 84.33      │
│ CeeDee Lamb ┆ 14   ┆ 18.1       ┆ 17.93      ┆ 6          ┆ 5.67       ┆ 121        ┆ 102.67     │
│ CeeDee Lamb ┆ 15   ┆ 17.1       ┆ 19.8       ┆ 6          ┆ 6.33       ┆ 111        ┆ 114.67     │
│ CeeDee Lamb ┆ 16   ┆ 11.1       ┆ 15.43      ┆ 6          ┆ 6.0        ┆ 51         ┆ 94.33      │
│ CeeDee Lamb ┆ 17   ┆ 9.6        ┆ 12.6       ┆ 5          ┆ 5.67       ┆ 46         ┆ 69.33      │
│ CeeDee Lamb ┆ 18   ┆ 1.4        ┆ 7.37       ┆ 1          ┆ 4.0        ┆ 4          ┆ 33.67      │
└─────────────┴──────┴────────────┴────────────┴────────────┴────────────┴────────────┴────────────┘

In [53]:
player_rolling_ppr = (
    receiving_stats_ppr
    .sort("player_display_name")
    .with_columns(
        pl.col("calculated_ppr")
        .rolling_mean(window_size=3)
        .round(2)
        .over("player_display_name")
        .alias("rolling_3_ppr"),

        pl.col("receptions")
        .rolling_mean(window_size=3)
        .round(2)
        .over("player_display_name")
        .alias("rolling_3_receptions"),

        pl.col("receiving_yards")
        .rolling_mean(window_size=3)
        .round(2)
        .over("player_display_name")
        .alias("rolling_3_receiving_yards")
    )
)

player_rolling_ppr.filter(pl.col('week') == 15).select([
    'player_display_name',
    'week',
    'calculated_ppr',
    'rolling_3_ppr',
    'receptions',
    'rolling_3_receptions',
    'receiving_yards',
    'rolling_3_receiving_yards'
]).sort('calculated_ppr', descending=True)

shape: (142, 8)
┌─────────────┬──────┬────────────┬────────────┬────────────┬────────────┬────────────┬────────────┐
│ player_disp ┆ week ┆ calculated ┆ rolling_3_ ┆ receptions ┆ rolling_3_ ┆ receiving_ ┆ rolling_3_ │
│ lay_name    ┆ ---  ┆ _ppr       ┆ ppr        ┆ ---        ┆ receptions ┆ yards      ┆ receiving_ │
│ ---         ┆ i32  ┆ ---        ┆ ---        ┆ i32        ┆ ---        ┆ ---        ┆ yards      │
│ str         ┆      ┆ f64        ┆ f64        ┆            ┆ f64        ┆ i32        ┆ ---        │
│             ┆      ┆            ┆            ┆            ┆            ┆            ┆ f64        │
╞═════════════╪══════╪════════════╪════════════╪════════════╪════════════╪════════════╪════════════╡
│ Amon-Ra St. ┆ 15   ┆ 41.4       ┆ 18.87      ┆ 13         ┆ 6.33       ┆ 164        ┆ 85.33      │
│ Brown       ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
│ Puka Nacua  ┆ 15   ┆ 27.9       ┆ 25.6       ┆ 9          ┆ 7.33       ┆ 181        ┆ 140.0      │
│ Jameson     ┆ 15   ┆ 26.4       ┆ 23.53      ┆ 7          ┆ 7.0        ┆ 134        ┆ 124.67     │
│ Williams    ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
│ Courtland   ┆ 15   ┆ 24.3       ┆ 17.9       ┆ 7          ┆ 6.0        ┆ 113        ┆ 79.0       │
│ Sutton      ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
│ Nico        ┆ 15   ┆ 23.5       ┆ 20.37      ┆ 3          ┆ 4.0        ┆ 85         ┆ 101.33     │
│ Collins     ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
│ Ja'Marr     ┆ 15   ┆ 23.2       ┆ 17.13      ┆ 10         ┆ 7.33       ┆ 132        ┆ 95.33      │
│ Chase       ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
│ DJ Moore    ┆ 15   ┆ 22.9       ┆ 9.4        ┆ 4          ┆ 2.33       ┆ 69         ┆ 27.33      │
│ Troy        ┆ 15   ┆ 20.8       ┆ 9.67       ┆ 6          ┆ 3.67       ┆ 85         ┆ 39.0       │
│ Franklin    ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
│ Chris Olave ┆ 15   ┆ 20.5       ┆ 13.73      ┆ 6          ┆ 4.33       ┆ 85         ┆ 54.0       │
│ Jalen       ┆ 15   ┆ 19.5       ┆ 8.5        ┆ 3          ┆ 2.0        ┆ 47         ┆ 25.67      │
│ Nailor      ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
│ Mike Evans  ┆ 15   ┆ 19.2       ┆ 10.83      ┆ 6          ┆ 3.33       ┆ 132        ┆ 55.0       │
│ Jauan       ┆ 15   ┆ 18.7       ┆ 15.9       ┆ 3          ┆ 4.0        ┆ 37         ┆ 39.0       │
│ Jennings    ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
│ Jaxon Smith ┆ 15   ┆ 18.3       ┆ 16.9       ┆ 7          ┆ 5.33       ┆ 113        ┆ 76.0       │
│ -Njigba     ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
│ Adonai      ┆ 15   ┆ 17.4       ┆ 15.0       ┆ 6          ┆ 5.0        ┆ 58         ┆ 61.33      │
│ Mitchell    ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
│ Brian       ┆ 15   ┆ 17.1       ┆ 11.2       ┆ 4          ┆ 3.0        ┆ 66         ┆ 60.33      │
│ Thomas Jr.  ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
│ CeeDee Lamb ┆ 15   ┆ 17.1       ┆ 19.8       ┆ 6          ┆ 6.33       ┆ 111        ┆ 114.67     │
│ Michael     ┆ 15   ┆ 16.4       ┆ 20.07      ┆ 5          ┆ 6.33       ┆ 54         ┆ 77.33      │
│ Wilson      ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
│ Wan'Dale    ┆ 15   ┆ 16.4       ┆ 19.13      ┆ 5          ┆ 7.0        ┆ 54         ┆ 81.33      │
│ Robinson    ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
│ Terry       ┆ 15   ┆ 15.9       ┆ 15.2       ┆ 3          ┆ 4.33       ┆ 69         ┆ 68.67      │
│ McLaurin    ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
│ Zay Flowers ┆ 15   ┆ 15.8       ┆ 12.33      ┆ 3          ┆ 4.33       ┆ 68         ┆ 66.0       │
│ Ricky       ┆ 15   ┆ 15.6       ┆ 7.27       ┆ 6          ┆ 3.33       ┆ 96         ┆ 38.67      │
│ Pearsall    ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
│ DK Metcalf  ┆ 15   ┆ 14.5       ┆ 14.17      ┆ 3          ┆ 4.33       ┆ 55         ┆ 78.33      │
│ Luther      ┆ 15   ┆ 14.4       ┆ 11.0       ┆ 6          ┆ 4.67       ┆ 84         ┆ 61.33      │
│ Burden III  ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
│ Jalen Coker ┆ 15   ┆ 14.0       ┆ 12.53      ┆ 4          ┆ 3.67       ┆ 60         ┆ 55.33      │
│ David Sills ┆ 15   ┆ 13.8       ┆ 7.77       ┆ 6          ┆ 2.67       ┆ 78         ┆ 31.0       │
│ …           ┆ …    ┆ …          ┆ …          ┆ …          ┆ …          ┆ …          ┆ …          │
│ Dylan       ┆ 15   ┆ 0.0        ┆ 2.13       ┆ 0          ┆ 1.33       ┆ 0          ┆ 8.0        │
│ Drummond    ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
│ Isaac       ┆ 15   ┆ 0.0        ┆ 7.17       ┆ 0          ┆ 1.33       ┆ 0          ┆ 18.33      │
│ TeSlaa      ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
│ Jalin Hyatt ┆ 15   ┆ 0.0        ┆ 1.27       ┆ 0          ┆ 0.67       ┆ 0          ┆ 6.0        │
│ James       ┆ 15   ┆ 0.0        ┆ 0.77       ┆ 0          ┆ 0.33       ┆ 0          ┆ 4.33       │
│ Proche      ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
│ Jaylin Lane ┆ 15   ┆ 0.0        ┆ 0.0        ┆ 0          ┆ 0.0        ┆ 0          ┆ 0.0        │
│ Jaylin Noel ┆ 15   ┆ 0.0        ┆ 1.1        ┆ 0          ┆ 0.67       ┆ 0          ┆ 4.0        │
│ Jordan      ┆ 15   ┆ 0.0        ┆ 0.5        ┆ 0          ┆ 0.33       ┆ 0          ┆ 1.67       │
│ Whittington ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
│ JuJu Smith- ┆ 15   ┆ 0.0        ┆ 0.5        ┆ 0          ┆ 0.33       ┆ 0          ┆ 1.67       │
│ Schuster    ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
│ Kameron     ┆ 15   ┆ 0.0        ┆ 0.0        ┆ 0          ┆ 0.0        ┆ 0          ┆ 0.0        │
│ Johnson     ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
│ KhaDarel    ┆ 15   ┆ 0.0        ┆ 0.0        ┆ 0          ┆ 0.0        ┆ 0          ┆ 0.0        │
│ Hodge       ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
│ Konata      ┆ 15   ┆ 0.0        ┆ 0.5        ┆ 0          ┆ 0.33       ┆ 0          ┆ 1.67       │
│ Mumpfield   ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
│ Kyle        ┆ 15   ┆ 0.0        ┆ 4.37       ┆ 0          ┆ 0.67       ┆ 0          ┆ 17.0       │
│ Williams    ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
│ LaJohntay   ┆ 15   ┆ 0.0        ┆ 0.0        ┆ 0          ┆ 0.0        ┆ 0          ┆ 0.0        │
│ Wester      ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
│ Myles Price ┆ 15   ┆ 0.0        ┆ 0.0        ┆ 0          ┆ 0.0        ┆ 0          ┆ 0.0        │
│ Nick Westbr ┆ 15   ┆ 0.0        ┆ -0.0       ┆ 0          ┆ 0.0        ┆ 0          ┆ 0.0        │
│ ook-Ikhine  ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
│ Nikko       ┆ 15   ┆ 0.0        ┆ 0.0        ┆ 0          ┆ 0.0        ┆ 0          ┆ 0.0        │
│ Remigio     ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
│ Olamide     ┆ 15   ┆ 0.0        ┆ 4.2        ┆ 0          ┆ 1.33       ┆ 0          ┆ 8.67       │
│ Zaccheaus   ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
│ Skyy Moore  ┆ 15   ┆ 0.0        ┆ 0.0        ┆ 0          ┆ 0.0        ┆ 0          ┆ 0.0        │
│ Tez Johnson ┆ 15   ┆ 0.0        ┆ 4.6        ┆ 0          ┆ 1.33       ┆ 0          ┆ 8.67       │
│ Tom Kennedy ┆ 15   ┆ 0.0        ┆ 2.53       ┆ 0          ┆ 1.33       ┆ 0          ┆ 12.0       │
│ Tre Tucker  ┆ 15   ┆ 0.0        ┆ 3.13       ┆ 0          ┆ 1.67       ┆ 0          ┆ 14.67      │
│ Treylon     ┆ 15   ┆ 0.0        ┆ 2.5        ┆ 0          ┆ 0.33       ┆ 0          ┆ 1.67       │
│ Burks       ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
│ Tylan       ┆ 15   ┆ 0.0        ┆ 0.0        ┆ 0          ┆ 0.0        ┆ 0          ┆ 0.0        │
│ Wallace     ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
│ Xavier      ┆ 15   ┆ 0.0        ┆ 4.27       ┆ 0          ┆ 1.33       ┆ 0          ┆ 29.33      │
│ Smith       ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
│ Dyami Brown ┆ 15   ┆ -1.6       ┆ -0.53      ┆ 0          ┆ 0.0        ┆ 0          ┆ 0.0        │
└─────────────┴──────┴────────────┴────────────┴────────────┴────────────┴────────────┴────────────┘

In [54]:
player_rolling_ppr.filter(pl.col('player_display_name') == 'Khalil Shakir').select([
    'player_display_name',
    'week',
    'calculated_ppr',
    'rolling_3_ppr',
    'receptions',
    'rolling_3_receptions',
    'receiving_yards',  
    'rolling_3_receiving_yards'
]).sort('week')

shape: (18, 8)
┌─────────────┬──────┬────────────┬────────────┬────────────┬────────────┬────────────┬────────────┐
│ player_disp ┆ week ┆ calculated ┆ rolling_3_ ┆ receptions ┆ rolling_3_ ┆ receiving_ ┆ rolling_3_ │
│ lay_name    ┆ ---  ┆ _ppr       ┆ ppr        ┆ ---        ┆ receptions ┆ yards      ┆ receiving_ │
│ ---         ┆ i32  ┆ ---        ┆ ---        ┆ i32        ┆ ---        ┆ ---        ┆ yards      │
│ str         ┆      ┆ f64        ┆ f64        ┆            ┆ f64        ┆ i32        ┆ ---        │
│             ┆      ┆            ┆            ┆            ┆            ┆            ┆ f64        │
╞═════════════╪══════╪════════════╪════════════╪════════════╪════════════╪════════════╪════════════╡
│ Khalil      ┆ 1    ┆ 12.4       ┆ null       ┆ 6          ┆ null       ┆ 64         ┆ null       │
│ Shakir      ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
│ Khalil      ┆ 2    ┆ 2.2        ┆ null       ┆ 1          ┆ null       ┆ 12         ┆ null       │
│ Shakir      ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
│ Khalil      ┆ 3    ┆ 14.5       ┆ 9.7        ┆ 4          ┆ 3.67       ┆ 45         ┆ 40.33      │
│ Shakir      ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
│ Khalil      ┆ 4    ┆ 17.9       ┆ 11.53      ┆ 5          ┆ 3.33       ┆ 69         ┆ 42.0       │
│ Shakir      ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
│ Khalil      ┆ 5    ┆ 11.0       ┆ 14.47      ┆ 6          ┆ 5.0        ┆ 45         ┆ 53.0       │
│ Shakir      ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
│ Khalil      ┆ 6    ┆ 6.3        ┆ 11.73      ┆ 3          ┆ 4.67       ┆ 33         ┆ 49.0       │
│ Shakir      ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
│ Khalil      ┆ 8    ┆ 20.8       ┆ 12.7       ┆ 6          ┆ 5.0        ┆ 88         ┆ 55.33      │
│ Shakir      ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
│ Khalil      ┆ 9    ┆ 11.3       ┆ 12.8       ┆ 7          ┆ 5.33       ┆ 43         ┆ 54.67      │
│ Shakir      ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
│ Khalil      ┆ 10   ┆ 12.8       ┆ 14.97      ┆ 7          ┆ 6.67       ┆ 58         ┆ 63.0       │
│ Shakir      ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
│ Khalil      ┆ 11   ┆ 0.7        ┆ 8.27       ┆ 1          ┆ 5.0        ┆ -3         ┆ 32.67      │
│ Shakir      ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
│ Khalil      ┆ 12   ┆ 17.0       ┆ 10.17      ┆ 8          ┆ 5.33       ┆ 110        ┆ 55.0       │
│ Shakir      ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
│ Khalil      ┆ 13   ┆ 1.5        ┆ 6.4        ┆ 1          ┆ 3.33       ┆ 5          ┆ 37.33      │
│ Shakir      ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
│ Khalil      ┆ 14   ┆ 9.6        ┆ 9.37       ┆ 2          ┆ 3.67       ┆ 16         ┆ 43.67      │
│ Shakir      ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
│ Khalil      ┆ 15   ┆ 11.5       ┆ 7.53       ┆ 5          ┆ 2.67       ┆ 65         ┆ 28.67      │
│ Shakir      ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
│ Khalil      ┆ 16   ┆ 7.4        ┆ 9.5        ┆ 4          ┆ 3.67       ┆ 34         ┆ 38.33      │
│ Shakir      ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
│ Khalil      ┆ 17   ┆ 9.5        ┆ 9.47       ┆ 6          ┆ 5.0        ┆ 35         ┆ 44.67      │
│ Shakir      ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
│ Khalil      ┆ 19   ┆ 20.2       ┆ 12.37      ┆ 12         ┆ 7.33       ┆ 82         ┆ 50.33      │
│ Shakir      ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
│ Khalil      ┆ 20   ┆ 14.5       ┆ 14.73      ┆ 7          ┆ 8.33       ┆ 75         ┆ 64.0       │
│ Shakir      ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
└─────────────┴──────┴────────────┴────────────┴────────────┴────────────┴────────────┴────────────┘

In [57]:
player_prediction_features = (
    receiving_stats_ppr
    .sort(["player_display_name", "week"])
    .with_columns(
        pl.col("calculated_ppr")
        .shift(1)
        .rolling_mean(window_size=3)
        .round(2)
        .over("player_display_name")
        .alias("prev_rolling_3_ppr"),

        pl.col("receptions")
        .shift(1)
        .rolling_mean(window_size=3)
        .round(2)
        .over("player_display_name")
        .alias("prev_rolling_3_receptions"),

        pl.col("receiving_yards")
        .shift(1)
        .rolling_mean(window_size=3)
        .round(2)
        .over("player_display_name")
        .alias("prev_rolling_3_receiving_yards")
    )
)

player_prediction_features.filter(pl.col('player_display_name') == 'Ja\'Marr Chase').select([
    'player_display_name',
    'week',
    'calculated_ppr',
    'prev_rolling_3_ppr',
    'receptions',
    'prev_rolling_3_receptions',
    'receiving_yards',  
    'prev_rolling_3_receiving_yards'
]).sort('week')

shape: (16, 8)
┌─────────────┬──────┬────────────┬────────────┬────────────┬────────────┬────────────┬────────────┐
│ player_disp ┆ week ┆ calculated ┆ prev_rolli ┆ receptions ┆ prev_rolli ┆ receiving_ ┆ prev_rolli │
│ lay_name    ┆ ---  ┆ _ppr       ┆ ng_3_ppr   ┆ ---        ┆ ng_3_recep ┆ yards      ┆ ng_3_recei │
│ ---         ┆ i32  ┆ ---        ┆ ---        ┆ i32        ┆ tions      ┆ ---        ┆ ving_yards │
│ str         ┆      ┆ f64        ┆ f64        ┆            ┆ ---        ┆ i32        ┆ ---        │
│             ┆      ┆            ┆            ┆            ┆ f64        ┆            ┆ f64        │
╞═════════════╪══════╪════════════╪════════════╪════════════╪════════════╪════════════╪════════════╡
│ Ja'Marr     ┆ 1    ┆ 4.6        ┆ null       ┆ 2          ┆ null       ┆ 26         ┆ null       │
│ Chase       ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
│ Ja'Marr     ┆ 2    ┆ 36.5       ┆ null       ┆ 14         ┆ null       ┆ 165        ┆ null       │
│ Chase       ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
│ Ja'Marr     ┆ 3    ┆ 8.9        ┆ null       ┆ 5          ┆ null       ┆ 50         ┆ null       │
│ Chase       ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
│ Ja'Marr     ┆ 4    ┆ 7.3        ┆ 16.67      ┆ 5          ┆ 7.0        ┆ 23         ┆ 80.33      │
│ Chase       ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
│ Ja'Marr     ┆ 5    ┆ 29.0       ┆ 17.57      ┆ 6          ┆ 8.0        ┆ 110        ┆ 79.33      │
│ Chase       ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
│ Ja'Marr     ┆ 6    ┆ 25.1       ┆ 15.07      ┆ 10         ┆ 5.33       ┆ 94         ┆ 61.0       │
│ Chase       ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
│ Ja'Marr     ┆ 7    ┆ 38.1       ┆ 20.47      ┆ 16         ┆ 7.0        ┆ 161        ┆ 75.67      │
│ Chase       ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
│ Ja'Marr     ┆ 8    ┆ 21.1       ┆ 30.73      ┆ 12         ┆ 10.67      ┆ 91         ┆ 121.67     │
│ Chase       ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
│ Ja'Marr     ┆ 9    ┆ 17.1       ┆ 28.1       ┆ 6          ┆ 12.67      ┆ 111        ┆ 115.33     │
│ Chase       ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
│ Ja'Marr     ┆ 11   ┆ 6.0        ┆ 25.43      ┆ 3          ┆ 11.33      ┆ 30         ┆ 121.0      │
│ Chase       ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
│ Ja'Marr     ┆ 13   ┆ 18.0       ┆ 14.73      ┆ 7          ┆ 7.0        ┆ 110        ┆ 77.33      │
│ Chase       ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
│ Ja'Marr     ┆ 14   ┆ 10.2       ┆ 13.7       ┆ 5          ┆ 5.33       ┆ 44         ┆ 83.67      │
│ Chase       ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
│ Ja'Marr     ┆ 15   ┆ 23.2       ┆ 11.4       ┆ 10         ┆ 5.0        ┆ 132        ┆ 61.33      │
│ Chase       ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
│ Ja'Marr     ┆ 16   ┆ 19.9       ┆ 17.13      ┆ 9          ┆ 7.33       ┆ 109        ┆ 95.33      │
│ Chase       ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
│ Ja'Marr     ┆ 17   ┆ 25.0       ┆ 17.77      ┆ 7          ┆ 8.0        ┆ 60         ┆ 95.0       │
│ Chase       ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
│ Ja'Marr     ┆ 18   ┆ 23.6       ┆ 22.7       ┆ 8          ┆ 8.67       ┆ 96         ┆ 100.33     │
│ Chase       ┆      ┆            ┆            ┆            ┆            ┆            ┆            │
└─────────────┴──────┴────────────┴────────────┴────────────┴────────────┴────────────┴────────────┘