In [6]:
import pandas as pd
import nflreadpy as nfl
import polars as pl
import matplotlib.pyplot as plt
import sys
from pathlib import Path
import sklearn
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import root_mean_squared_error

In [7]:
weekly = nfl.load_player_stats([2021, 2022, 2023, 2024, 2025])
weekly

shape: (94_848, 150)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ player_id ┆ player_na ┆ player_di ┆ position ┆ … ┆ pt_return ┆ pt_net_ya ┆ fantasy_p ┆ fantasy_p │
│ ---       ┆ me        ┆ splay_nam ┆ ---      ┆   ┆ _tds      ┆ rds       ┆ oints     ┆ oints_ppr │
│ str       ┆ ---       ┆ e         ┆ str      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│           ┆ str       ┆ ---       ┆          ┆   ┆ i32       ┆ i32       ┆ f64       ┆ f64       │
│           ┆           ┆ str       ┆          ┆   ┆           ┆           ┆           ┆           │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 00-001959 ┆ T.Brady   ┆ Tom Brady ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 27.16     ┆ 27.16     │
│ 6         ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-002282 ┆ A.Lee     ┆ Andy Lee  ┆ P        ┆ … ┆ 0         ┆ 124       ┆ 0.0       ┆ 0.0       │
│ 4         ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-002292 ┆ B.Roethli ┆ Ben Roeth ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 12.02     ┆ 12.02     │
│ 4         ┆ sberger   ┆ lisberger ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-002325 ┆ R.Gould   ┆ Robbie    ┆ K        ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 2         ┆           ┆ Gould     ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-002345 ┆ Aa.Rodger ┆ Aaron     ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 1.32      ┆ 1.32      │
│ 9         ┆ s         ┆ Rodgers   ┆          ┆   ┆           ┆           ┆           ┆           │
│ …         ┆ …         ┆ …         ┆ …        ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 00-004069 ┆ W.Campbel ┆ Will      ┆ OT       ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 9         ┆ l         ┆ Campbell  ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-004071 ┆ C.Woodson ┆ Craig     ┆ SAF      ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 6         ┆           ┆ Woodson   ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-004073 ┆ N.Emmanwo ┆ Nick      ┆ SAF      ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 3         ┆ ri        ┆ Emmanwori ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-004073 ┆ T.Henders ┆ TreVeyon  ┆ RB       ┆ … ┆ 0         ┆ 0         ┆ 4.5       ┆ 7.5       │
│ 4         ┆ on        ┆ Henderson ┆          ┆   ┆           ┆           ┆           ┆           │
│ null      ┆ null      ┆ null      ┆ null     ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [8]:
receivers = weekly.filter((weekly['position'] == 'WR') & (weekly['season_type'] == 'REG'))
receiving_stats = receivers.select([
    "player_display_name",
    "season",
    "season_type",
    "week",
    "team",
    "opponent_team",
    "receptions",
    "targets",
    "receiving_yards",
    "receiving_tds",
    "receiving_fumbles_lost",
    "receiving_2pt_conversions",
    "special_teams_tds",
    "rushing_yards",
    "rushing_tds",
    "rushing_fumbles_lost",
    "rushing_2pt_conversions",
    "fantasy_points_ppr",
])

receiving_stats

shape: (12_298, 18)
┌─────────────┬────────┬────────────┬──────┬───┬────────────┬────────────┬────────────┬────────────┐
│ player_disp ┆ season ┆ season_typ ┆ week ┆ … ┆ rushing_td ┆ rushing_fu ┆ rushing_2p ┆ fantasy_po │
│ lay_name    ┆ ---    ┆ e          ┆ ---  ┆   ┆ s          ┆ mbles_lost ┆ t_conversi ┆ ints_ppr   │
│ ---         ┆ i32    ┆ ---        ┆ i32  ┆   ┆ ---        ┆ ---        ┆ ons        ┆ ---        │
│ str         ┆        ┆ str        ┆      ┆   ┆ i32        ┆ i32        ┆ ---        ┆ f64        │
│             ┆        ┆            ┆      ┆   ┆            ┆            ┆ i32        ┆            │
╞═════════════╪════════╪════════════╪══════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ Danny       ┆ 2021   ┆ REG        ┆ 1    ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 14.4       │
│ Amendola    ┆        ┆            ┆      ┆   ┆            ┆            ┆            ┆            │
│ DeSean      ┆ 2021   ┆ REG        ┆ 1    ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 4.1        │
│ Jackson     ┆        ┆            ┆      ┆   ┆            ┆            ┆            ┆            │
│ Emmanuel    ┆ 2021   ┆ REG        ┆ 1    ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 9.2        │
│ Sanders     ┆        ┆            ┆      ┆   ┆            ┆            ┆            ┆            │
│ Andre       ┆ 2021   ┆ REG        ┆ 1    ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 0.0        │
│ Roberts     ┆        ┆            ┆      ┆   ┆            ┆            ┆            ┆            │
│ Antonio     ┆ 2021   ┆ REG        ┆ 1    ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 23.7       │
│ Brown       ┆        ┆            ┆      ┆   ┆            ┆            ┆            ┆            │
│ …           ┆ …      ┆ …          ┆ …    ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ Chimere     ┆ 2025   ┆ REG        ┆ 18   ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 5.7        │
│ Dike        ┆        ┆            ┆      ┆   ┆            ┆            ┆            ┆            │
│ Tre Harris  ┆ 2025   ┆ REG        ┆ 18   ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 4.8        │
│ Jack Bech   ┆ 2025   ┆ REG        ┆ 18   ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 0.0        │
│ Luther      ┆ 2025   ┆ REG        ┆ 18   ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 7.5        │
│ Burden III  ┆        ┆            ┆      ┆   ┆            ┆            ┆            ┆            │
│ Isaiah Bond ┆ 2025   ┆ REG        ┆ 18   ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 2.7        │
└─────────────┴────────┴────────────┴──────┴───┴────────────┴────────────┴────────────┴────────────┘

In [9]:
project_root = Path.cwd().parent
sys.path.append(str(project_root))

from src.scoring import calculate_ppr

receiving_stats_ppr = calculate_ppr(receiving_stats)
receiving_stats_ppr

shape: (12_298, 19)
┌─────────────┬────────┬────────────┬──────┬───┬────────────┬────────────┬────────────┬────────────┐
│ player_disp ┆ season ┆ season_typ ┆ week ┆ … ┆ rushing_fu ┆ rushing_2p ┆ fantasy_po ┆ calculated │
│ lay_name    ┆ ---    ┆ e          ┆ ---  ┆   ┆ mbles_lost ┆ t_conversi ┆ ints_ppr   ┆ _ppr       │
│ ---         ┆ i32    ┆ ---        ┆ i32  ┆   ┆ ---        ┆ ons        ┆ ---        ┆ ---        │
│ str         ┆        ┆ str        ┆      ┆   ┆ i32        ┆ ---        ┆ f64        ┆ f64        │
│             ┆        ┆            ┆      ┆   ┆            ┆ i32        ┆            ┆            │
╞═════════════╪════════╪════════════╪══════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ Danny       ┆ 2021   ┆ REG        ┆ 1    ┆ … ┆ 0          ┆ 0          ┆ 14.4       ┆ 14.4       │
│ Amendola    ┆        ┆            ┆      ┆   ┆            ┆            ┆            ┆            │
│ DeSean      ┆ 2021   ┆ REG        ┆ 1    ┆ … ┆ 0          ┆ 0          ┆ 4.1        ┆ 4.1        │
│ Jackson     ┆        ┆            ┆      ┆   ┆            ┆            ┆            ┆            │
│ Emmanuel    ┆ 2021   ┆ REG        ┆ 1    ┆ … ┆ 0          ┆ 0          ┆ 9.2        ┆ 9.2        │
│ Sanders     ┆        ┆            ┆      ┆   ┆            ┆            ┆            ┆            │
│ Andre       ┆ 2021   ┆ REG        ┆ 1    ┆ … ┆ 0          ┆ 0          ┆ 0.0        ┆ 0.0        │
│ Roberts     ┆        ┆            ┆      ┆   ┆            ┆            ┆            ┆            │
│ Antonio     ┆ 2021   ┆ REG        ┆ 1    ┆ … ┆ 0          ┆ 0          ┆ 23.7       ┆ 23.7       │
│ Brown       ┆        ┆            ┆      ┆   ┆            ┆            ┆            ┆            │
│ …           ┆ …      ┆ …          ┆ …    ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ Chimere     ┆ 2025   ┆ REG        ┆ 18   ┆ … ┆ 0          ┆ 0          ┆ 5.7        ┆ 5.7        │
│ Dike        ┆        ┆            ┆      ┆   ┆            ┆            ┆            ┆            │
│ Tre Harris  ┆ 2025   ┆ REG        ┆ 18   ┆ … ┆ 0          ┆ 0          ┆ 4.8        ┆ 4.8        │
│ Jack Bech   ┆ 2025   ┆ REG        ┆ 18   ┆ … ┆ 0          ┆ 0          ┆ 0.0        ┆ 0.0        │
│ Luther      ┆ 2025   ┆ REG        ┆ 18   ┆ … ┆ 0          ┆ 0          ┆ 7.5        ┆ 7.5        │
│ Burden III  ┆        ┆            ┆      ┆   ┆            ┆            ┆            ┆            │
│ Isaiah Bond ┆ 2025   ┆ REG        ┆ 18   ┆ … ┆ 0          ┆ 0          ┆ 2.7        ┆ 2.7        │
└─────────────┴────────┴────────────┴──────┴───┴────────────┴────────────┴────────────┴────────────┘

In [10]:
project_root = Path.cwd().parent
sys.path.append(str(project_root))

from src.features import create_features
from src.features import create_defensive_features

player_prediction_features = create_features(receiving_stats_ppr)
player_prediction_features = create_defensive_features(player_prediction_features)

player_prediction_features

shape: (12_298, 25)
┌─────────────┬────────┬────────────┬──────┬───┬────────────┬────────────┬────────────┬────────────┐
│ player_disp ┆ season ┆ season_typ ┆ week ┆ … ┆ prev_rolli ┆ prev_rolli ┆ prev_seaso ┆ prev_defen │
│ lay_name    ┆ ---    ┆ e          ┆ ---  ┆   ┆ ng_3_recep ┆ ng_3_recei ┆ n_avg_ppr  ┆ se_wr_ppr_ │
│ ---         ┆ i32    ┆ ---        ┆ i32  ┆   ┆ tions      ┆ ving_yards ┆ ---        ┆ allowed_av │
│ str         ┆        ┆ str        ┆      ┆   ┆ ---        ┆ ---        ┆ f64        ┆ …          │
│             ┆        ┆            ┆      ┆   ┆ f64        ┆ f64        ┆            ┆ ---        │
│             ┆        ┆            ┆      ┆   ┆            ┆            ┆            ┆ f64        │
╞═════════════╪════════╪════════════╪══════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ A.J. Brown  ┆ 2021   ┆ REG        ┆ 1    ┆ … ┆ null       ┆ null       ┆ null       ┆ null       │
│ A.J. Brown  ┆ 2021   ┆ REG        ┆ 2    ┆ … ┆ null       ┆ null       ┆ 14.9       ┆ 34.2       │
│ A.J. Brown  ┆ 2021   ┆ REG        ┆ 3    ┆ … ┆ null       ┆ null       ┆ 11.1       ┆ 48.75      │
│ A.J. Brown  ┆ 2021   ┆ REG        ┆ 5    ┆ … ┆ 2.33       ┆ 30.67      ┆ 7.5        ┆ 40.88      │
│ A.J. Brown  ┆ 2021   ┆ REG        ┆ 6    ┆ … ┆ 2.0        ┆ 27.0       ┆ 7.32       ┆ 26.62      │
│ …           ┆ …      ┆ …          ┆ …    ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ Zay Jones   ┆ 2025   ┆ REG        ┆ 3    ┆ … ┆ 2.0        ┆ 23.0       ┆ 1.4        ┆ 30.7       │
│ Zay Jones   ┆ 2025   ┆ REG        ┆ 5    ┆ … ┆ 2.33       ┆ 25.0       ┆ 2.95       ┆ 38.7       │
│ Zay Jones   ┆ 2025   ┆ REG        ┆ 6    ┆ … ┆ 1.67       ┆ 12.33      ┆ 2.9        ┆ 38.02      │
│ Zay Jones   ┆ 2025   ┆ REG        ┆ 7    ┆ … ┆ 3.0        ┆ 37.33      ┆ 5.4        ┆ 33.42      │
│ Zay Jones   ┆ 2025   ┆ REG        ┆ 10   ┆ … ┆ 3.0        ┆ 51.33      ┆ 6.06       ┆ 29.04      │
└─────────────┴────────┴────────────┴──────┴───┴────────────┴────────────┴────────────┴────────────┘

In [11]:
with pl.Config(tbl_rows=-1):
    print(player_prediction_features.filter(pl.col("player_display_name") == 'CeeDee Lamb').head(20))
# player_prediction_features.filter(
#     pl.col("player_display_name") == "A.J. Brown"
# ).select([
#     "player_display_name",
#     "season",
#     "week",
#     "calculated_ppr",
#     "prev_rolling_3_ppr",
#     "targets",
#     "prev_rolling_3_targets",
#     "receptions",
#     "prev_rolling_3_receptions",
#     "receiving_yards",
#     "prev_rolling_3_receiving_yards"
# ]).sort(["season", "week"])

shape: (20, 25)
┌─────────────┬────────┬────────────┬──────┬───┬────────────┬────────────┬────────────┬────────────┐
│ player_disp ┆ season ┆ season_typ ┆ week ┆ … ┆ prev_rolli ┆ prev_rolli ┆ prev_seaso ┆ prev_defen │
│ lay_name    ┆ ---    ┆ e          ┆ ---  ┆   ┆ ng_3_recep ┆ ng_3_recei ┆ n_avg_ppr  ┆ se_wr_ppr_ │
│ ---         ┆ i32    ┆ ---        ┆ i32  ┆   ┆ tions      ┆ ving_yards ┆ ---        ┆ allowed_av │
│ str         ┆        ┆ str        ┆      ┆   ┆ ---        ┆ ---        ┆ f64        ┆ …          │
│             ┆        ┆            ┆      ┆   ┆ f64        ┆ f64        ┆            ┆ ---        │
│             ┆        ┆            ┆      ┆   ┆            ┆            ┆            ┆ f64        │
╞═════════════╪════════╪════════════╪══════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ CeeDee Lamb ┆ 2021   ┆ REG        ┆ 1    ┆ … ┆ null       ┆ null       ┆ null       ┆ null       │
│ CeeDee Lamb ┆ 2021   ┆ REG        ┆ 2    ┆ … ┆ null       ┆ null       ┆ 23.4       ┆ 16.7       │
│ CeeDee Lamb ┆ 2021   ┆ REG        ┆ 3    ┆ … ┆ null       ┆ null       ┆ 20.4       ┆ 19.7       │
│ CeeDee Lamb ┆ 2021   ┆ REG        ┆ 4    ┆ … ┆ 6.0        ┆ 83.67      ┆ 16.77      ┆ 29.2       │
│ CeeDee Lamb ┆ 2021   ┆ REG        ┆ 5    ┆ … ┆ 4.33       ┆ 53.33      ┆ 13.4       ┆ 35.3       │
│ CeeDee Lamb ┆ 2021   ┆ REG        ┆ 6    ┆ … ┆ 3.0        ┆ 54.33      ┆ 14.48      ┆ 32.06      │
│ CeeDee Lamb ┆ 2021   ┆ REG        ┆ 8    ┆ … ┆ 5.0        ┆ 82.0       ┆ 18.08      ┆ 35.98      │
│ CeeDee Lamb ┆ 2021   ┆ REG        ┆ 9    ┆ … ┆ 6.33       ┆ 115.0      ┆ 17.96      ┆ 33.43      │
│ CeeDee Lamb ┆ 2021   ┆ REG        ┆ 10   ┆ … ┆ 5.67       ┆ 94.67      ┆ 16.25      ┆ 35.04      │
│ CeeDee Lamb ┆ 2021   ┆ REG        ┆ 11   ┆ … ┆ 4.67       ┆ 76.33      ┆ 17.62      ┆ 33.52      │
│ CeeDee Lamb ┆ 2021   ┆ REG        ┆ 13   ┆ … ┆ 3.67       ┆ 43.67      ┆ 16.3       ┆ 37.74      │
│ CeeDee Lamb ┆ 2021   ┆ REG        ┆ 14   ┆ … ┆ 5.33       ┆ 65.67      ┆ 16.56      ┆ 38.83      │
│ CeeDee Lamb ┆ 2021   ┆ REG        ┆ 15   ┆ … ┆ 5.67       ┆ 54.67      ┆ 16.4       ┆ 37.33      │
│ CeeDee Lamb ┆ 2021   ┆ REG        ┆ 16   ┆ … ┆ 6.67       ┆ 66.67      ┆ 15.98      ┆ 38.67      │
│ CeeDee Lamb ┆ 2021   ┆ REG        ┆ 17   ┆ … ┆ 5.67       ┆ 59.0       ┆ 15.59      ┆ 36.61      │
│ CeeDee Lamb ┆ 2021   ┆ REG        ┆ 18   ┆ … ┆ 4.33       ┆ 55.67      ┆ 15.09      ┆ 27.4       │
│ CeeDee Lamb ┆ 2022   ┆ REG        ┆ 1    ┆ … ┆ 3.0        ┆ 54.0       ┆ null       ┆ null       │
│ CeeDee Lamb ┆ 2022   ┆ REG        ┆ 2    ┆ … ┆ 2.33       ┆ 41.67      ┆ 4.9        ┆ 23.2       │
│ CeeDee Lamb ┆ 2022   ┆ REG        ┆ 3    ┆ … ┆ 3.67       ┆ 49.67      ┆ 10.0       ┆ 23.8       │
│ CeeDee Lamb ┆ 2022   ┆ REG        ┆ 4    ┆ … ┆ 5.67       ┆ 63.67      ┆ 14.23      ┆ 49.2       │
└─────────────┴────────┴────────────┴──────┴───┴────────────┴────────────┴────────────┴────────────┘

In [12]:
player_prediction_features = (
    player_prediction_features
    .sort(["player_display_name", "season", "week"])
    .with_columns(
        (
            pl.col("calculated_ppr").shift(1).cum_sum().over(["player_display_name", "season"])
            /
            pl.col("calculated_ppr").shift(1).cum_count().over(["player_display_name", "season"])
        )
        .round(2)
        .alias("prev_season_avg_ppr")
    )
)

player_prediction_features

shape: (12_298, 25)
┌─────────────┬────────┬────────────┬──────┬───┬────────────┬────────────┬────────────┬────────────┐
│ player_disp ┆ season ┆ season_typ ┆ week ┆ … ┆ prev_rolli ┆ prev_rolli ┆ prev_seaso ┆ prev_defen │
│ lay_name    ┆ ---    ┆ e          ┆ ---  ┆   ┆ ng_3_recep ┆ ng_3_recei ┆ n_avg_ppr  ┆ se_wr_ppr_ │
│ ---         ┆ i32    ┆ ---        ┆ i32  ┆   ┆ tions      ┆ ving_yards ┆ ---        ┆ allowed_av │
│ str         ┆        ┆ str        ┆      ┆   ┆ ---        ┆ ---        ┆ f64        ┆ …          │
│             ┆        ┆            ┆      ┆   ┆ f64        ┆ f64        ┆            ┆ ---        │
│             ┆        ┆            ┆      ┆   ┆            ┆            ┆            ┆ f64        │
╞═════════════╪════════╪════════════╪══════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ A.J. Brown  ┆ 2021   ┆ REG        ┆ 1    ┆ … ┆ null       ┆ null       ┆ null       ┆ null       │
│ A.J. Brown  ┆ 2021   ┆ REG        ┆ 2    ┆ … ┆ null       ┆ null       ┆ 14.9       ┆ 34.2       │
│ A.J. Brown  ┆ 2021   ┆ REG        ┆ 3    ┆ … ┆ null       ┆ null       ┆ 11.1       ┆ 48.75      │
│ A.J. Brown  ┆ 2021   ┆ REG        ┆ 5    ┆ … ┆ 2.33       ┆ 30.67      ┆ 7.5        ┆ 40.88      │
│ A.J. Brown  ┆ 2021   ┆ REG        ┆ 6    ┆ … ┆ 2.0        ┆ 27.0       ┆ 7.32       ┆ 26.62      │
│ …           ┆ …      ┆ …          ┆ …    ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ Zay Jones   ┆ 2025   ┆ REG        ┆ 3    ┆ … ┆ 2.0        ┆ 23.0       ┆ 1.4        ┆ 30.7       │
│ Zay Jones   ┆ 2025   ┆ REG        ┆ 5    ┆ … ┆ 2.33       ┆ 25.0       ┆ 2.95       ┆ 38.7       │
│ Zay Jones   ┆ 2025   ┆ REG        ┆ 6    ┆ … ┆ 1.67       ┆ 12.33      ┆ 2.9        ┆ 38.02      │
│ Zay Jones   ┆ 2025   ┆ REG        ┆ 7    ┆ … ┆ 3.0        ┆ 37.33      ┆ 5.4        ┆ 33.42      │
│ Zay Jones   ┆ 2025   ┆ REG        ┆ 10   ┆ … ┆ 3.0        ┆ 51.33      ┆ 6.06       ┆ 29.04      │
└─────────────┴────────┴────────────┴──────┴───┴────────────┴────────────┴────────────┴────────────┘

In [13]:
player_prediction_features.filter(
    pl.col("player_display_name") == "A.J. Brown"
).select([
    "player_display_name",
    "season",
    "week",
    "calculated_ppr",
    "prev_season_avg_ppr"
]).sort(["season", "week"])

shape: (75, 5)
┌─────────────────────┬────────┬──────┬────────────────┬─────────────────────┐
│ player_display_name ┆ season ┆ week ┆ calculated_ppr ┆ prev_season_avg_ppr │
│ ---                 ┆ ---    ┆ ---  ┆ ---            ┆ ---                 │
│ str                 ┆ i32    ┆ i32  ┆ f64            ┆ f64                 │
╞═════════════════════╪════════╪══════╪════════════════╪═════════════════════╡
│ A.J. Brown          ┆ 2021   ┆ 1    ┆ 14.9           ┆ null                │
│ A.J. Brown          ┆ 2021   ┆ 2    ┆ 7.3            ┆ 14.9                │
│ A.J. Brown          ┆ 2021   ┆ 3    ┆ 0.3            ┆ 11.1                │
│ A.J. Brown          ┆ 2021   ┆ 5    ┆ 6.8            ┆ 7.5                 │
│ A.J. Brown          ┆ 2021   ┆ 6    ┆ 16.1           ┆ 7.32                │
│ …                   ┆ …      ┆ …    ┆ …              ┆ …                   │
│ A.J. Brown          ┆ 2025   ┆ 13   ┆ 35.2           ┆ 12.67               │
│ A.J. Brown          ┆ 2025   ┆ 14   ┆ 16.0           ┆ 14.72               │
│ A.J. Brown          ┆ 2025   ┆ 15   ┆ 12.1           ┆ 14.82               │
│ A.J. Brown          ┆ 2025   ┆ 16   ┆ 18.5           ┆ 14.62               │
│ A.J. Brown          ┆ 2025   ┆ 17   ┆ 11.8           ┆ 14.89               │
└─────────────────────┴────────┴──────┴────────────────┴─────────────────────┘

In [14]:
defense_week_wr_yds_allowed = (
    player_prediction_features
    .group_by("season", "week", "opponent_team")
    .agg (
        pl.col("receiving_yards").sum().alias("wr_receiving_yards_allowed")
    ).sort("opponent_team", "season", "week")
)
defense_week_wr_yds_allowed

shape: (2_718, 4)
┌────────┬──────┬───────────────┬────────────────────────────┐
│ season ┆ week ┆ opponent_team ┆ wr_receiving_yards_allowed │
│ ---    ┆ ---  ┆ ---           ┆ ---                        │
│ i32    ┆ i32  ┆ str           ┆ i32                        │
╞════════╪══════╪═══════════════╪════════════════════════════╡
│ 2021   ┆ 1    ┆ ARI           ┆ 150                        │
│ 2021   ┆ 2    ┆ ARI           ┆ 195                        │
│ 2021   ┆ 3    ┆ ARI           ┆ 159                        │
│ 2021   ┆ 4    ┆ ARI           ┆ 208                        │
│ 2021   ┆ 5    ┆ ARI           ┆ 109                        │
│ …      ┆ …    ┆ …             ┆ …                          │
│ 2025   ┆ 14   ┆ WAS           ┆ 113                        │
│ 2025   ┆ 15   ┆ WAS           ┆ 111                        │
│ 2025   ┆ 16   ┆ WAS           ┆ 150                        │
│ 2025   ┆ 17   ┆ WAS           ┆ 241                        │
│ 2025   ┆ 18   ┆ WAS           ┆ 145                        │
└────────┴──────┴───────────────┴────────────────────────────┘

In [15]:
defense_week_wr_yds_allowed = (
    defense_week_wr_yds_allowed
    .with_columns(
        (
            pl.col("wr_receiving_yards_allowed").shift(1).cum_sum().over(["opponent_team", "season"])
            /
            pl.col("wr_receiving_yards_allowed").shift(1).cum_count().over(["opponent_team", "season"])
        )
        .round(2)
        .alias("prev_defense_wr_yds_allowed_avg")
    )
)
defense_week_wr_yds_allowed

shape: (2_718, 5)
┌────────┬──────┬───────────────┬────────────────────────────┬─────────────────────────────────┐
│ season ┆ week ┆ opponent_team ┆ wr_receiving_yards_allowed ┆ prev_defense_wr_yds_allowed_av… │
│ ---    ┆ ---  ┆ ---           ┆ ---                        ┆ ---                             │
│ i32    ┆ i32  ┆ str           ┆ i32                        ┆ f64                             │
╞════════╪══════╪═══════════════╪════════════════════════════╪═════════════════════════════════╡
│ 2021   ┆ 1    ┆ ARI           ┆ 150                        ┆ null                            │
│ 2021   ┆ 2    ┆ ARI           ┆ 195                        ┆ 150.0                           │
│ 2021   ┆ 3    ┆ ARI           ┆ 159                        ┆ 172.5                           │
│ 2021   ┆ 4    ┆ ARI           ┆ 208                        ┆ 168.0                           │
│ 2021   ┆ 5    ┆ ARI           ┆ 109                        ┆ 178.0                           │
│ …      ┆ …    ┆ …             ┆ …                          ┆ …                               │
│ 2025   ┆ 14   ┆ WAS           ┆ 113                        ┆ 167.17                          │
│ 2025   ┆ 15   ┆ WAS           ┆ 111                        ┆ 163.0                           │
│ 2025   ┆ 16   ┆ WAS           ┆ 150                        ┆ 159.29                          │
│ 2025   ┆ 17   ┆ WAS           ┆ 241                        ┆ 158.67                          │
│ 2025   ┆ 18   ┆ WAS           ┆ 145                        ┆ 163.81                          │
└────────┴──────┴───────────────┴────────────────────────────┴─────────────────────────────────┘

In [16]:
defense_week_wr_yds_allowed.filter(
    (pl.col("opponent_team") == "DAL") & (pl.col("season") == 2025)
).select([
    "season",
    "week",
    "opponent_team",
    "wr_receiving_yards_allowed",
    "prev_defense_wr_yds_allowed_avg"
]).sort("week")

shape: (17, 5)
┌────────┬──────┬───────────────┬────────────────────────────┬─────────────────────────────────┐
│ season ┆ week ┆ opponent_team ┆ wr_receiving_yards_allowed ┆ prev_defense_wr_yds_allowed_av… │
│ ---    ┆ ---  ┆ ---           ┆ ---                        ┆ ---                             │
│ i32    ┆ i32  ┆ str           ┆ i32                        ┆ f64                             │
╞════════╪══════╪═══════════════╪════════════════════════════╪═════════════════════════════════╡
│ 2025   ┆ 1    ┆ DAL           ┆ 83                         ┆ null                            │
│ 2025   ┆ 2    ┆ DAL           ┆ 370                        ┆ 83.0                            │
│ 2025   ┆ 3    ┆ DAL           ┆ 208                        ┆ 226.5                           │
│ 2025   ┆ 4    ┆ DAL           ┆ 166                        ┆ 220.33                          │
│ 2025   ┆ 5    ┆ DAL           ┆ 117                        ┆ 206.75                          │
│ …      ┆ …    ┆ …             ┆ …                          ┆ …                               │
│ 2025   ┆ 14   ┆ DAL           ┆ 208                        ┆ 168.0                           │
│ 2025   ┆ 15   ┆ DAL           ┆ 135                        ┆ 171.08                          │
│ 2025   ┆ 16   ┆ DAL           ┆ 255                        ┆ 168.5                           │
│ 2025   ┆ 17   ┆ DAL           ┆ 157                        ┆ 174.27                          │
│ 2025   ┆ 18   ┆ DAL           ┆ 136                        ┆ 173.19                          │
└────────┴──────┴───────────────┴────────────────────────────┴─────────────────────────────────┘

In [17]:
player_prediction_features = player_prediction_features.join(
    defense_week_wr_yds_allowed.select([
        "season",
        "week",
        "opponent_team",
        "prev_defense_wr_yds_allowed_avg",
    ]),
    on=["season", "week", "opponent_team"],
    how="left",
)
player_prediction_features

shape: (12_298, 26)
┌─────────────┬────────┬────────────┬──────┬───┬────────────┬────────────┬────────────┬────────────┐
│ player_disp ┆ season ┆ season_typ ┆ week ┆ … ┆ prev_rolli ┆ prev_seaso ┆ prev_defen ┆ prev_defen │
│ lay_name    ┆ ---    ┆ e          ┆ ---  ┆   ┆ ng_3_recei ┆ n_avg_ppr  ┆ se_wr_ppr_ ┆ se_wr_yds_ │
│ ---         ┆ i32    ┆ ---        ┆ i32  ┆   ┆ ving_yards ┆ ---        ┆ allowed_av ┆ allowed_av │
│ str         ┆        ┆ str        ┆      ┆   ┆ ---        ┆ f64        ┆ …          ┆ …          │
│             ┆        ┆            ┆      ┆   ┆ f64        ┆            ┆ ---        ┆ ---        │
│             ┆        ┆            ┆      ┆   ┆            ┆            ┆ f64        ┆ f64        │
╞═════════════╪════════╪════════════╪══════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ A.J. Brown  ┆ 2021   ┆ REG        ┆ 1    ┆ … ┆ null       ┆ null       ┆ null       ┆ null       │
│ A.J. Brown  ┆ 2021   ┆ REG        ┆ 2    ┆ … ┆ null       ┆ 14.9       ┆ 34.2       ┆ 122.0      │
│ A.J. Brown  ┆ 2021   ┆ REG        ┆ 3    ┆ … ┆ null       ┆ 11.1       ┆ 48.75      ┆ 203.5      │
│ A.J. Brown  ┆ 2021   ┆ REG        ┆ 5    ┆ … ┆ 30.67      ┆ 7.5        ┆ 40.88      ┆ 223.0      │
│ A.J. Brown  ┆ 2021   ┆ REG        ┆ 6    ┆ … ┆ 27.0       ┆ 7.32       ┆ 26.62      ┆ 111.6      │
│ …           ┆ …      ┆ …          ┆ …    ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ Zay Jones   ┆ 2025   ┆ REG        ┆ 3    ┆ … ┆ 23.0       ┆ 1.4        ┆ 30.7       ┆ 137.0      │
│ Zay Jones   ┆ 2025   ┆ REG        ┆ 5    ┆ … ┆ 25.0       ┆ 2.95       ┆ 38.7       ┆ 167.75     │
│ Zay Jones   ┆ 2025   ┆ REG        ┆ 6    ┆ … ┆ 12.33      ┆ 2.9        ┆ 38.02      ┆ 161.8      │
│ Zay Jones   ┆ 2025   ┆ REG        ┆ 7    ┆ … ┆ 37.33      ┆ 5.4        ┆ 33.42      ┆ 137.0      │
│ Zay Jones   ┆ 2025   ┆ REG        ┆ 10   ┆ … ┆ 51.33      ┆ 6.06       ┆ 29.04      ┆ 130.25     │
└─────────────┴────────┴────────────┴──────┴───┴────────────┴────────────┴────────────┴────────────┘

In [18]:
baseline_predictions = (
    player_prediction_features
    .with_columns(
        pl.col("prev_rolling_3_ppr").alias("baseline_prediction"),
        pl.col("prev_season_avg_ppr").alias("baseline_prediction_season")
    )
)

baseline_prediction_clean = baseline_predictions.filter(
    (pl.col("prev_rolling_3_ppr").is_not_null())
)

baseline_prediction_clean = baseline_prediction_clean.with_columns(
    (pl.col("baseline_prediction") - pl.col("calculated_ppr"))
    .abs()
    .round(2)
    .alias("absolute_error"),

    (pl.col("calculated_ppr") - pl.col("prev_season_avg_ppr"))
    .abs()
    .round(2)
    .alias("season_avg_error"),
)

baseline_prediction_clean

shape: (11_014, 30)
┌─────────────┬────────┬────────────┬──────┬───┬────────────┬────────────┬────────────┬────────────┐
│ player_disp ┆ season ┆ season_typ ┆ week ┆ … ┆ baseline_p ┆ baseline_p ┆ absolute_e ┆ season_avg │
│ lay_name    ┆ ---    ┆ e          ┆ ---  ┆   ┆ rediction  ┆ rediction_ ┆ rror       ┆ _error     │
│ ---         ┆ i32    ┆ ---        ┆ i32  ┆   ┆ ---        ┆ season     ┆ ---        ┆ ---        │
│ str         ┆        ┆ str        ┆      ┆   ┆ f64        ┆ ---        ┆ f64        ┆ f64        │
│             ┆        ┆            ┆      ┆   ┆            ┆ f64        ┆            ┆            │
╞═════════════╪════════╪════════════╪══════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ A.J. Brown  ┆ 2021   ┆ REG        ┆ 5    ┆ … ┆ 7.5        ┆ 7.5        ┆ 0.7        ┆ 0.7        │
│ A.J. Brown  ┆ 2021   ┆ REG        ┆ 6    ┆ … ┆ 4.8        ┆ 7.32       ┆ 11.3       ┆ 8.78       │
│ A.J. Brown  ┆ 2021   ┆ REG        ┆ 7    ┆ … ┆ 7.73       ┆ 9.08       ┆ 19.57      ┆ 18.22      │
│ A.J. Brown  ┆ 2021   ┆ REG        ┆ 8    ┆ … ┆ 16.73      ┆ 12.12      ┆ 14.77      ┆ 19.38      │
│ A.J. Brown  ┆ 2021   ┆ REG        ┆ 9    ┆ … ┆ 24.97      ┆ 14.89      ┆ 15.77      ┆ 5.69       │
│ …           ┆ …      ┆ …          ┆ …    ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ Zay Jones   ┆ 2025   ┆ REG        ┆ 3    ┆ … ┆ 4.3        ┆ 1.4        ┆ 0.2        ┆ 3.1        │
│ Zay Jones   ┆ 2025   ┆ REG        ┆ 5    ┆ … ┆ 4.83       ┆ 2.95       ┆ 2.03       ┆ 0.15       │
│ Zay Jones   ┆ 2025   ┆ REG        ┆ 6    ┆ … ┆ 2.9        ┆ 2.9        ┆ 10.0       ┆ 10.0       │
│ Zay Jones   ┆ 2025   ┆ REG        ┆ 7    ┆ … ┆ 6.73       ┆ 5.4        ┆ 1.97       ┆ 3.3        │
│ Zay Jones   ┆ 2025   ┆ REG        ┆ 10   ┆ … ┆ 8.13       ┆ 6.06       ┆ 8.13       ┆ 6.06       │
└─────────────┴────────┴────────────┴──────┴───┴────────────┴────────────┴────────────┴────────────┘

In [19]:
dataset = (
    baseline_prediction_clean.select([
        'player_display_name',
        'season',
        'week',
        'team',
        'opponent_team',
        'prev_rolling_3_ppr',
        'prev_rolling_3_targets',
        'prev_rolling_3_receptions',
        'prev_rolling_3_receiving_yards',
        'prev_season_avg_ppr',
        'prev_defense_wr_yds_allowed_avg',
        'prev_defense_wr_ppr_allowed_avg',
        'calculated_ppr',
        'absolute_error',
        'season_avg_error'
    ])
)

dataset = dataset.filter(
    (pl.col("prev_rolling_3_ppr").is_not_null()) & 
    (pl.col("prev_rolling_3_targets").is_not_null()) & 
    (pl.col("prev_rolling_3_receptions").is_not_null()) & 
    (pl.col("prev_rolling_3_receiving_yards").is_not_null()) & 
    (pl.col("prev_season_avg_ppr").is_not_null()) & 
    (pl.col("prev_defense_wr_yds_allowed_avg").is_not_null()) & 
    (pl.col("prev_defense_wr_ppr_allowed_avg").is_not_null()) & 
    (pl.col("calculated_ppr").is_not_null())
)

dataset

shape: (10_301, 15)
┌──────────────┬────────┬──────┬──────┬───┬──────────────┬─────────────┬─────────────┬─────────────┐
│ player_displ ┆ season ┆ week ┆ team ┆ … ┆ prev_defense ┆ calculated_ ┆ absolute_er ┆ season_avg_ │
│ ay_name      ┆ ---    ┆ ---  ┆ ---  ┆   ┆ _wr_ppr_allo ┆ ppr         ┆ ror         ┆ error       │
│ ---          ┆ i32    ┆ i32  ┆ str  ┆   ┆ wed_av…      ┆ ---         ┆ ---         ┆ ---         │
│ str          ┆        ┆      ┆      ┆   ┆ ---          ┆ f64         ┆ f64         ┆ f64         │
│              ┆        ┆      ┆      ┆   ┆ f64          ┆             ┆             ┆             │
╞══════════════╪════════╪══════╪══════╪═══╪══════════════╪═════════════╪═════════════╪═════════════╡
│ A.J. Brown   ┆ 2021   ┆ 5    ┆ TEN  ┆ … ┆ 40.88        ┆ 6.8         ┆ 0.7         ┆ 0.7         │
│ A.J. Brown   ┆ 2021   ┆ 6    ┆ TEN  ┆ … ┆ 26.62        ┆ 16.1        ┆ 11.3        ┆ 8.78        │
│ A.J. Brown   ┆ 2021   ┆ 7    ┆ TEN  ┆ … ┆ 33.08        ┆ 27.3        ┆ 19.57       ┆ 18.22       │
│ A.J. Brown   ┆ 2021   ┆ 8    ┆ TEN  ┆ … ┆ 38.4         ┆ 31.5        ┆ 14.77       ┆ 19.38       │
│ A.J. Brown   ┆ 2021   ┆ 9    ┆ TEN  ┆ … ┆ 36.88        ┆ 9.2         ┆ 15.77       ┆ 5.69        │
│ …            ┆ …      ┆ …    ┆ …    ┆ … ┆ …            ┆ …           ┆ …           ┆ …           │
│ Zay Jones    ┆ 2025   ┆ 3    ┆ ARI  ┆ … ┆ 30.7         ┆ 4.5         ┆ 0.2         ┆ 3.1         │
│ Zay Jones    ┆ 2025   ┆ 5    ┆ ARI  ┆ … ┆ 38.7         ┆ 2.8         ┆ 2.03        ┆ 0.15        │
│ Zay Jones    ┆ 2025   ┆ 6    ┆ ARI  ┆ … ┆ 38.02        ┆ 12.9        ┆ 10.0        ┆ 10.0        │
│ Zay Jones    ┆ 2025   ┆ 7    ┆ ARI  ┆ … ┆ 33.42        ┆ 8.7         ┆ 1.97        ┆ 3.3         │
│ Zay Jones    ┆ 2025   ┆ 10   ┆ ARI  ┆ … ┆ 29.04        ┆ 0.0         ┆ 8.13        ┆ 6.06        │
└──────────────┴────────┴──────┴──────┴───┴──────────────┴─────────────┴─────────────┴─────────────┘

In [20]:
mean_abs_error = dataset.filter(pl.col("season") == 2025).select(
    pl.col("absolute_error").mean().round(2).alias("mean_absolute_error")
)
mean_abs_error

shape: (1, 1)
┌─────────────────────┐
│ mean_absolute_error │
│ ---                 │
│ f64                 │
╞═════════════════════╡
│ 4.56                │
└─────────────────────┘

In [21]:
mean_season_avg_error = dataset.filter(pl.col("season") == 2025).select(
    pl.col("season_avg_error").mean().round(2).alias("mean_season_avg_error")
)
mean_season_avg_error

shape: (1, 1)
┌───────────────────────┐
│ mean_season_avg_error │
│ ---                   │
│ f64                   │
╞═══════════════════════╡
│ 4.45                  │
└───────────────────────┘

In [22]:
rmse_rolling = dataset.filter(pl.col("season") == 2025).select(
    (pl.col("absolute_error") ** 2).mean().sqrt().round(2).alias("rmse_rolling")
)
rmse_rolling

shape: (1, 1)
┌──────────────┐
│ rmse_rolling │
│ ---          │
│ f64          │
╞══════════════╡
│ 6.41         │
└──────────────┘

In [23]:
rmse_season_avg = dataset.filter(pl.col("season") == 2025).select(
    (pl.col("season_avg_error") ** 2).mean().sqrt().round(2).alias("rmse_season_avg")
)
rmse_season_avg

shape: (1, 1)
┌─────────────────┐
│ rmse_season_avg │
│ ---             │
│ f64             │
╞═════════════════╡
│ 6.27            │
└─────────────────┘

In [24]:
feature_columns = [
    "prev_rolling_3_ppr",
    "prev_rolling_3_targets",
    "prev_rolling_3_receptions",
    "prev_rolling_3_receiving_yards",
    "prev_season_avg_ppr",
    "prev_defense_wr_yds_allowed_avg",
    "prev_defense_wr_ppr_allowed_avg"
]

In [25]:
X_train = dataset.filter(pl.col("season") < 2025).select(feature_columns).to_numpy()

X_test = dataset.filter(pl.col("season") == 2025).select(feature_columns).to_numpy()

y_train = dataset.filter(pl.col("season") < 2025).select('calculated_ppr').to_numpy().ravel()
y_test = dataset.filter(pl.col("season") == 2025).select('calculated_ppr').to_numpy().ravel()

model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
mae = mean_absolute_error(y_test, y_pred)
print(f"Mean Absolute Error: {mae}")
rmse = root_mean_squared_error(y_test, y_pred)
print(f"Root Mean Squared Error: {rmse}")

Mean Absolute Error: 4.39051946385784
Root Mean Squared Error: 5.997226647061871

In [26]:
random_forest = RandomForestRegressor(n_estimators=200, random_state=42, min_samples_leaf=5)

random_forest.fit(X_train, y_train)

rf_y_pred = random_forest.predict(X_test)
rf_mae = mean_absolute_error(y_test, rf_y_pred)
rf_rmse = root_mean_squared_error(y_test, rf_y_pred)
print(f"Random Forest Mean Absolute Error: {rf_mae}")
print(f"Random Forest Root Mean Squared Error: {rf_rmse}")

Random Forest Mean Absolute Error: 4.453435033896652
Random Forest Root Mean Squared Error: 6.1033405509329

In [27]:
test_results = (
    dataset
    .filter(pl.col("season") == 2025)
    .with_columns(
        pl.Series("linear_regression_prediction", y_pred),
        pl.Series("random_forest_prediction", rf_y_pred)
    )
)

test_results = test_results.with_columns(
    (pl.col("linear_regression_prediction") - pl.col("calculated_ppr"))
    .abs()
    .round(2)
    .alias("linear_regression_absolute_error"),

    (pl.col("prev_rolling_3_ppr") - pl.col("calculated_ppr"))
    .abs()
    .round(2)
    .alias("rolling_baseline_absolute_error"),

    (pl.col("prev_season_avg_ppr") - pl.col("calculated_ppr"))
    .abs()
    .round(2)
    .alias("season_baseline_absolute_error")
)

test_results.select([
    "player_display_name",
    "season",
    "week",
    "calculated_ppr",
    "linear_regression_prediction",
    "random_forest_prediction",
    "linear_regression_absolute_error",
    "rolling_baseline_absolute_error",
    "season_baseline_absolute_error",
]).sort("linear_regression_absolute_error", descending=True).head(20)

shape: (20, 9)
┌─────────────┬────────┬──────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ player_disp ┆ season ┆ week ┆ calculated ┆ … ┆ random_for ┆ linear_reg ┆ rolling_ba ┆ season_bas │
│ lay_name    ┆ ---    ┆ ---  ┆ _ppr       ┆   ┆ est_predic ┆ ression_ab ┆ seline_abs ┆ eline_abso │
│ ---         ┆ i32    ┆ i32  ┆ ---        ┆   ┆ tion       ┆ solute_err ┆ olute_erro ┆ lute_error │
│ str         ┆        ┆      ┆ f64        ┆   ┆ ---        ┆ …          ┆ …          ┆ ---        │
│             ┆        ┆      ┆            ┆   ┆ f64        ┆ ---        ┆ ---        ┆ f64        │
│             ┆        ┆      ┆            ┆   ┆            ┆ f64        ┆ f64        ┆            │
╞═════════════╪════════╪══════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ Tre Tucker  ┆ 2025   ┆ 3    ┆ 40.9       ┆ … ┆ 7.644366   ┆ 32.54      ┆ 33.0       ┆ 31.75      │
│ Amon-Ra St. ┆ 2025   ┆ 2    ┆ 39.2       ┆ … ┆ 10.943847  ┆ 28.82      ┆ 25.13      ┆ 30.7       │
│ Brown       ┆        ┆      ┆            ┆   ┆            ┆            ┆            ┆            │
│ Puka Nacua  ┆ 2025   ┆ 16   ┆ 46.5       ┆ … ┆ 19.612181  ┆ 27.6       ┆ 20.9       ┆ 24.44      │
│ Amon-Ra St. ┆ 2025   ┆ 15   ┆ 41.4       ┆ … ┆ 13.225678  ┆ 26.6       ┆ 26.37      ┆ 23.44      │
│ Brown       ┆        ┆      ┆            ┆   ┆            ┆            ┆            ┆            │
│ Michael     ┆ 2025   ┆ 11   ┆ 33.5       ┆ … ┆ 7.053234   ┆ 26.03      ┆ 25.67      ┆ 27.82      │
│ Wilson      ┆        ┆      ┆            ┆   ┆            ┆            ┆            ┆            │
│ …           ┆ …      ┆ …    ┆ …          ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ Dontayvion  ┆ 2025   ┆ 13   ┆ 28.0       ┆ … ┆ 6.879016   ┆ 21.64      ┆ 23.03      ┆ 23.41      │
│ Wicks       ┆        ┆      ┆            ┆   ┆            ┆            ┆            ┆            │
│ George      ┆ 2025   ┆ 4    ┆ 33.4       ┆ … ┆ 11.597009  ┆ 21.36      ┆ 19.53      ┆ 19.53      │
│ Pickens     ┆        ┆      ┆            ┆   ┆            ┆            ┆            ┆            │
│ Alec Pierce ┆ 2025   ┆ 18   ┆ 29.2       ┆ … ┆ 7.700851   ┆ 21.12      ┆ 20.13      ┆ 18.19      │
│ Tetairoa    ┆ 2025   ┆ 11   ┆ 33.0       ┆ … ┆ 11.759169  ┆ 20.66      ┆ 20.83      ┆ 21.02      │
│ McMillan    ┆        ┆      ┆            ┆   ┆            ┆            ┆            ┆            │
│ Tee Higgins ┆ 2025   ┆ 9    ┆ 31.1       ┆ … ┆ 9.317129   ┆ 20.54      ┆ 16.37      ┆ 20.48      │
└─────────────┴────────┴──────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [28]:
test_results = test_results.with_columns(
    pl.Series("random_forest_prediction", rf_y_pred)
)

test_results = test_results.with_columns(
    (pl.col("random_forest_prediction") - pl.col("calculated_ppr"))
    .round(2)
    .alias("random_forest_signed_error"),

    (pl.col("random_forest_prediction") - pl.col("calculated_ppr"))
    .abs()
    .round(2)
    .alias("random_forest_absolute_error"),
)

test_results.select([
    "player_display_name",
    "season",
    "week",
    "calculated_ppr",
    "linear_regression_prediction",
    "linear_regression_absolute_error",
    "random_forest_prediction",
    "random_forest_absolute_error",
    "random_forest_signed_error",
]).sort("random_forest_absolute_error", descending=True).head(20)

shape: (20, 9)
┌─────────────┬────────┬──────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ player_disp ┆ season ┆ week ┆ calculated ┆ … ┆ linear_reg ┆ random_for ┆ random_for ┆ random_for │
│ lay_name    ┆ ---    ┆ ---  ┆ _ppr       ┆   ┆ ression_ab ┆ est_predic ┆ est_absolu ┆ est_signed │
│ ---         ┆ i32    ┆ i32  ┆ ---        ┆   ┆ solute_err ┆ tion       ┆ te_error   ┆ _error     │
│ str         ┆        ┆      ┆ f64        ┆   ┆ …          ┆ ---        ┆ ---        ┆ ---        │
│             ┆        ┆      ┆            ┆   ┆ ---        ┆ f64        ┆ f64        ┆ f64        │
│             ┆        ┆      ┆            ┆   ┆ f64        ┆            ┆            ┆            │
╞═════════════╪════════╪══════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ Tre Tucker  ┆ 2025   ┆ 3    ┆ 40.9       ┆ … ┆ 32.54      ┆ 7.644366   ┆ 33.26      ┆ -33.26     │
│ Amon-Ra St. ┆ 2025   ┆ 2    ┆ 39.2       ┆ … ┆ 28.82      ┆ 10.943847  ┆ 28.26      ┆ -28.26     │
│ Brown       ┆        ┆      ┆            ┆   ┆            ┆            ┆            ┆            │
│ Amon-Ra St. ┆ 2025   ┆ 15   ┆ 41.4       ┆ … ┆ 26.6       ┆ 13.225678  ┆ 28.17      ┆ -28.17     │
│ Brown       ┆        ┆      ┆            ┆   ┆            ┆            ┆            ┆            │
│ Puka Nacua  ┆ 2025   ┆ 16   ┆ 46.5       ┆ … ┆ 27.6       ┆ 19.612181  ┆ 26.89      ┆ -26.89     │
│ Michael     ┆ 2025   ┆ 11   ┆ 33.5       ┆ … ┆ 26.03      ┆ 7.053234   ┆ 26.45      ┆ -26.45     │
│ Wilson      ┆        ┆      ┆            ┆   ┆            ┆            ┆            ┆            │
│ …           ┆ …      ┆ …    ┆ …          ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ Dontayvion  ┆ 2025   ┆ 13   ┆ 28.0       ┆ … ┆ 21.64      ┆ 6.879016   ┆ 21.12      ┆ -21.12     │
│ Wicks       ┆        ┆      ┆            ┆   ┆            ┆            ┆            ┆            │
│ Hunter      ┆ 2025   ┆ 2    ┆ 23.8       ┆ … ┆ 19.68      ┆ 3.48919    ┆ 20.31      ┆ -20.31     │
│ Renfrow     ┆        ┆      ┆            ┆   ┆            ┆            ┆            ┆            │
│ Kayshon     ┆ 2025   ┆ 6    ┆ 26.3       ┆ … ┆ 19.43      ┆ 6.097215   ┆ 20.2       ┆ -20.2      │
│ Boutte      ┆        ┆      ┆            ┆   ┆            ┆            ┆            ┆            │
│ Drake       ┆ 2025   ┆ 9    ┆ 38.8       ┆ … ┆ 22.09      ┆ 18.870096  ┆ 19.93      ┆ -19.93     │
│ London      ┆        ┆      ┆            ┆   ┆            ┆            ┆            ┆            │
│ Xavier      ┆ 2025   ┆ 7    ┆ 24.2       ┆ … ┆ 18.37      ┆ 4.487094   ┆ 19.71      ┆ -19.71     │
│ Legette     ┆        ┆      ┆            ┆   ┆            ┆            ┆            ┆            │
└─────────────┴────────┴──────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [29]:
metrics_comparison = pl.DataFrame({
    "model": [
        "Rolling 3-game baseline",
        "Season-to-date baseline",
        "Linear Regression",
        "Random Forest",
    ],
    "mae": [
        mean_absolute_error(
            test_results["calculated_ppr"],
            test_results["prev_rolling_3_ppr"],
        ),
        mean_absolute_error(
            test_results["calculated_ppr"],
            test_results["prev_season_avg_ppr"],
        ),
        mean_absolute_error(y_test, y_pred),
        mean_absolute_error(y_test, rf_y_pred),
    ],
    "rmse": [
        root_mean_squared_error(
            test_results["calculated_ppr"],
            test_results["prev_rolling_3_ppr"],
        ),
        root_mean_squared_error(
            test_results["calculated_ppr"],
            test_results["prev_season_avg_ppr"],
        ),
        root_mean_squared_error(y_test, y_pred),
        root_mean_squared_error(y_test, rf_y_pred),
    ],
}).with_columns(
    pl.col("mae").round(2),
    pl.col("rmse").round(2),
)

metrics_comparison

shape: (4, 3)
┌─────────────────────────┬──────┬──────┐
│ model                   ┆ mae  ┆ rmse │
│ ---                     ┆ ---  ┆ ---  │
│ str                     ┆ f64  ┆ f64  │
╞═════════════════════════╪══════╪══════╡
│ Rolling 3-game baseline ┆ 4.56 ┆ 6.41 │
│ Season-to-date baseline ┆ 4.45 ┆ 6.27 │
│ Linear Regression       ┆ 4.39 ┆ 6.0  │
│ Random Forest           ┆ 4.45 ┆ 6.1  │
└─────────────────────────┴──────┴──────┘

Random Forest was tested as a comparison model using the same training and test split as Linear Regression. It performed worse than Linear Regression on the 2025 test season, so Linear Regression remains the preferred current model. This suggests that, with the current feature set, a more flexible model may be fitting noise rather than improving generalization.

In [30]:
feature_columns = [
    "prev_rolling_3_ppr",
    "prev_rolling_3_targets",
    "prev_rolling_3_receptions",
    "prev_rolling_3_receiving_yards",
    "prev_season_avg_ppr",
    "prev_defense_wr_yds_allowed_avg",
    "prev_defense_wr_ppr_allowed_avg"
]

coefficients = pl.DataFrame({
    "feature": feature_columns,
    "coefficient": model.coef_,
}).sort("coefficient", descending=True)

coefficients

shape: (7, 2)
┌─────────────────────────────────┬─────────────┐
│ feature                         ┆ coefficient │
│ ---                             ┆ ---         │
│ str                             ┆ f64         │
╞═════════════════════════════════╪═════════════╡
│ prev_rolling_3_targets          ┆ 0.50942     │
│ prev_season_avg_ppr             ┆ 0.4324      │
│ prev_rolling_3_receptions       ┆ 0.279975    │
│ prev_rolling_3_receiving_yards  ┆ 0.020165    │
│ prev_defense_wr_yds_allowed_av… ┆ 0.005671    │
│ prev_defense_wr_ppr_allowed_av… ┆ -0.009481   │
│ prev_rolling_3_ppr              ┆ -0.068328   │
└─────────────────────────────────┴─────────────┘

In [31]:
rf_feature_importance = pl.DataFrame({
    "feature": feature_columns,
    "importance": random_forest.feature_importances_,
}).sort("importance", descending=True)

rf_feature_importance

shape: (7, 2)
┌─────────────────────────────────┬────────────┐
│ feature                         ┆ importance │
│ ---                             ┆ ---        │
│ str                             ┆ f64        │
╞═════════════════════════════════╪════════════╡
│ prev_season_avg_ppr             ┆ 0.500943   │
│ prev_rolling_3_targets          ┆ 0.112154   │
│ prev_defense_wr_ppr_allowed_av… ┆ 0.088428   │
│ prev_defense_wr_yds_allowed_av… ┆ 0.08638    │
│ prev_rolling_3_ppr              ┆ 0.085967   │
│ prev_rolling_3_receiving_yards  ┆ 0.083719   │
│ prev_rolling_3_receptions       ┆ 0.04241    │
└─────────────────────────────────┴────────────┘

Opponent defensive strength features were tested using prior season-to-date WR receiving yards allowed and prior season-to-date WR PPR allowed. These features were prediction-safe because they were shifted before joining to player-week rows.

The defensive features produced only a very small change in Linear Regression performance. Linear Regression remained the best model, but the improvement over the baselines is still modest. The coefficients for both defensive features were small, suggesting that player-level usage and production features are still carrying most of the signal.