In [2]:
import pandas as pd
import nflreadpy as nfl
import polars as pl
import matplotlib.pyplot as plt
import sys
from pathlib import Path
import sklearn
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error

In [3]:
weekly = nfl.load_player_stats([2021, 2022, 2023, 2024, 2025])
weekly

shape: (94_848, 150)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ player_id ┆ player_na ┆ player_di ┆ position ┆ … ┆ pt_return ┆ pt_net_ya ┆ fantasy_p ┆ fantasy_p │
│ ---       ┆ me        ┆ splay_nam ┆ ---      ┆   ┆ _tds      ┆ rds       ┆ oints     ┆ oints_ppr │
│ str       ┆ ---       ┆ e         ┆ str      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│           ┆ str       ┆ ---       ┆          ┆   ┆ i32       ┆ i32       ┆ f64       ┆ f64       │
│           ┆           ┆ str       ┆          ┆   ┆           ┆           ┆           ┆           │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 00-001959 ┆ T.Brady   ┆ Tom Brady ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 27.16     ┆ 27.16     │
│ 6         ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-002282 ┆ A.Lee     ┆ Andy Lee  ┆ P        ┆ … ┆ 0         ┆ 124       ┆ 0.0       ┆ 0.0       │
│ 4         ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-002292 ┆ B.Roethli ┆ Ben Roeth ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 12.02     ┆ 12.02     │
│ 4         ┆ sberger   ┆ lisberger ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-002325 ┆ R.Gould   ┆ Robbie    ┆ K        ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 2         ┆           ┆ Gould     ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-002345 ┆ Aa.Rodger ┆ Aaron     ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 1.32      ┆ 1.32      │
│ 9         ┆ s         ┆ Rodgers   ┆          ┆   ┆           ┆           ┆           ┆           │
│ …         ┆ …         ┆ …         ┆ …        ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 00-004069 ┆ W.Campbel ┆ Will      ┆ OT       ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 9         ┆ l         ┆ Campbell  ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-004071 ┆ C.Woodson ┆ Craig     ┆ SAF      ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 6         ┆           ┆ Woodson   ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-004073 ┆ N.Emmanwo ┆ Nick      ┆ SAF      ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 3         ┆ ri        ┆ Emmanwori ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-004073 ┆ T.Henders ┆ TreVeyon  ┆ RB       ┆ … ┆ 0         ┆ 0         ┆ 4.5       ┆ 7.5       │
│ 4         ┆ on        ┆ Henderson ┆          ┆   ┆           ┆           ┆           ┆           │
│ null      ┆ null      ┆ null      ┆ null     ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [6]:
receivers = weekly.filter((weekly['position'] == 'WR') & (weekly['season_type'] == 'REG'))
receiving_stats = receivers.select([
    "player_display_name",
    "season",
    "season_type",
    "week",
    "team",
    "opponent_team",
    "receptions",
    "targets",
    "receiving_yards",
    "receiving_tds",
    "receiving_fumbles_lost",
    "receiving_2pt_conversions",
    "special_teams_tds",
    "rushing_yards",
    "rushing_tds",
    "rushing_fumbles_lost",
    "rushing_2pt_conversions",
    "fantasy_points_ppr",
])

receiving_stats

shape: (12_298, 18)
┌─────────────┬────────┬────────────┬──────┬───┬────────────┬────────────┬────────────┬────────────┐
│ player_disp ┆ season ┆ season_typ ┆ week ┆ … ┆ rushing_td ┆ rushing_fu ┆ rushing_2p ┆ fantasy_po │
│ lay_name    ┆ ---    ┆ e          ┆ ---  ┆   ┆ s          ┆ mbles_lost ┆ t_conversi ┆ ints_ppr   │
│ ---         ┆ i32    ┆ ---        ┆ i32  ┆   ┆ ---        ┆ ---        ┆ ons        ┆ ---        │
│ str         ┆        ┆ str        ┆      ┆   ┆ i32        ┆ i32        ┆ ---        ┆ f64        │
│             ┆        ┆            ┆      ┆   ┆            ┆            ┆ i32        ┆            │
╞═════════════╪════════╪════════════╪══════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ Danny       ┆ 2021   ┆ REG        ┆ 1    ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 14.4       │
│ Amendola    ┆        ┆            ┆      ┆   ┆            ┆            ┆            ┆            │
│ DeSean      ┆ 2021   ┆ REG        ┆ 1    ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 4.1        │
│ Jackson     ┆        ┆            ┆      ┆   ┆            ┆            ┆            ┆            │
│ Emmanuel    ┆ 2021   ┆ REG        ┆ 1    ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 9.2        │
│ Sanders     ┆        ┆            ┆      ┆   ┆            ┆            ┆            ┆            │
│ Andre       ┆ 2021   ┆ REG        ┆ 1    ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 0.0        │
│ Roberts     ┆        ┆            ┆      ┆   ┆            ┆            ┆            ┆            │
│ Antonio     ┆ 2021   ┆ REG        ┆ 1    ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 23.7       │
│ Brown       ┆        ┆            ┆      ┆   ┆            ┆            ┆            ┆            │
│ …           ┆ …      ┆ …          ┆ …    ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ Chimere     ┆ 2025   ┆ REG        ┆ 18   ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 5.7        │
│ Dike        ┆        ┆            ┆      ┆   ┆            ┆            ┆            ┆            │
│ Tre Harris  ┆ 2025   ┆ REG        ┆ 18   ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 4.8        │
│ Jack Bech   ┆ 2025   ┆ REG        ┆ 18   ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 0.0        │
│ Luther      ┆ 2025   ┆ REG        ┆ 18   ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 7.5        │
│ Burden III  ┆        ┆            ┆      ┆   ┆            ┆            ┆            ┆            │
│ Isaiah Bond ┆ 2025   ┆ REG        ┆ 18   ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 2.7        │
└─────────────┴────────┴────────────┴──────┴───┴────────────┴────────────┴────────────┴────────────┘

In [7]:
project_root = Path.cwd().parent
sys.path.append(str(project_root))

from src.scoring import calculate_ppr

receiving_stats_ppr = calculate_ppr(receiving_stats)
receiving_stats_ppr

shape: (12_298, 19)
┌─────────────┬────────┬────────────┬──────┬───┬────────────┬────────────┬────────────┬────────────┐
│ player_disp ┆ season ┆ season_typ ┆ week ┆ … ┆ rushing_fu ┆ rushing_2p ┆ fantasy_po ┆ calculated │
│ lay_name    ┆ ---    ┆ e          ┆ ---  ┆   ┆ mbles_lost ┆ t_conversi ┆ ints_ppr   ┆ _ppr       │
│ ---         ┆ i32    ┆ ---        ┆ i32  ┆   ┆ ---        ┆ ons        ┆ ---        ┆ ---        │
│ str         ┆        ┆ str        ┆      ┆   ┆ i32        ┆ ---        ┆ f64        ┆ f64        │
│             ┆        ┆            ┆      ┆   ┆            ┆ i32        ┆            ┆            │
╞═════════════╪════════╪════════════╪══════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ Danny       ┆ 2021   ┆ REG        ┆ 1    ┆ … ┆ 0          ┆ 0          ┆ 14.4       ┆ 14.4       │
│ Amendola    ┆        ┆            ┆      ┆   ┆            ┆            ┆            ┆            │
│ DeSean      ┆ 2021   ┆ REG        ┆ 1    ┆ … ┆ 0          ┆ 0          ┆ 4.1        ┆ 4.1        │
│ Jackson     ┆        ┆            ┆      ┆   ┆            ┆            ┆            ┆            │
│ Emmanuel    ┆ 2021   ┆ REG        ┆ 1    ┆ … ┆ 0          ┆ 0          ┆ 9.2        ┆ 9.2        │
│ Sanders     ┆        ┆            ┆      ┆   ┆            ┆            ┆            ┆            │
│ Andre       ┆ 2021   ┆ REG        ┆ 1    ┆ … ┆ 0          ┆ 0          ┆ 0.0        ┆ 0.0        │
│ Roberts     ┆        ┆            ┆      ┆   ┆            ┆            ┆            ┆            │
│ Antonio     ┆ 2021   ┆ REG        ┆ 1    ┆ … ┆ 0          ┆ 0          ┆ 23.7       ┆ 23.7       │
│ Brown       ┆        ┆            ┆      ┆   ┆            ┆            ┆            ┆            │
│ …           ┆ …      ┆ …          ┆ …    ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ Chimere     ┆ 2025   ┆ REG        ┆ 18   ┆ … ┆ 0          ┆ 0          ┆ 5.7        ┆ 5.7        │
│ Dike        ┆        ┆            ┆      ┆   ┆            ┆            ┆            ┆            │
│ Tre Harris  ┆ 2025   ┆ REG        ┆ 18   ┆ … ┆ 0          ┆ 0          ┆ 4.8        ┆ 4.8        │
│ Jack Bech   ┆ 2025   ┆ REG        ┆ 18   ┆ … ┆ 0          ┆ 0          ┆ 0.0        ┆ 0.0        │
│ Luther      ┆ 2025   ┆ REG        ┆ 18   ┆ … ┆ 0          ┆ 0          ┆ 7.5        ┆ 7.5        │
│ Burden III  ┆        ┆            ┆      ┆   ┆            ┆            ┆            ┆            │
│ Isaiah Bond ┆ 2025   ┆ REG        ┆ 18   ┆ … ┆ 0          ┆ 0          ┆ 2.7        ┆ 2.7        │
└─────────────┴────────┴────────────┴──────┴───┴────────────┴────────────┴────────────┴────────────┘

In [31]:
player_prediction_features = (
    receiving_stats_ppr
    .sort(["player_display_name", "season", "week"])
    .with_columns(
        pl.col("calculated_ppr")
        .shift(1)
        .rolling_mean(window_size=3, min_samples=3)
        .round(2)
        .over(["player_display_name"])
        .alias("prev_rolling_3_ppr"),

        pl.col("targets")
        .shift(1)
        .rolling_mean(window_size=3, min_samples=3)
        .round(2)
        .over(["player_display_name"])
        .alias("prev_rolling_3_targets"),

        pl.col("receptions")
        .shift(1)
        .rolling_mean(window_size=3, min_samples=3)
        .round(2)
        .over(["player_display_name"])
        .alias("prev_rolling_3_receptions"),

        pl.col("receiving_yards")
        .shift(1)
        .rolling_mean(window_size=3, min_samples=3)
        .round(2)
        .over(["player_display_name"])
        .alias("prev_rolling_3_receiving_yards")
    )
)

player_prediction_features

shape: (12_298, 23)
┌─────────────┬────────┬────────────┬──────┬───┬────────────┬────────────┬────────────┬────────────┐
│ player_disp ┆ season ┆ season_typ ┆ week ┆ … ┆ prev_rolli ┆ prev_rolli ┆ prev_rolli ┆ prev_rolli │
│ lay_name    ┆ ---    ┆ e          ┆ ---  ┆   ┆ ng_3_ppr   ┆ ng_3_targe ┆ ng_3_recep ┆ ng_3_recei │
│ ---         ┆ i32    ┆ ---        ┆ i32  ┆   ┆ ---        ┆ ts         ┆ tions      ┆ ving_yards │
│ str         ┆        ┆ str        ┆      ┆   ┆ f64        ┆ ---        ┆ ---        ┆ ---        │
│             ┆        ┆            ┆      ┆   ┆            ┆ f64        ┆ f64        ┆ f64        │
╞═════════════╪════════╪════════════╪══════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ A.J. Brown  ┆ 2021   ┆ REG        ┆ 1    ┆ … ┆ null       ┆ null       ┆ null       ┆ null       │
│ A.J. Brown  ┆ 2021   ┆ REG        ┆ 2    ┆ … ┆ null       ┆ null       ┆ null       ┆ null       │
│ A.J. Brown  ┆ 2021   ┆ REG        ┆ 3    ┆ … ┆ null       ┆ null       ┆ null       ┆ null       │
│ A.J. Brown  ┆ 2021   ┆ REG        ┆ 5    ┆ … ┆ 7.5        ┆ 6.33       ┆ 2.33       ┆ 30.67      │
│ A.J. Brown  ┆ 2021   ┆ REG        ┆ 6    ┆ … ┆ 4.8        ┆ 5.67       ┆ 2.0        ┆ 27.0       │
│ …           ┆ …      ┆ …          ┆ …    ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ Zay Jones   ┆ 2025   ┆ REG        ┆ 3    ┆ … ┆ 4.3        ┆ 2.33       ┆ 2.0        ┆ 23.0       │
│ Zay Jones   ┆ 2025   ┆ REG        ┆ 5    ┆ … ┆ 4.83       ┆ 3.0        ┆ 2.33       ┆ 25.0       │
│ Zay Jones   ┆ 2025   ┆ REG        ┆ 6    ┆ … ┆ 2.9        ┆ 2.33       ┆ 1.67       ┆ 12.33      │
│ Zay Jones   ┆ 2025   ┆ REG        ┆ 7    ┆ … ┆ 6.73       ┆ 4.67       ┆ 3.0        ┆ 37.33      │
│ Zay Jones   ┆ 2025   ┆ REG        ┆ 10   ┆ … ┆ 8.13       ┆ 4.33       ┆ 3.0        ┆ 51.33      │
└─────────────┴────────┴────────────┴──────┴───┴────────────┴────────────┴────────────┴────────────┘

In [38]:
with pl.Config(tbl_rows=-1):
    print(player_prediction_features.filter(pl.col("player_display_name") == 'CeeDee Lamb').head(20))
# player_prediction_features.filter(
#     pl.col("player_display_name") == "A.J. Brown"
# ).select([
#     "player_display_name",
#     "season",
#     "week",
#     "calculated_ppr",
#     "prev_rolling_3_ppr",
#     "targets",
#     "prev_rolling_3_targets",
#     "receptions",
#     "prev_rolling_3_receptions",
#     "receiving_yards",
#     "prev_rolling_3_receiving_yards"
# ]).sort(["season", "week"])

shape: (20, 23)
┌─────────────┬────────┬────────────┬──────┬───┬────────────┬────────────┬────────────┬────────────┐
│ player_disp ┆ season ┆ season_typ ┆ week ┆ … ┆ prev_rolli ┆ prev_rolli ┆ prev_rolli ┆ prev_rolli │
│ lay_name    ┆ ---    ┆ e          ┆ ---  ┆   ┆ ng_3_ppr   ┆ ng_3_targe ┆ ng_3_recep ┆ ng_3_recei │
│ ---         ┆ i32    ┆ ---        ┆ i32  ┆   ┆ ---        ┆ ts         ┆ tions      ┆ ving_yards │
│ str         ┆        ┆ str        ┆      ┆   ┆ f64        ┆ ---        ┆ ---        ┆ ---        │
│             ┆        ┆            ┆      ┆   ┆            ┆ f64        ┆ f64        ┆ f64        │
╞═════════════╪════════╪════════════╪══════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ CeeDee Lamb ┆ 2021   ┆ REG        ┆ 1    ┆ … ┆ null       ┆ null       ┆ null       ┆ null       │
│ CeeDee Lamb ┆ 2021   ┆ REG        ┆ 2    ┆ … ┆ null       ┆ null       ┆ null       ┆ null       │
│ CeeDee Lamb ┆ 2021   ┆ REG        ┆ 3    ┆ … ┆ null       ┆ null       ┆ null       ┆ null       │
│ CeeDee Lamb ┆ 2021   ┆ REG        ┆ 4    ┆ … ┆ 16.77      ┆ 9.0        ┆ 6.0        ┆ 83.67      │
│ CeeDee Lamb ┆ 2021   ┆ REG        ┆ 5    ┆ … ┆ 10.07      ┆ 5.67       ┆ 4.33       ┆ 53.33      │
│ CeeDee Lamb ┆ 2021   ┆ REG        ┆ 6    ┆ … ┆ 10.53      ┆ 4.67       ┆ 3.0        ┆ 54.33      │
│ CeeDee Lamb ┆ 2021   ┆ REG        ┆ 8    ┆ … ┆ 19.4       ┆ 7.33       ┆ 5.0        ┆ 82.0       │
│ CeeDee Lamb ┆ 2021   ┆ REG        ┆ 9    ┆ … ┆ 24.03      ┆ 8.33       ┆ 6.33       ┆ 115.0      │
│ CeeDee Lamb ┆ 2021   ┆ REG        ┆ 10   ┆ … ┆ 19.2       ┆ 9.33       ┆ 5.67       ┆ 94.67      │
│ CeeDee Lamb ┆ 2021   ┆ REG        ┆ 11   ┆ … ┆ 16.7       ┆ 8.0        ┆ 4.67       ┆ 76.33      │
│ CeeDee Lamb ┆ 2021   ┆ REG        ┆ 13   ┆ … ┆ 12.43      ┆ 6.67       ┆ 3.67       ┆ 43.67      │
│ CeeDee Lamb ┆ 2021   ┆ REG        ┆ 14   ┆ … ┆ 17.4       ┆ 8.0        ┆ 5.33       ┆ 65.67      │
│ CeeDee Lamb ┆ 2021   ┆ REG        ┆ 15   ┆ … ┆ 12.73      ┆ 9.0        ┆ 5.67       ┆ 54.67      │
│ CeeDee Lamb ┆ 2021   ┆ REG        ┆ 16   ┆ … ┆ 14.93      ┆ 10.67      ┆ 6.67       ┆ 66.67      │
│ CeeDee Lamb ┆ 2021   ┆ REG        ┆ 17   ┆ … ┆ 12.0       ┆ 8.0        ┆ 5.67       ┆ 59.0       │
│ CeeDee Lamb ┆ 2021   ┆ REG        ┆ 18   ┆ … ┆ 9.83       ┆ 6.0        ┆ 4.33       ┆ 55.67      │
│ CeeDee Lamb ┆ 2022   ┆ REG        ┆ 1    ┆ … ┆ 8.33       ┆ 3.67       ┆ 3.0        ┆ 54.0       │
│ CeeDee Lamb ┆ 2022   ┆ REG        ┆ 2    ┆ … ┆ 6.5        ┆ 5.67       ┆ 2.33       ┆ 41.67      │
│ CeeDee Lamb ┆ 2022   ┆ REG        ┆ 3    ┆ … ┆ 8.83       ┆ 8.0        ┆ 3.67       ┆ 49.67      │
│ CeeDee Lamb ┆ 2022   ┆ REG        ┆ 4    ┆ … ┆ 14.23      ┆ 11.33      ┆ 5.67       ┆ 63.67      │
└─────────────┴────────┴────────────┴──────┴───┴────────────┴────────────┴────────────┴────────────┘

In [17]:
player_prediction_features = (
    player_prediction_features
    .sort(["player_display_name", "season", "week"])
    .with_columns(
        (
            pl.col("calculated_ppr").shift(1).cum_sum().over(["player_display_name", "season"])
            /
            pl.col("calculated_ppr").shift(1).cum_count().over(["player_display_name", "season"])
        )
        .round(2)
        .alias("prev_season_avg_ppr")
    )
)

player_prediction_features

shape: (12_298, 24)
┌─────────────┬────────┬────────────┬──────┬───┬────────────┬────────────┬────────────┬────────────┐
│ player_disp ┆ season ┆ season_typ ┆ week ┆ … ┆ prev_rolli ┆ prev_rolli ┆ prev_rolli ┆ prev_seaso │
│ lay_name    ┆ ---    ┆ e          ┆ ---  ┆   ┆ ng_3_targe ┆ ng_3_recep ┆ ng_3_recei ┆ n_avg_ppr  │
│ ---         ┆ i32    ┆ ---        ┆ i32  ┆   ┆ ts         ┆ tions      ┆ ving_yards ┆ ---        │
│ str         ┆        ┆ str        ┆      ┆   ┆ ---        ┆ ---        ┆ ---        ┆ f64        │
│             ┆        ┆            ┆      ┆   ┆ f64        ┆ f64        ┆ f64        ┆            │
╞═════════════╪════════╪════════════╪══════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ A.J. Brown  ┆ 2021   ┆ REG        ┆ 1    ┆ … ┆ null       ┆ null       ┆ null       ┆ null       │
│ A.J. Brown  ┆ 2021   ┆ REG        ┆ 2    ┆ … ┆ null       ┆ null       ┆ null       ┆ 14.9       │
│ A.J. Brown  ┆ 2021   ┆ REG        ┆ 3    ┆ … ┆ null       ┆ null       ┆ null       ┆ 11.1       │
│ A.J. Brown  ┆ 2021   ┆ REG        ┆ 5    ┆ … ┆ 6.33       ┆ 2.33       ┆ 30.67      ┆ 7.5        │
│ A.J. Brown  ┆ 2021   ┆ REG        ┆ 6    ┆ … ┆ 5.67       ┆ 2.0        ┆ 27.0       ┆ 7.32       │
│ …           ┆ …      ┆ …          ┆ …    ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ Zay Jones   ┆ 2025   ┆ REG        ┆ 3    ┆ … ┆ null       ┆ null       ┆ null       ┆ 1.4        │
│ Zay Jones   ┆ 2025   ┆ REG        ┆ 5    ┆ … ┆ null       ┆ null       ┆ null       ┆ 2.95       │
│ Zay Jones   ┆ 2025   ┆ REG        ┆ 6    ┆ … ┆ 2.33       ┆ 1.67       ┆ 12.33      ┆ 2.9        │
│ Zay Jones   ┆ 2025   ┆ REG        ┆ 7    ┆ … ┆ 4.67       ┆ 3.0        ┆ 37.33      ┆ 5.4        │
│ Zay Jones   ┆ 2025   ┆ REG        ┆ 10   ┆ … ┆ 4.33       ┆ 3.0        ┆ 51.33      ┆ 6.06       │
└─────────────┴────────┴────────────┴──────┴───┴────────────┴────────────┴────────────┴────────────┘

In [18]:
player_prediction_features.filter(
    pl.col("player_display_name") == "A.J. Brown"
).select([
    "player_display_name",
    "season",
    "week",
    "calculated_ppr",
    "prev_season_avg_ppr"
]).sort(["season", "week"])

shape: (75, 5)
┌─────────────────────┬────────┬──────┬────────────────┬─────────────────────┐
│ player_display_name ┆ season ┆ week ┆ calculated_ppr ┆ prev_season_avg_ppr │
│ ---                 ┆ ---    ┆ ---  ┆ ---            ┆ ---                 │
│ str                 ┆ i32    ┆ i32  ┆ f64            ┆ f64                 │
╞═════════════════════╪════════╪══════╪════════════════╪═════════════════════╡
│ A.J. Brown          ┆ 2021   ┆ 1    ┆ 14.9           ┆ null                │
│ A.J. Brown          ┆ 2021   ┆ 2    ┆ 7.3            ┆ 14.9                │
│ A.J. Brown          ┆ 2021   ┆ 3    ┆ 0.3            ┆ 11.1                │
│ A.J. Brown          ┆ 2021   ┆ 5    ┆ 6.8            ┆ 7.5                 │
│ A.J. Brown          ┆ 2021   ┆ 6    ┆ 16.1           ┆ 7.32                │
│ …                   ┆ …      ┆ …    ┆ …              ┆ …                   │
│ A.J. Brown          ┆ 2025   ┆ 13   ┆ 35.2           ┆ 12.67               │
│ A.J. Brown          ┆ 2025   ┆ 14   ┆ 16.0           ┆ 14.72               │
│ A.J. Brown          ┆ 2025   ┆ 15   ┆ 12.1           ┆ 14.82               │
│ A.J. Brown          ┆ 2025   ┆ 16   ┆ 18.5           ┆ 14.62               │
│ A.J. Brown          ┆ 2025   ┆ 17   ┆ 11.8           ┆ 14.89               │
└─────────────────────┴────────┴──────┴────────────────┴─────────────────────┘

In [19]:
baseline_predictions = (
    player_prediction_features
    .with_columns(
        pl.col("prev_rolling_3_ppr").alias("baseline_prediction"),
        pl.col("prev_season_avg_ppr").alias("baseline_prediction_season")
    )
)

baseline_prediction_clean = baseline_predictions.filter(
    (pl.col("prev_rolling_3_ppr").is_not_null())
)

baseline_prediction_clean = baseline_prediction_clean.with_columns(
    (pl.col("baseline_prediction") - pl.col("calculated_ppr"))
    .abs()
    .round(2)
    .alias("absolute_error"),

    (pl.col("calculated_ppr") - pl.col("prev_season_avg_ppr"))
    .abs()
    .round(2)
    .alias("season_avg_error"),
)

baseline_prediction_clean

shape: (8_944, 28)
┌─────────────┬────────┬────────────┬──────┬───┬────────────┬────────────┬────────────┬────────────┐
│ player_disp ┆ season ┆ season_typ ┆ week ┆ … ┆ baseline_p ┆ baseline_p ┆ absolute_e ┆ season_avg │
│ lay_name    ┆ ---    ┆ e          ┆ ---  ┆   ┆ rediction  ┆ rediction_ ┆ rror       ┆ _error     │
│ ---         ┆ i32    ┆ ---        ┆ i32  ┆   ┆ ---        ┆ season     ┆ ---        ┆ ---        │
│ str         ┆        ┆ str        ┆      ┆   ┆ f64        ┆ ---        ┆ f64        ┆ f64        │
│             ┆        ┆            ┆      ┆   ┆            ┆ f64        ┆            ┆            │
╞═════════════╪════════╪════════════╪══════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ A.J. Brown  ┆ 2021   ┆ REG        ┆ 5    ┆ … ┆ 7.5        ┆ 7.5        ┆ 0.7        ┆ 0.7        │
│ A.J. Brown  ┆ 2021   ┆ REG        ┆ 6    ┆ … ┆ 4.8        ┆ 7.32       ┆ 11.3       ┆ 8.78       │
│ A.J. Brown  ┆ 2021   ┆ REG        ┆ 7    ┆ … ┆ 7.73       ┆ 9.08       ┆ 19.57      ┆ 18.22      │
│ A.J. Brown  ┆ 2021   ┆ REG        ┆ 8    ┆ … ┆ 16.73      ┆ 12.12      ┆ 14.77      ┆ 19.38      │
│ A.J. Brown  ┆ 2021   ┆ REG        ┆ 9    ┆ … ┆ 24.97      ┆ 14.89      ┆ 15.77      ┆ 5.69       │
│ …           ┆ …      ┆ …          ┆ …    ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ Zay Jones   ┆ 2024   ┆ REG        ┆ 17   ┆ … ┆ 1.63       ┆ 1.22       ┆ 1.27       ┆ 1.68       │
│ Zay Jones   ┆ 2024   ┆ REG        ┆ 18   ┆ … ┆ 2.17       ┆ 1.56       ┆ 6.43       ┆ 7.04       │
│ Zay Jones   ┆ 2025   ┆ REG        ┆ 6    ┆ … ┆ 2.9        ┆ 2.9        ┆ 10.0       ┆ 10.0       │
│ Zay Jones   ┆ 2025   ┆ REG        ┆ 7    ┆ … ┆ 6.73       ┆ 5.4        ┆ 1.97       ┆ 3.3        │
│ Zay Jones   ┆ 2025   ┆ REG        ┆ 10   ┆ … ┆ 8.13       ┆ 6.06       ┆ 8.13       ┆ 6.06       │
└─────────────┴────────┴────────────┴──────┴───┴────────────┴────────────┴────────────┴────────────┘

In [39]:
mean_abs_error = baseline_prediction_clean.filter(pl.col("season") == 2025).select(
    pl.col("absolute_error").mean().round(2).alias("mean_absolute_error")
)
mean_abs_error

shape: (1, 1)
┌─────────────────────┐
│ mean_absolute_error │
│ ---                 │
│ f64                 │
╞═════════════════════╡
│ 4.58                │
└─────────────────────┘

In [40]:
mean_season_avg_error = baseline_prediction_clean.filter(pl.col("season") == 2025).select(
    pl.col("season_avg_error").mean().round(2).alias("mean_season_avg_error")
)
mean_season_avg_error

shape: (1, 1)
┌───────────────────────┐
│ mean_season_avg_error │
│ ---                   │
│ f64                   │
╞═══════════════════════╡
│ 4.4                   │
└───────────────────────┘

In [41]:
dataset = (
    baseline_prediction_clean.select([
        'player_display_name',
        'season',
        'week',
        'team',
        'opponent_team',
        'prev_rolling_3_ppr',
        'prev_rolling_3_targets',
        'prev_rolling_3_receptions',
        'prev_rolling_3_receiving_yards',
        'prev_season_avg_ppr',
        'calculated_ppr',
    ])
)

dataset = dataset.filter(
    (pl.col("prev_rolling_3_ppr").is_not_null()) & 
    (pl.col("prev_rolling_3_targets").is_not_null()) & 
    (pl.col("prev_rolling_3_receptions").is_not_null()) & 
    (pl.col("prev_rolling_3_receiving_yards").is_not_null()) & 
    (pl.col("prev_season_avg_ppr").is_not_null()) & 
    (pl.col("calculated_ppr").is_not_null())
)

dataset

shape: (8_944, 11)
┌──────────────┬────────┬──────┬──────┬───┬──────────────┬─────────────┬─────────────┬─────────────┐
│ player_displ ┆ season ┆ week ┆ team ┆ … ┆ prev_rolling ┆ prev_rollin ┆ prev_season ┆ calculated_ │
│ ay_name      ┆ ---    ┆ ---  ┆ ---  ┆   ┆ _3_reception ┆ g_3_receivi ┆ _avg_ppr    ┆ ppr         │
│ ---          ┆ i32    ┆ i32  ┆ str  ┆   ┆ s            ┆ ng_yards    ┆ ---         ┆ ---         │
│ str          ┆        ┆      ┆      ┆   ┆ ---          ┆ ---         ┆ f64         ┆ f64         │
│              ┆        ┆      ┆      ┆   ┆ f64          ┆ f64         ┆             ┆             │
╞══════════════╪════════╪══════╪══════╪═══╪══════════════╪═════════════╪═════════════╪═════════════╡
│ A.J. Brown   ┆ 2021   ┆ 5    ┆ TEN  ┆ … ┆ 2.33         ┆ 30.67       ┆ 7.5         ┆ 6.8         │
│ A.J. Brown   ┆ 2021   ┆ 6    ┆ TEN  ┆ … ┆ 2.0          ┆ 27.0        ┆ 7.32        ┆ 16.1        │
│ A.J. Brown   ┆ 2021   ┆ 7    ┆ TEN  ┆ … ┆ 3.33         ┆ 43.0        ┆ 9.08        ┆ 27.3        │
│ A.J. Brown   ┆ 2021   ┆ 8    ┆ TEN  ┆ … ┆ 6.0          ┆ 87.33       ┆ 12.12       ┆ 31.5        │
│ A.J. Brown   ┆ 2021   ┆ 9    ┆ TEN  ┆ … ┆ 8.33         ┆ 126.33      ┆ 14.89       ┆ 9.2         │
│ …            ┆ …      ┆ …    ┆ …    ┆ … ┆ …            ┆ …           ┆ …           ┆ …           │
│ Zay Jones    ┆ 2024   ┆ 17   ┆ ARI  ┆ … ┆ 1.0          ┆ 6.33        ┆ 1.22        ┆ 2.9         │
│ Zay Jones    ┆ 2024   ┆ 18   ┆ ARI  ┆ … ┆ 1.0          ┆ 11.67       ┆ 1.56        ┆ 8.6         │
│ Zay Jones    ┆ 2025   ┆ 6    ┆ ARI  ┆ … ┆ 1.67         ┆ 12.33       ┆ 2.9         ┆ 12.9        │
│ Zay Jones    ┆ 2025   ┆ 7    ┆ ARI  ┆ … ┆ 3.0          ┆ 37.33       ┆ 5.4         ┆ 8.7         │
│ Zay Jones    ┆ 2025   ┆ 10   ┆ ARI  ┆ … ┆ 3.0          ┆ 51.33       ┆ 6.06        ┆ 0.0         │
└──────────────┴────────┴──────┴──────┴───┴──────────────┴─────────────┴─────────────┴─────────────┘

In [42]:
X_train = dataset.filter(pl.col("season") < 2025).select([
    'prev_rolling_3_ppr',
    'prev_rolling_3_targets',
    'prev_rolling_3_receptions',
    'prev_rolling_3_receiving_yards',
    'prev_season_avg_ppr',
]).to_numpy()

X_test = dataset.filter(pl.col("season") == 2025).select([
    'prev_rolling_3_ppr',
    'prev_rolling_3_targets',
    'prev_rolling_3_receptions',
    'prev_rolling_3_receiving_yards',
    'prev_season_avg_ppr',
]).to_numpy()

y_train = dataset.filter(pl.col("season") < 2025).select('calculated_ppr').to_numpy().ravel()
y_test = dataset.filter(pl.col("season") == 2025).select('calculated_ppr').to_numpy().ravel()

model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
mae = mean_absolute_error(y_test, y_pred)
print(f"Mean Absolute Error: {mae}")

Mean Absolute Error: 4.405180270665091

In [43]:
test_results = (
    dataset
    .filter(pl.col("season") == 2025)
    .with_columns(
        pl.Series("linear_regression_prediction", y_pred)
    )
)

test_results = test_results.with_columns(
    (pl.col("linear_regression_prediction") - pl.col("calculated_ppr"))
    .abs()
    .round(2)
    .alias("linear_regression_absolute_error"),

    (pl.col("prev_rolling_3_ppr") - pl.col("calculated_ppr"))
    .abs()
    .round(2)
    .alias("rolling_baseline_absolute_error"),

    (pl.col("prev_season_avg_ppr") - pl.col("calculated_ppr"))
    .abs()
    .round(2)
    .alias("season_baseline_absolute_error")
)

test_results.select([
    "player_display_name",
    "season",
    "week",
    "calculated_ppr",
    "linear_regression_prediction",
    "linear_regression_absolute_error",
    "rolling_baseline_absolute_error",
    "season_baseline_absolute_error",
]).sort("linear_regression_absolute_error", descending=True).head(20)

shape: (20, 8)
┌─────────────┬────────┬──────┬─────────────┬─────────────┬─────────────┬─────────────┬────────────┐
│ player_disp ┆ season ┆ week ┆ calculated_ ┆ linear_regr ┆ linear_regr ┆ rolling_bas ┆ season_bas │
│ lay_name    ┆ ---    ┆ ---  ┆ ppr         ┆ ession_pred ┆ ession_abso ┆ eline_absol ┆ eline_abso │
│ ---         ┆ i32    ┆ i32  ┆ ---         ┆ iction      ┆ lute_err…   ┆ ute_erro…   ┆ lute_error │
│ str         ┆        ┆      ┆ f64         ┆ ---         ┆ ---         ┆ ---         ┆ ---        │
│             ┆        ┆      ┆             ┆ f64         ┆ f64         ┆ f64         ┆ f64        │
╞═════════════╪════════╪══════╪═════════════╪═════════════╪═════════════╪═════════════╪════════════╡
│ Puka Nacua  ┆ 2025   ┆ 16   ┆ 46.5        ┆ 19.307006   ┆ 27.19       ┆ 20.9        ┆ 24.44      │
│ Michael     ┆ 2025   ┆ 11   ┆ 33.5        ┆ 7.02605     ┆ 26.47       ┆ 25.67       ┆ 27.82      │
│ Wilson      ┆        ┆      ┆             ┆             ┆             ┆             ┆            │
│ Amon-Ra St. ┆ 2025   ┆ 15   ┆ 41.4        ┆ 15.430114   ┆ 25.97       ┆ 26.37       ┆ 23.44      │
│ Brown       ┆        ┆      ┆             ┆             ┆             ┆             ┆            │
│ Chris Olave ┆ 2025   ┆ 16   ┆ 36.8        ┆ 12.89305    ┆ 23.91       ┆ 23.07       ┆ 21.99      │
│ Michael     ┆ 2025   ┆ 14   ┆ 37.2        ┆ 13.663759   ┆ 23.54       ┆ 16.57       ┆ 27.78      │
│ Wilson      ┆        ┆      ┆             ┆             ┆             ┆             ┆            │
│ …           ┆ …      ┆ …    ┆ …           ┆ …           ┆ …           ┆ …           ┆ …          │
│ Alec Pierce ┆ 2025   ┆ 18   ┆ 29.2        ┆ 8.776934    ┆ 20.42       ┆ 20.13       ┆ 18.19      │
│ Adonai      ┆ 2025   ┆ 13   ┆ 24.2        ┆ 4.903677    ┆ 19.3        ┆ 20.9        ┆ 21.16      │
│ Mitchell    ┆        ┆      ┆             ┆             ┆             ┆             ┆            │
│ Puka Nacua  ┆ 2025   ┆ 6    ┆ 4.8         ┆ 23.959682   ┆ 19.16       ┆ 22.97       ┆ 22.0       │
│ Luther      ┆ 2025   ┆ 17   ┆ 27.8        ┆ 8.648684    ┆ 19.15       ┆ 16.8        ┆ 20.68      │
│ Burden III  ┆        ┆      ┆             ┆             ┆             ┆             ┆            │
│ Kayshon     ┆ 2025   ┆ 6    ┆ 26.3        ┆ 7.299465    ┆ 19.0        ┆ 21.33       ┆ 18.34      │
│ Boutte      ┆        ┆      ┆             ┆             ┆             ┆             ┆            │
└─────────────┴────────┴──────┴─────────────┴─────────────┴─────────────┴─────────────┴────────────┘

In [44]:
feature_columns = [
    "prev_rolling_3_ppr",
    "prev_rolling_3_targets",
    "prev_rolling_3_receptions",
    "prev_rolling_3_receiving_yards",
    "prev_season_avg_ppr",
]

coefficients = pl.DataFrame({
    "feature": feature_columns,
    "coefficient": model.coef_,
}).sort("coefficient", descending=True)

coefficients

shape: (5, 2)
┌────────────────────────────────┬─────────────┐
│ feature                        ┆ coefficient │
│ ---                            ┆ ---         │
│ str                            ┆ f64         │
╞════════════════════════════════╪═════════════╡
│ prev_season_avg_ppr            ┆ 0.580249    │
│ prev_rolling_3_targets         ┆ 0.373956    │
│ prev_rolling_3_receptions      ┆ 0.254936    │
│ prev_rolling_3_receiving_yards ┆ 0.015749    │
│ prev_rolling_3_ppr             ┆ -0.097503   │
└────────────────────────────────┴─────────────┘