In [1]:
import pandas as pd
import polars as pl
import matplotlib.pyplot as plt
import sys
from pathlib import Path
import sklearn
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import root_mean_squared_error

project_root = Path.cwd().parent
sys.path.append(str(project_root))

In [2]:
from src.data import load_wr_weekly_stats

receiving_stats = load_wr_weekly_stats([2021, 2022, 2023, 2024, 2025])
receiving_stats

shape: (12_298, 18)
┌─────────────┬────────┬────────────┬──────┬───┬────────────┬────────────┬────────────┬────────────┐
│ player_disp ┆ season ┆ season_typ ┆ week ┆ … ┆ rushing_td ┆ rushing_fu ┆ rushing_2p ┆ fantasy_po │
│ lay_name    ┆ ---    ┆ e          ┆ ---  ┆   ┆ s          ┆ mbles_lost ┆ t_conversi ┆ ints_ppr   │
│ ---         ┆ i32    ┆ ---        ┆ i32  ┆   ┆ ---        ┆ ---        ┆ ons        ┆ ---        │
│ str         ┆        ┆ str        ┆      ┆   ┆ i32        ┆ i32        ┆ ---        ┆ f64        │
│             ┆        ┆            ┆      ┆   ┆            ┆            ┆ i32        ┆            │
╞═════════════╪════════╪════════════╪══════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ Danny       ┆ 2021   ┆ REG        ┆ 1    ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 14.4       │
│ Amendola    ┆        ┆            ┆      ┆   ┆            ┆            ┆            ┆            │
│ DeSean      ┆ 2021   ┆ REG        ┆ 1    ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 4.1        │
│ Jackson     ┆        ┆            ┆      ┆   ┆            ┆            ┆            ┆            │
│ Emmanuel    ┆ 2021   ┆ REG        ┆ 1    ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 9.2        │
│ Sanders     ┆        ┆            ┆      ┆   ┆            ┆            ┆            ┆            │
│ Andre       ┆ 2021   ┆ REG        ┆ 1    ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 0.0        │
│ Roberts     ┆        ┆            ┆      ┆   ┆            ┆            ┆            ┆            │
│ Antonio     ┆ 2021   ┆ REG        ┆ 1    ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 23.7       │
│ Brown       ┆        ┆            ┆      ┆   ┆            ┆            ┆            ┆            │
│ …           ┆ …      ┆ …          ┆ …    ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ Chimere     ┆ 2025   ┆ REG        ┆ 18   ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 5.7        │
│ Dike        ┆        ┆            ┆      ┆   ┆            ┆            ┆            ┆            │
│ Tre Harris  ┆ 2025   ┆ REG        ┆ 18   ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 4.8        │
│ Jack Bech   ┆ 2025   ┆ REG        ┆ 18   ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 0.0        │
│ Luther      ┆ 2025   ┆ REG        ┆ 18   ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 7.5        │
│ Burden III  ┆        ┆            ┆      ┆   ┆            ┆            ┆            ┆            │
│ Isaiah Bond ┆ 2025   ┆ REG        ┆ 18   ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 2.7        │
└─────────────┴────────┴────────────┴──────┴───┴────────────┴────────────┴────────────┴────────────┘

In [3]:
from src.scoring import calculate_ppr

receiving_stats_ppr = calculate_ppr(receiving_stats)
receiving_stats_ppr

shape: (12_298, 19)
┌─────────────┬────────┬────────────┬──────┬───┬────────────┬────────────┬────────────┬────────────┐
│ player_disp ┆ season ┆ season_typ ┆ week ┆ … ┆ rushing_fu ┆ rushing_2p ┆ fantasy_po ┆ calculated │
│ lay_name    ┆ ---    ┆ e          ┆ ---  ┆   ┆ mbles_lost ┆ t_conversi ┆ ints_ppr   ┆ _ppr       │
│ ---         ┆ i32    ┆ ---        ┆ i32  ┆   ┆ ---        ┆ ons        ┆ ---        ┆ ---        │
│ str         ┆        ┆ str        ┆      ┆   ┆ i32        ┆ ---        ┆ f64        ┆ f64        │
│             ┆        ┆            ┆      ┆   ┆            ┆ i32        ┆            ┆            │
╞═════════════╪════════╪════════════╪══════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ Danny       ┆ 2021   ┆ REG        ┆ 1    ┆ … ┆ 0          ┆ 0          ┆ 14.4       ┆ 14.4       │
│ Amendola    ┆        ┆            ┆      ┆   ┆            ┆            ┆            ┆            │
│ DeSean      ┆ 2021   ┆ REG        ┆ 1    ┆ … ┆ 0          ┆ 0          ┆ 4.1        ┆ 4.1        │
│ Jackson     ┆        ┆            ┆      ┆   ┆            ┆            ┆            ┆            │
│ Emmanuel    ┆ 2021   ┆ REG        ┆ 1    ┆ … ┆ 0          ┆ 0          ┆ 9.2        ┆ 9.2        │
│ Sanders     ┆        ┆            ┆      ┆   ┆            ┆            ┆            ┆            │
│ Andre       ┆ 2021   ┆ REG        ┆ 1    ┆ … ┆ 0          ┆ 0          ┆ 0.0        ┆ 0.0        │
│ Roberts     ┆        ┆            ┆      ┆   ┆            ┆            ┆            ┆            │
│ Antonio     ┆ 2021   ┆ REG        ┆ 1    ┆ … ┆ 0          ┆ 0          ┆ 23.7       ┆ 23.7       │
│ Brown       ┆        ┆            ┆      ┆   ┆            ┆            ┆            ┆            │
│ …           ┆ …      ┆ …          ┆ …    ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ Chimere     ┆ 2025   ┆ REG        ┆ 18   ┆ … ┆ 0          ┆ 0          ┆ 5.7        ┆ 5.7        │
│ Dike        ┆        ┆            ┆      ┆   ┆            ┆            ┆            ┆            │
│ Tre Harris  ┆ 2025   ┆ REG        ┆ 18   ┆ … ┆ 0          ┆ 0          ┆ 4.8        ┆ 4.8        │
│ Jack Bech   ┆ 2025   ┆ REG        ┆ 18   ┆ … ┆ 0          ┆ 0          ┆ 0.0        ┆ 0.0        │
│ Luther      ┆ 2025   ┆ REG        ┆ 18   ┆ … ┆ 0          ┆ 0          ┆ 7.5        ┆ 7.5        │
│ Burden III  ┆        ┆            ┆      ┆   ┆            ┆            ┆            ┆            │
│ Isaiah Bond ┆ 2025   ┆ REG        ┆ 18   ┆ … ┆ 0          ┆ 0          ┆ 2.7        ┆ 2.7        │
└─────────────┴────────┴────────────┴──────┴───┴────────────┴────────────┴────────────┴────────────┘

In [4]:
from src.features import create_features
from src.features import create_defensive_features
from src.modeling import FEATURE_COLUMNS, TARGET_COLUMN, make_train_test_data, train_linear_regression, evaluate_predictions

player_prediction_features = create_features(receiving_stats_ppr)
player_prediction_features = create_defensive_features(player_prediction_features)

player_prediction_features

shape: (12_298, 25)
┌─────────────┬────────┬────────────┬──────┬───┬────────────┬────────────┬────────────┬────────────┐
│ player_disp ┆ season ┆ season_typ ┆ week ┆ … ┆ prev_rolli ┆ prev_rolli ┆ prev_seaso ┆ prev_defen │
│ lay_name    ┆ ---    ┆ e          ┆ ---  ┆   ┆ ng_3_recep ┆ ng_3_recei ┆ n_avg_ppr  ┆ se_wr_ppr_ │
│ ---         ┆ i32    ┆ ---        ┆ i32  ┆   ┆ tions      ┆ ving_yards ┆ ---        ┆ allowed_av │
│ str         ┆        ┆ str        ┆      ┆   ┆ ---        ┆ ---        ┆ f64        ┆ …          │
│             ┆        ┆            ┆      ┆   ┆ f64        ┆ f64        ┆            ┆ ---        │
│             ┆        ┆            ┆      ┆   ┆            ┆            ┆            ┆ f64        │
╞═════════════╪════════╪════════════╪══════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ A.J. Brown  ┆ 2021   ┆ REG        ┆ 1    ┆ … ┆ null       ┆ null       ┆ null       ┆ null       │
│ A.J. Brown  ┆ 2021   ┆ REG        ┆ 2    ┆ … ┆ null       ┆ null       ┆ 14.9       ┆ 34.2       │
│ A.J. Brown  ┆ 2021   ┆ REG        ┆ 3    ┆ … ┆ null       ┆ null       ┆ 11.1       ┆ 48.75      │
│ A.J. Brown  ┆ 2021   ┆ REG        ┆ 5    ┆ … ┆ 2.33       ┆ 30.67      ┆ 7.5        ┆ 40.88      │
│ A.J. Brown  ┆ 2021   ┆ REG        ┆ 6    ┆ … ┆ 2.0        ┆ 27.0       ┆ 7.32       ┆ 26.62      │
│ …           ┆ …      ┆ …          ┆ …    ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ Zay Jones   ┆ 2025   ┆ REG        ┆ 3    ┆ … ┆ 2.0        ┆ 23.0       ┆ 1.4        ┆ 30.7       │
│ Zay Jones   ┆ 2025   ┆ REG        ┆ 5    ┆ … ┆ 2.33       ┆ 25.0       ┆ 2.95       ┆ 38.7       │
│ Zay Jones   ┆ 2025   ┆ REG        ┆ 6    ┆ … ┆ 1.67       ┆ 12.33      ┆ 2.9        ┆ 38.02      │
│ Zay Jones   ┆ 2025   ┆ REG        ┆ 7    ┆ … ┆ 3.0        ┆ 37.33      ┆ 5.4        ┆ 33.42      │
│ Zay Jones   ┆ 2025   ┆ REG        ┆ 10   ┆ … ┆ 3.0        ┆ 51.33      ┆ 6.06       ┆ 29.04      │
└─────────────┴────────┴────────────┴──────┴───┴────────────┴────────────┴────────────┴────────────┘

In [5]:
with pl.Config(tbl_rows=-1):
    print(player_prediction_features.filter(pl.col("player_display_name") == 'CeeDee Lamb').head(20))
# player_prediction_features.filter(
#     pl.col("player_display_name") == "A.J. Brown"
# ).select([
#     "player_display_name",
#     "season",
#     "week",
#     "calculated_ppr",
#     "prev_rolling_3_ppr",
#     "targets",
#     "prev_rolling_3_targets",
#     "receptions",
#     "prev_rolling_3_receptions",
#     "receiving_yards",
#     "prev_rolling_3_receiving_yards"
# ]).sort(["season", "week"])

shape: (20, 25)
┌─────────────┬────────┬────────────┬──────┬───┬────────────┬────────────┬────────────┬────────────┐
│ player_disp ┆ season ┆ season_typ ┆ week ┆ … ┆ prev_rolli ┆ prev_rolli ┆ prev_seaso ┆ prev_defen │
│ lay_name    ┆ ---    ┆ e          ┆ ---  ┆   ┆ ng_3_recep ┆ ng_3_recei ┆ n_avg_ppr  ┆ se_wr_ppr_ │
│ ---         ┆ i32    ┆ ---        ┆ i32  ┆   ┆ tions      ┆ ving_yards ┆ ---        ┆ allowed_av │
│ str         ┆        ┆ str        ┆      ┆   ┆ ---        ┆ ---        ┆ f64        ┆ …          │
│             ┆        ┆            ┆      ┆   ┆ f64        ┆ f64        ┆            ┆ ---        │
│             ┆        ┆            ┆      ┆   ┆            ┆            ┆            ┆ f64        │
╞═════════════╪════════╪════════════╪══════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ CeeDee Lamb ┆ 2021   ┆ REG        ┆ 1    ┆ … ┆ null       ┆ null       ┆ null       ┆ null       │
│ CeeDee Lamb ┆ 2021   ┆ REG        ┆ 2    ┆ … ┆ null       ┆ null       ┆ 23.4       ┆ 16.7       │
│ CeeDee Lamb ┆ 2021   ┆ REG        ┆ 3    ┆ … ┆ null       ┆ null       ┆ 20.4       ┆ 19.7       │
│ CeeDee Lamb ┆ 2021   ┆ REG        ┆ 4    ┆ … ┆ 6.0        ┆ 83.67      ┆ 16.77      ┆ 29.2       │
│ CeeDee Lamb ┆ 2021   ┆ REG        ┆ 5    ┆ … ┆ 4.33       ┆ 53.33      ┆ 13.4       ┆ 35.3       │
│ CeeDee Lamb ┆ 2021   ┆ REG        ┆ 6    ┆ … ┆ 3.0        ┆ 54.33      ┆ 14.48      ┆ 32.06      │
│ CeeDee Lamb ┆ 2021   ┆ REG        ┆ 8    ┆ … ┆ 5.0        ┆ 82.0       ┆ 18.08      ┆ 35.98      │
│ CeeDee Lamb ┆ 2021   ┆ REG        ┆ 9    ┆ … ┆ 6.33       ┆ 115.0      ┆ 17.96      ┆ 33.43      │
│ CeeDee Lamb ┆ 2021   ┆ REG        ┆ 10   ┆ … ┆ 5.67       ┆ 94.67      ┆ 16.25      ┆ 35.04      │
│ CeeDee Lamb ┆ 2021   ┆ REG        ┆ 11   ┆ … ┆ 4.67       ┆ 76.33      ┆ 17.62      ┆ 33.52      │
│ CeeDee Lamb ┆ 2021   ┆ REG        ┆ 13   ┆ … ┆ 3.67       ┆ 43.67      ┆ 16.3       ┆ 37.74      │
│ CeeDee Lamb ┆ 2021   ┆ REG        ┆ 14   ┆ … ┆ 5.33       ┆ 65.67      ┆ 16.56      ┆ 38.83      │
│ CeeDee Lamb ┆ 2021   ┆ REG        ┆ 15   ┆ … ┆ 5.67       ┆ 54.67      ┆ 16.4       ┆ 37.33      │
│ CeeDee Lamb ┆ 2021   ┆ REG        ┆ 16   ┆ … ┆ 6.67       ┆ 66.67      ┆ 15.98      ┆ 38.67      │
│ CeeDee Lamb ┆ 2021   ┆ REG        ┆ 17   ┆ … ┆ 5.67       ┆ 59.0       ┆ 15.59      ┆ 36.61      │
│ CeeDee Lamb ┆ 2021   ┆ REG        ┆ 18   ┆ … ┆ 4.33       ┆ 55.67      ┆ 15.09      ┆ 27.4       │
│ CeeDee Lamb ┆ 2022   ┆ REG        ┆ 1    ┆ … ┆ 3.0        ┆ 54.0       ┆ null       ┆ null       │
│ CeeDee Lamb ┆ 2022   ┆ REG        ┆ 2    ┆ … ┆ 2.33       ┆ 41.67      ┆ 4.9        ┆ 23.2       │
│ CeeDee Lamb ┆ 2022   ┆ REG        ┆ 3    ┆ … ┆ 3.67       ┆ 49.67      ┆ 10.0       ┆ 23.8       │
│ CeeDee Lamb ┆ 2022   ┆ REG        ┆ 4    ┆ … ┆ 5.67       ┆ 63.67      ┆ 14.23      ┆ 49.2       │
└─────────────┴────────┴────────────┴──────┴───┴────────────┴────────────┴────────────┴────────────┘

In [6]:
player_prediction_features = (
    player_prediction_features
    .sort(["player_display_name", "season", "week"])
    .with_columns(
        (
            pl.col("calculated_ppr").shift(1).cum_sum().over(["player_display_name", "season"])
            /
            pl.col("calculated_ppr").shift(1).cum_count().over(["player_display_name", "season"])
        )
        .round(2)
        .alias("prev_season_avg_ppr")
    )
)

player_prediction_features

shape: (12_298, 25)
┌─────────────┬────────┬────────────┬──────┬───┬────────────┬────────────┬────────────┬────────────┐
│ player_disp ┆ season ┆ season_typ ┆ week ┆ … ┆ prev_rolli ┆ prev_rolli ┆ prev_seaso ┆ prev_defen │
│ lay_name    ┆ ---    ┆ e          ┆ ---  ┆   ┆ ng_3_recep ┆ ng_3_recei ┆ n_avg_ppr  ┆ se_wr_ppr_ │
│ ---         ┆ i32    ┆ ---        ┆ i32  ┆   ┆ tions      ┆ ving_yards ┆ ---        ┆ allowed_av │
│ str         ┆        ┆ str        ┆      ┆   ┆ ---        ┆ ---        ┆ f64        ┆ …          │
│             ┆        ┆            ┆      ┆   ┆ f64        ┆ f64        ┆            ┆ ---        │
│             ┆        ┆            ┆      ┆   ┆            ┆            ┆            ┆ f64        │
╞═════════════╪════════╪════════════╪══════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ A.J. Brown  ┆ 2021   ┆ REG        ┆ 1    ┆ … ┆ null       ┆ null       ┆ null       ┆ null       │
│ A.J. Brown  ┆ 2021   ┆ REG        ┆ 2    ┆ … ┆ null       ┆ null       ┆ 14.9       ┆ 34.2       │
│ A.J. Brown  ┆ 2021   ┆ REG        ┆ 3    ┆ … ┆ null       ┆ null       ┆ 11.1       ┆ 48.75      │
│ A.J. Brown  ┆ 2021   ┆ REG        ┆ 5    ┆ … ┆ 2.33       ┆ 30.67      ┆ 7.5        ┆ 40.88      │
│ A.J. Brown  ┆ 2021   ┆ REG        ┆ 6    ┆ … ┆ 2.0        ┆ 27.0       ┆ 7.32       ┆ 26.62      │
│ …           ┆ …      ┆ …          ┆ …    ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ Zay Jones   ┆ 2025   ┆ REG        ┆ 3    ┆ … ┆ 2.0        ┆ 23.0       ┆ 1.4        ┆ 30.7       │
│ Zay Jones   ┆ 2025   ┆ REG        ┆ 5    ┆ … ┆ 2.33       ┆ 25.0       ┆ 2.95       ┆ 38.7       │
│ Zay Jones   ┆ 2025   ┆ REG        ┆ 6    ┆ … ┆ 1.67       ┆ 12.33      ┆ 2.9        ┆ 38.02      │
│ Zay Jones   ┆ 2025   ┆ REG        ┆ 7    ┆ … ┆ 3.0        ┆ 37.33      ┆ 5.4        ┆ 33.42      │
│ Zay Jones   ┆ 2025   ┆ REG        ┆ 10   ┆ … ┆ 3.0        ┆ 51.33      ┆ 6.06       ┆ 29.04      │
└─────────────┴────────┴────────────┴──────┴───┴────────────┴────────────┴────────────┴────────────┘

In [7]:
player_prediction_features.filter(
    pl.col("player_display_name") == "A.J. Brown"
).select([
    "player_display_name",
    "season",
    "week",
    "calculated_ppr",
    "prev_season_avg_ppr"
]).sort(["season", "week"])

shape: (75, 5)
┌─────────────────────┬────────┬──────┬────────────────┬─────────────────────┐
│ player_display_name ┆ season ┆ week ┆ calculated_ppr ┆ prev_season_avg_ppr │
│ ---                 ┆ ---    ┆ ---  ┆ ---            ┆ ---                 │
│ str                 ┆ i32    ┆ i32  ┆ f64            ┆ f64                 │
╞═════════════════════╪════════╪══════╪════════════════╪═════════════════════╡
│ A.J. Brown          ┆ 2021   ┆ 1    ┆ 14.9           ┆ null                │
│ A.J. Brown          ┆ 2021   ┆ 2    ┆ 7.3            ┆ 14.9                │
│ A.J. Brown          ┆ 2021   ┆ 3    ┆ 0.3            ┆ 11.1                │
│ A.J. Brown          ┆ 2021   ┆ 5    ┆ 6.8            ┆ 7.5                 │
│ A.J. Brown          ┆ 2021   ┆ 6    ┆ 16.1           ┆ 7.32                │
│ …                   ┆ …      ┆ …    ┆ …              ┆ …                   │
│ A.J. Brown          ┆ 2025   ┆ 13   ┆ 35.2           ┆ 12.67               │
│ A.J. Brown          ┆ 2025   ┆ 14   ┆ 16.0           ┆ 14.72               │
│ A.J. Brown          ┆ 2025   ┆ 15   ┆ 12.1           ┆ 14.82               │
│ A.J. Brown          ┆ 2025   ┆ 16   ┆ 18.5           ┆ 14.62               │
│ A.J. Brown          ┆ 2025   ┆ 17   ┆ 11.8           ┆ 14.89               │
└─────────────────────┴────────┴──────┴────────────────┴─────────────────────┘

In [8]:
baseline_prediction_clean = player_prediction_features.filter(
    pl.col("prev_rolling_3_ppr").is_not_null()
)

baseline_prediction_clean

shape: (11_014, 25)
┌─────────────┬────────┬────────────┬──────┬───┬────────────┬────────────┬────────────┬────────────┐
│ player_disp ┆ season ┆ season_typ ┆ week ┆ … ┆ prev_rolli ┆ prev_rolli ┆ prev_seaso ┆ prev_defen │
│ lay_name    ┆ ---    ┆ e          ┆ ---  ┆   ┆ ng_3_recep ┆ ng_3_recei ┆ n_avg_ppr  ┆ se_wr_ppr_ │
│ ---         ┆ i32    ┆ ---        ┆ i32  ┆   ┆ tions      ┆ ving_yards ┆ ---        ┆ allowed_av │
│ str         ┆        ┆ str        ┆      ┆   ┆ ---        ┆ ---        ┆ f64        ┆ …          │
│             ┆        ┆            ┆      ┆   ┆ f64        ┆ f64        ┆            ┆ ---        │
│             ┆        ┆            ┆      ┆   ┆            ┆            ┆            ┆ f64        │
╞═════════════╪════════╪════════════╪══════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ A.J. Brown  ┆ 2021   ┆ REG        ┆ 5    ┆ … ┆ 2.33       ┆ 30.67      ┆ 7.5        ┆ 40.88      │
│ A.J. Brown  ┆ 2021   ┆ REG        ┆ 6    ┆ … ┆ 2.0        ┆ 27.0       ┆ 7.32       ┆ 26.62      │
│ A.J. Brown  ┆ 2021   ┆ REG        ┆ 7    ┆ … ┆ 3.33       ┆ 43.0       ┆ 9.08       ┆ 33.08      │
│ A.J. Brown  ┆ 2021   ┆ REG        ┆ 8    ┆ … ┆ 6.0        ┆ 87.33      ┆ 12.12      ┆ 38.4       │
│ A.J. Brown  ┆ 2021   ┆ REG        ┆ 9    ┆ … ┆ 8.33       ┆ 126.33     ┆ 14.89      ┆ 36.88      │
│ …           ┆ …      ┆ …          ┆ …    ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ Zay Jones   ┆ 2025   ┆ REG        ┆ 3    ┆ … ┆ 2.0        ┆ 23.0       ┆ 1.4        ┆ 30.7       │
│ Zay Jones   ┆ 2025   ┆ REG        ┆ 5    ┆ … ┆ 2.33       ┆ 25.0       ┆ 2.95       ┆ 38.7       │
│ Zay Jones   ┆ 2025   ┆ REG        ┆ 6    ┆ … ┆ 1.67       ┆ 12.33      ┆ 2.9        ┆ 38.02      │
│ Zay Jones   ┆ 2025   ┆ REG        ┆ 7    ┆ … ┆ 3.0        ┆ 37.33      ┆ 5.4        ┆ 33.42      │
│ Zay Jones   ┆ 2025   ┆ REG        ┆ 10   ┆ … ┆ 3.0        ┆ 51.33      ┆ 6.06       ┆ 29.04      │
└─────────────┴────────┴────────────┴──────┴───┴────────────┴────────────┴────────────┴────────────┘

In [9]:
dataset = (
    baseline_prediction_clean.select([
        'player_display_name',
        'season',
        'week',
        'team',
        'opponent_team',
        'prev_rolling_3_ppr',
        'prev_rolling_3_targets',
        'prev_rolling_3_receptions',
        'prev_rolling_3_receiving_yards',
        'prev_season_avg_ppr',
        'prev_defense_wr_ppr_allowed_avg',
        'calculated_ppr',
    ])
)

dataset = dataset.filter(
    (pl.col("prev_rolling_3_ppr").is_not_null()) & 
    (pl.col("prev_rolling_3_targets").is_not_null()) & 
    (pl.col("prev_rolling_3_receptions").is_not_null()) & 
    (pl.col("prev_rolling_3_receiving_yards").is_not_null()) & 
    (pl.col("prev_season_avg_ppr").is_not_null()) & 
    (pl.col("prev_defense_wr_ppr_allowed_avg").is_not_null()) & 
    (pl.col("calculated_ppr").is_not_null())
)

dataset

shape: (10_301, 12)
┌──────────────┬────────┬──────┬──────┬───┬──────────────┬─────────────┬─────────────┬─────────────┐
│ player_displ ┆ season ┆ week ┆ team ┆ … ┆ prev_rolling ┆ prev_season ┆ prev_defens ┆ calculated_ │
│ ay_name      ┆ ---    ┆ ---  ┆ ---  ┆   ┆ _3_receiving ┆ _avg_ppr    ┆ e_wr_ppr_al ┆ ppr         │
│ ---          ┆ i32    ┆ i32  ┆ str  ┆   ┆ _yards       ┆ ---         ┆ lowed_av…   ┆ ---         │
│ str          ┆        ┆      ┆      ┆   ┆ ---          ┆ f64         ┆ ---         ┆ f64         │
│              ┆        ┆      ┆      ┆   ┆ f64          ┆             ┆ f64         ┆             │
╞══════════════╪════════╪══════╪══════╪═══╪══════════════╪═════════════╪═════════════╪═════════════╡
│ A.J. Brown   ┆ 2021   ┆ 5    ┆ TEN  ┆ … ┆ 30.67        ┆ 7.5         ┆ 40.88       ┆ 6.8         │
│ A.J. Brown   ┆ 2021   ┆ 6    ┆ TEN  ┆ … ┆ 27.0         ┆ 7.32        ┆ 26.62       ┆ 16.1        │
│ A.J. Brown   ┆ 2021   ┆ 7    ┆ TEN  ┆ … ┆ 43.0         ┆ 9.08        ┆ 33.08       ┆ 27.3        │
│ A.J. Brown   ┆ 2021   ┆ 8    ┆ TEN  ┆ … ┆ 87.33        ┆ 12.12       ┆ 38.4        ┆ 31.5        │
│ A.J. Brown   ┆ 2021   ┆ 9    ┆ TEN  ┆ … ┆ 126.33       ┆ 14.89       ┆ 36.88       ┆ 9.2         │
│ …            ┆ …      ┆ …    ┆ …    ┆ … ┆ …            ┆ …           ┆ …           ┆ …           │
│ Zay Jones    ┆ 2025   ┆ 3    ┆ ARI  ┆ … ┆ 23.0         ┆ 1.4         ┆ 30.7        ┆ 4.5         │
│ Zay Jones    ┆ 2025   ┆ 5    ┆ ARI  ┆ … ┆ 25.0         ┆ 2.95        ┆ 38.7        ┆ 2.8         │
│ Zay Jones    ┆ 2025   ┆ 6    ┆ ARI  ┆ … ┆ 12.33        ┆ 2.9         ┆ 38.02       ┆ 12.9        │
│ Zay Jones    ┆ 2025   ┆ 7    ┆ ARI  ┆ … ┆ 37.33        ┆ 5.4         ┆ 33.42       ┆ 8.7         │
│ Zay Jones    ┆ 2025   ┆ 10   ┆ ARI  ┆ … ┆ 51.33        ┆ 6.06        ┆ 29.04       ┆ 0.0         │
└──────────────┴────────┴──────┴──────┴───┴──────────────┴─────────────┴─────────────┴─────────────┘

In [10]:
test_2025 = dataset.filter(pl.col("season") == 2025)

rolling_mae, rolling_rmse = evaluate_predictions(
    test_2025["calculated_ppr"].to_numpy(),
    test_2025["prev_rolling_3_ppr"].to_numpy(),
)
print(f"Rolling 3-game baseline MAE: {rolling_mae}")
print(f"Rolling 3-game baseline RMSE: {rolling_rmse}")

Rolling 3-game baseline MAE: 4.56
Rolling 3-game baseline RMSE: 6.41

In [11]:
season_avg_mae, season_avg_rmse = evaluate_predictions(
    test_2025["calculated_ppr"].to_numpy(),
    test_2025["prev_season_avg_ppr"].to_numpy(),
)
print(f"Season-to-date baseline MAE: {season_avg_mae}")
print(f"Season-to-date baseline RMSE: {season_avg_rmse}")

Season-to-date baseline MAE: 4.45
Season-to-date baseline RMSE: 6.27

In [12]:
feature_columns = FEATURE_COLUMNS
feature_columns

['prev_rolling_3_ppr',
 'prev_rolling_3_targets',
 'prev_rolling_3_receptions',
 'prev_rolling_3_receiving_yards',
 'prev_season_avg_ppr',
 'prev_defense_wr_ppr_allowed_avg']

In [13]:
X_train, X_test, y_train, y_test = make_train_test_data(
    dataset,
    FEATURE_COLUMNS,
    TARGET_COLUMN,
)

model, mae, rmse = train_linear_regression(dataset)
y_pred = model.predict(X_test)

print(f"Mean Absolute Error: {mae}")
print(f"Root Mean Squared Error: {rmse}")

Mean Absolute Error: 4.39
Root Mean Squared Error: 6.0

In [14]:
random_forest = RandomForestRegressor(n_estimators=200, random_state=42, min_samples_leaf=5)

random_forest.fit(X_train, y_train)

rf_y_pred = random_forest.predict(X_test)
rf_mae = mean_absolute_error(y_test, rf_y_pred)
rf_rmse = root_mean_squared_error(y_test, rf_y_pred)
print(f"Random Forest Mean Absolute Error: {rf_mae}")
print(f"Random Forest Root Mean Squared Error: {rf_rmse}")

Random Forest Mean Absolute Error: 4.458324341378723
Random Forest Root Mean Squared Error: 6.120431530180162

In [15]:
test_results = (
    dataset
    .filter(pl.col("season") == 2025)
    .with_columns(
        pl.Series("linear_regression_prediction", y_pred),
        pl.Series("random_forest_prediction", rf_y_pred)
    )
)

test_results = test_results.with_columns(
    (pl.col("linear_regression_prediction") - pl.col("calculated_ppr"))
    .abs()
    .round(2)
    .alias("linear_regression_absolute_error"),

    (pl.col("prev_rolling_3_ppr") - pl.col("calculated_ppr"))
    .abs()
    .round(2)
    .alias("rolling_baseline_absolute_error"),

    (pl.col("prev_season_avg_ppr") - pl.col("calculated_ppr"))
    .abs()
    .round(2)
    .alias("season_baseline_absolute_error")
)

test_results.select([
    "player_display_name",
    "season",
    "week",
    "calculated_ppr",
    "linear_regression_prediction",
    "random_forest_prediction",
    "linear_regression_absolute_error",
    "rolling_baseline_absolute_error",
    "season_baseline_absolute_error",
]).sort("linear_regression_absolute_error", descending=True).head(20)

shape: (20, 9)
┌─────────────┬────────┬──────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ player_disp ┆ season ┆ week ┆ calculated ┆ … ┆ random_for ┆ linear_reg ┆ rolling_ba ┆ season_bas │
│ lay_name    ┆ ---    ┆ ---  ┆ _ppr       ┆   ┆ est_predic ┆ ression_ab ┆ seline_abs ┆ eline_abso │
│ ---         ┆ i32    ┆ i32  ┆ ---        ┆   ┆ tion       ┆ solute_err ┆ olute_erro ┆ lute_error │
│ str         ┆        ┆      ┆ f64        ┆   ┆ ---        ┆ …          ┆ …          ┆ ---        │
│             ┆        ┆      ┆            ┆   ┆ f64        ┆ ---        ┆ ---        ┆ f64        │
│             ┆        ┆      ┆            ┆   ┆            ┆ f64        ┆ f64        ┆            │
╞═════════════╪════════╪══════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ Tre Tucker  ┆ 2025   ┆ 3    ┆ 40.9       ┆ … ┆ 6.962419   ┆ 32.52      ┆ 33.0       ┆ 31.75      │
│ Amon-Ra St. ┆ 2025   ┆ 2    ┆ 39.2       ┆ … ┆ 10.256028  ┆ 28.73      ┆ 25.13      ┆ 30.7       │
│ Brown       ┆        ┆      ┆            ┆   ┆            ┆            ┆            ┆            │
│ Puka Nacua  ┆ 2025   ┆ 16   ┆ 46.5       ┆ … ┆ 18.932626  ┆ 27.53      ┆ 20.9       ┆ 24.44      │
│ Amon-Ra St. ┆ 2025   ┆ 15   ┆ 41.4       ┆ … ┆ 13.990254  ┆ 26.61      ┆ 26.37      ┆ 23.44      │
│ Brown       ┆        ┆      ┆            ┆   ┆            ┆            ┆            ┆            │
│ Michael     ┆ 2025   ┆ 11   ┆ 33.5       ┆ … ┆ 7.125559   ┆ 26.02      ┆ 25.67      ┆ 27.82      │
│ Wilson      ┆        ┆      ┆            ┆   ┆            ┆            ┆            ┆            │
│ …           ┆ …      ┆ …    ┆ …          ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ Dontayvion  ┆ 2025   ┆ 13   ┆ 28.0       ┆ … ┆ 6.890154   ┆ 21.61      ┆ 23.03      ┆ 23.41      │
│ Wicks       ┆        ┆      ┆            ┆   ┆            ┆            ┆            ┆            │
│ George      ┆ 2025   ┆ 4    ┆ 33.4       ┆ … ┆ 11.610053  ┆ 21.25      ┆ 19.53      ┆ 19.53      │
│ Pickens     ┆        ┆      ┆            ┆   ┆            ┆            ┆            ┆            │
│ Alec Pierce ┆ 2025   ┆ 18   ┆ 29.2       ┆ … ┆ 7.798118   ┆ 21.17      ┆ 20.13      ┆ 18.19      │
│ Tetairoa    ┆ 2025   ┆ 11   ┆ 33.0       ┆ … ┆ 11.340783  ┆ 20.62      ┆ 20.83      ┆ 21.02      │
│ McMillan    ┆        ┆      ┆            ┆   ┆            ┆            ┆            ┆            │
│ Rome Odunze ┆ 2025   ┆ 2    ┆ 31.8       ┆ … ┆ 11.784326  ┆ 20.5       ┆ 24.47      ┆ 16.1       │
└─────────────┴────────┴──────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [16]:
test_results = test_results.with_columns(
    pl.Series("random_forest_prediction", rf_y_pred)
)

test_results = test_results.with_columns(
    (pl.col("random_forest_prediction") - pl.col("calculated_ppr"))
    .round(2)
    .alias("random_forest_signed_error"),

    (pl.col("random_forest_prediction") - pl.col("calculated_ppr"))
    .abs()
    .round(2)
    .alias("random_forest_absolute_error"),
)

test_results.select([
    "player_display_name",
    "season",
    "week",
    "calculated_ppr",
    "linear_regression_prediction",
    "linear_regression_absolute_error",
    "random_forest_prediction",
    "random_forest_absolute_error",
    "random_forest_signed_error",
]).sort("random_forest_absolute_error", descending=True).head(20)

shape: (20, 9)
┌─────────────┬────────┬──────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ player_disp ┆ season ┆ week ┆ calculated ┆ … ┆ linear_reg ┆ random_for ┆ random_for ┆ random_for │
│ lay_name    ┆ ---    ┆ ---  ┆ _ppr       ┆   ┆ ression_ab ┆ est_predic ┆ est_absolu ┆ est_signed │
│ ---         ┆ i32    ┆ i32  ┆ ---        ┆   ┆ solute_err ┆ tion       ┆ te_error   ┆ _error     │
│ str         ┆        ┆      ┆ f64        ┆   ┆ …          ┆ ---        ┆ ---        ┆ ---        │
│             ┆        ┆      ┆            ┆   ┆ ---        ┆ f64        ┆ f64        ┆ f64        │
│             ┆        ┆      ┆            ┆   ┆ f64        ┆            ┆            ┆            │
╞═════════════╪════════╪══════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ Tre Tucker  ┆ 2025   ┆ 3    ┆ 40.9       ┆ … ┆ 32.52      ┆ 6.962419   ┆ 33.94      ┆ -33.94     │
│ Amon-Ra St. ┆ 2025   ┆ 2    ┆ 39.2       ┆ … ┆ 28.73      ┆ 10.256028  ┆ 28.94      ┆ -28.94     │
│ Brown       ┆        ┆      ┆            ┆   ┆            ┆            ┆            ┆            │
│ Puka Nacua  ┆ 2025   ┆ 16   ┆ 46.5       ┆ … ┆ 27.53      ┆ 18.932626  ┆ 27.57      ┆ -27.57     │
│ Amon-Ra St. ┆ 2025   ┆ 15   ┆ 41.4       ┆ … ┆ 26.61      ┆ 13.990254  ┆ 27.41      ┆ -27.41     │
│ Brown       ┆        ┆      ┆            ┆   ┆            ┆            ┆            ┆            │
│ Michael     ┆ 2025   ┆ 11   ┆ 33.5       ┆ … ┆ 26.02      ┆ 7.125559   ┆ 26.37      ┆ -26.37     │
│ Wilson      ┆        ┆      ┆            ┆   ┆            ┆            ┆            ┆            │
│ …           ┆ …      ┆ …    ┆ …          ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ Drake       ┆ 2025   ┆ 6    ┆ 31.8       ┆ … ┆ 19.02      ┆ 11.007585  ┆ 20.79      ┆ -20.79     │
│ London      ┆        ┆      ┆            ┆   ┆            ┆            ┆            ┆            │
│ Xavier      ┆ 2025   ┆ 7    ┆ 24.2       ┆ … ┆ 18.44      ┆ 3.616403   ┆ 20.58      ┆ -20.58     │
│ Legette     ┆        ┆      ┆            ┆   ┆            ┆            ┆            ┆            │
│ Ryan        ┆ 2025   ┆ 14   ┆ 26.5       ┆ … ┆ 21.85      ┆ 6.030206   ┆ 20.47      ┆ -20.47     │
│ Flournoy    ┆        ┆      ┆            ┆   ┆            ┆            ┆            ┆            │
│ Ja'Marr     ┆ 2025   ┆ 2    ┆ 36.5       ┆ … ┆ 25.45      ┆ 16.099363  ┆ 20.4       ┆ -20.4      │
│ Chase       ┆        ┆      ┆            ┆   ┆            ┆            ┆            ┆            │
│ Drake       ┆ 2025   ┆ 9    ┆ 38.8       ┆ … ┆ 22.08      ┆ 18.443679  ┆ 20.36      ┆ -20.36     │
│ London      ┆        ┆      ┆            ┆   ┆            ┆            ┆            ┆            │
└─────────────┴────────┴──────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [17]:
metrics_comparison = pl.DataFrame({
    "model": [
        "Rolling 3-game baseline",
        "Season-to-date baseline",
        "Linear Regression",
        "Random Forest",
    ],
    "mae": [
        mean_absolute_error(
            test_results["calculated_ppr"],
            test_results["prev_rolling_3_ppr"],
        ),
        mean_absolute_error(
            test_results["calculated_ppr"],
            test_results["prev_season_avg_ppr"],
        ),
        mean_absolute_error(y_test, y_pred),
        mean_absolute_error(y_test, rf_y_pred),
    ],
    "rmse": [
        root_mean_squared_error(
            test_results["calculated_ppr"],
            test_results["prev_rolling_3_ppr"],
        ),
        root_mean_squared_error(
            test_results["calculated_ppr"],
            test_results["prev_season_avg_ppr"],
        ),
        root_mean_squared_error(y_test, y_pred),
        root_mean_squared_error(y_test, rf_y_pred),
    ],
}).with_columns(
    pl.col("mae").round(2),
    pl.col("rmse").round(2),
)

metrics_comparison

shape: (4, 3)
┌─────────────────────────┬──────┬──────┐
│ model                   ┆ mae  ┆ rmse │
│ ---                     ┆ ---  ┆ ---  │
│ str                     ┆ f64  ┆ f64  │
╞═════════════════════════╪══════╪══════╡
│ Rolling 3-game baseline ┆ 4.56 ┆ 6.41 │
│ Season-to-date baseline ┆ 4.45 ┆ 6.27 │
│ Linear Regression       ┆ 4.39 ┆ 6.0  │
│ Random Forest           ┆ 4.46 ┆ 6.12 │
└─────────────────────────┴──────┴──────┘

Random Forest was tested as a comparison model using the same training and test split as Linear Regression. It performed worse than Linear Regression on the 2025 test season, so Linear Regression remains the preferred current model. This suggests that, with the current feature set, a more flexible model may be fitting noise rather than improving generalization.

In [18]:
coefficients = pl.DataFrame({
    "feature": FEATURE_COLUMNS,
    "coefficient": model.coef_,
}).sort("coefficient", descending=True)

coefficients

shape: (6, 2)
┌─────────────────────────────────┬─────────────┐
│ feature                         ┆ coefficient │
│ ---                             ┆ ---         │
│ str                             ┆ f64         │
╞═════════════════════════════════╪═════════════╡
│ prev_rolling_3_targets          ┆ 0.508796    │
│ prev_season_avg_ppr             ┆ 0.432601    │
│ prev_rolling_3_receptions       ┆ 0.28093     │
│ prev_rolling_3_receiving_yards  ┆ 0.020157    │
│ prev_defense_wr_ppr_allowed_av… ┆ 0.015629    │
│ prev_rolling_3_ppr              ┆ -0.068516   │
└─────────────────────────────────┴─────────────┘

In [19]:
rf_feature_importance = pl.DataFrame({
    "feature": FEATURE_COLUMNS,
    "importance": random_forest.feature_importances_,
}).sort("importance", descending=True)

rf_feature_importance

shape: (6, 2)
┌─────────────────────────────────┬────────────┐
│ feature                         ┆ importance │
│ ---                             ┆ ---        │
│ str                             ┆ f64        │
╞═════════════════════════════════╪════════════╡
│ prev_season_avg_ppr             ┆ 0.521674   │
│ prev_rolling_3_targets          ┆ 0.118991   │
│ prev_defense_wr_ppr_allowed_av… ┆ 0.117753   │
│ prev_rolling_3_ppr              ┆ 0.098848   │
│ prev_rolling_3_receiving_yards  ┆ 0.094956   │
│ prev_rolling_3_receptions       ┆ 0.047778   │
└─────────────────────────────────┴────────────┘

Opponent defensive strength features were tested using prior season-to-date WR receiving yards allowed and prior season-to-date WR PPR allowed. These features were prediction-safe because they were shifted before joining to player-week rows.

The defensive features produced only a very small change in Linear Regression performance. Linear Regression remained the best model, but the improvement over the baselines is still modest. The coefficients for both defensive features were small, suggesting that player-level usage and production features are still carrying most of the signal.

Single-player prediction using the reusable src/predict.py helpers, so a projection can be generated for a player without re-running this entire notebook.

In [20]:
from src.predict import predict_next_week_ppr

lamb_projection = predict_next_week_ppr(model, dataset, "CeeDee Lamb")
lamb_projection

15.08

Model persistence with src/modeling.py save_model()/load_model(), so the trained model can be reused for prediction without retraining or opening this notebook.

In [21]:
from src.modeling import save_model, load_model

model_path = project_root / "models" / "linear_regression.joblib"
save_model(model, model_path)
loaded_model = load_model(model_path)

loaded_lamb_projection = predict_next_week_ppr(loaded_model, dataset, "CeeDee Lamb")
loaded_lamb_projection

15.08